import { useQuery } from "@tanstack/react-query";
import { AlertTriangle, ArrowRight, Clock3, Flame, PhoneCall, Sparkles, Target } from "lucide-react";
import { Link } from "react-router-dom";
import { salesApi } from "../salesApi";

const money = (value: number) => `₹${Math.round(value).toLocaleString("en-IN")}`;
const routeFor = (type: "lead" | "opportunity" | "customer") => type === "lead" ? "/sales/leads" : type === "opportunity" ? "/sales/pipeline" : "/sales/customers";
const urgencyStyle = { CRITICAL: "bg-red-100 text-red-700", HIGH: "bg-amber-100 text-amber-700", NORMAL: "bg-slate-100 text-slate-600" };

export const DailySalesCockpit = () => {
  const query = useQuery({ queryKey: ["daily-sales-cockpit"], queryFn: salesApi.dailyCockpit, refetchInterval: 60_000 });
  const data = query.data;
  const totalPipeline = data?.highPotentialClients.reduce((sum, client) => sum + client.weightedValue, 0) ?? 0;

  return <section className="space-y-5">
    <div className="rounded-3xl bg-gradient-to-br from-slate-950 via-slate-900 to-teal-950 p-6 text-white shadow-xl sm:p-8">
      <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.2em] text-teal-300"><Sparkles size={15}/> Daily Sales Cockpit</p><h2 className="mt-2 text-2xl font-bold">What Should I Do Now?</h2><p className="mt-1 text-sm text-slate-300">Your five highest-impact actions, ranked by urgency × deal value × conversion probability ÷ effort.</p></div><span className="rounded-full bg-white/10 px-3 py-1 text-xs text-slate-200">Refreshes every minute</span></div>
      {query.isLoading ? <p className="mt-6 text-sm text-slate-300">Prioritizing today’s work…</p> : query.isError ? <p role="alert" className="mt-6 rounded-xl bg-red-500/15 p-4 text-sm text-red-200">{query.error.message}</p> : !data?.nextBestActions.length ? <p className="mt-6 rounded-xl bg-white/5 p-5 text-sm text-slate-300">No urgent actions detected. Keep CRM activities and scheduled follow-up metadata current.</p> : <div className="mt-6 grid gap-3">{data.nextBestActions.map((action, index) => <article key={action.id} className="rounded-2xl border border-white/10 bg-white/[0.07] p-4"><div className="flex gap-3"><span className="grid size-8 shrink-0 place-items-center rounded-full bg-teal-400 font-bold text-slate-950">{index + 1}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold">{action.clientName} · {action.title}</h3><span className={`rounded-full px-2 py-0.5 text-[10px] font-bold ${urgencyStyle[action.urgency]}`}>{action.urgency}</span><span className="text-xs text-slate-400">{action.confidenceScore}% confidence</span></div><p className="mt-1 text-sm text-teal-100">{action.recommendedAction}</p><div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-xs text-slate-300"><span className="flex items-center gap-1"><PhoneCall size={12}/>{action.recommendedChannel}</span><span className="flex items-center gap-1"><Clock3 size={12}/>{action.suggestedTiming}</span><span>{money(action.dealValue)}</span></div><p className="mt-2 text-xs text-slate-400">{action.reasonCodes.join(" · ")}</p>{action.draftScriptOrNote && <details className="mt-2 text-xs"><summary className="cursor-pointer text-teal-300">Suggested talking points</summary><p className="mt-2 rounded-lg bg-black/20 p-3 text-slate-200">{action.draftScriptOrNote}</p></details>}</div><Link aria-label={`Open ${action.clientName}`} to={routeFor(action.entityType)} className="self-center rounded-lg p-2 text-teal-300 hover:bg-white/10"><ArrowRight size={18}/></Link></div></article>)}</div>}
    </div>

    {data && <div className="grid gap-4 lg:grid-cols-3"><section className="rounded-2xl border bg-white p-5 shadow-soft"><div className="flex items-center gap-2 font-semibold"><AlertTriangle size={17} className="text-red-600"/> Execution alerts</div><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-xl bg-red-50 p-4"><p className="text-2xl font-bold text-red-700">{data.slaBreaches}</p><p className="text-xs text-red-600">Inbound SLA breaches</p></div><div className="rounded-xl bg-amber-50 p-4"><p className="text-2xl font-bold text-amber-700">{data.overdueFollowUps}</p><p className="text-xs text-amber-600">Overdue follow-ups</p></div></div></section><section className="rounded-2xl border bg-white p-5 shadow-soft"><div className="flex items-center gap-2 font-semibold"><Target size={17} className="text-blue-600"/> Conversion probability</div><div className="mt-4 space-y-3">{[["High · 70%+", data.probabilityBreakdown.high, "bg-emerald-500"], ["Medium · 40–69%", data.probabilityBreakdown.medium, "bg-amber-500"], ["Low · below 40%", data.probabilityBreakdown.low, "bg-slate-400"]].map(([label, count, color]) => <div key={String(label)}><div className="flex justify-between text-xs"><span>{label}</span><strong>{count}</strong></div><div className="mt-1 h-1.5 rounded bg-slate-100"><div className={`h-full rounded ${color}`} style={{width: `${Math.min(100, Number(count) * 20)}%`}}/></div></div>)}</div></section><section className="rounded-2xl border bg-white p-5 shadow-soft"><div className="flex items-center gap-2 font-semibold"><Flame size={17} className="text-orange-600"/> High-potential clients</div><p className="mt-1 text-xs text-slate-500">Weighted pipeline {money(totalPipeline)}</p><div className="mt-3 space-y-2">{data.highPotentialClients.map((client) => <div key={client.id} className="flex items-center justify-between rounded-xl bg-slate-50 p-3 text-sm"><div><p className="font-semibold">{client.name}</p><p className="text-xs text-slate-500">{client.stage} · {money(client.value)}</p></div><strong className="text-emerald-700">{client.probability}%</strong></div>)}{!data.highPotentialClients.length && <p className="text-sm text-slate-400">No opportunities at 70%+ yet.</p>}</div></section></div>}
  </section>;
};
