import { api } from "@/api/client";
export interface ContributionEmployee { _id:string; firstName:string; lastName:string; employeeId:string; officialEmail:string }
export interface WeeklyUpdate { _id:string; employee:ContributionEmployee; weekStart:string; accomplishments:string[]; currentPriorities:string[]; blockers:{description:string;category:string;external:boolean}[]; helpNeeded?:string; nextWeekPlan?:string; managerComment?:string; acknowledgedBy?:{name:string}; acknowledgedAt?:string }
export interface CheckIn { _id:string; employee:ContributionEmployee; manager:{name:string}; meetingDate:string; accomplishments?:string; challenges?:string; supportNeeded?:string; careerGoals?:string; agreedActions:{text:string;dueDate?:string;completed:boolean}[]; nextReviewDate?:string; employeeResponse?:string; acknowledgedAt?:string }
export interface ContributionReview { _id:string; employee:ContributionEmployee; period:string; selfReview?:{accomplishments:string;impact:string;collaboration:string;growth:string;challenges?:string;evidenceLinks:string[]}; managerReview?:{ratings:Record<string,number>;comment:string;reviewedBy:{name:string}}; employeeResponse?:string; status:string }
export interface ContributionSnapshot { _id:string; employee:ContributionEmployee; period:string; totalScore:number; classification:string; evidenceCoverage:number; components:{key:string;label:string;score:number;configuredWeight:number;effectiveWeight:number;contribution:number;available:boolean;explanation:string}[]; alerts:{type:string;severity:string;title:string;detail:string;private:boolean}[]; calculatedAt:string }
const query = (employee?:string) => employee ? `?employee=${encodeURIComponent(employee)}` : "";
export const contributionApi = {
  employees:()=>api.get<{items:ContributionEmployee[]}>("/api/v1/contribution/employees"),
  weekly:(employee?:string)=>api.get<{items:WeeklyUpdate[]}>(`/api/v1/contribution/weekly${query(employee)}`), saveWeekly:(body:unknown)=>api.put("/api/v1/contribution/weekly",body), acknowledgeWeekly:(id:string,body:unknown)=>api.patch(`/api/v1/contribution/weekly/${id}/acknowledge`,body),
  checkIns:(employee?:string)=>api.get<{items:CheckIn[]}>(`/api/v1/contribution/check-ins${query(employee)}`), createCheckIn:(body:unknown)=>api.post("/api/v1/contribution/check-ins",body), respondCheckIn:(id:string,body:unknown)=>api.patch(`/api/v1/contribution/check-ins/${id}/respond`,body),
  reviews:(employee?:string)=>api.get<{items:ContributionReview[]}>(`/api/v1/contribution/reviews${query(employee)}`), selfReview:(body:unknown)=>api.put("/api/v1/contribution/reviews/self",body), managerReview:(id:string,body:unknown)=>api.patch(`/api/v1/contribution/reviews/${id}/manager`,body), respondReview:(id:string,body:unknown)=>api.patch(`/api/v1/contribution/reviews/${id}/respond`,body),
  snapshots:(employee?:string)=>api.get<{items:ContributionSnapshot[]}>(`/api/v1/contribution/snapshots${query(employee)}`), calculate:(body:unknown)=>api.post("/api/v1/contribution/snapshots/calculate",body)
};
