import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { api } from "@/api/client";
import { Button } from "@/components/ui/Button";

interface Totals { total: number; completed: number; open: number; overdue: number; review: number; blocked: number; remainingHours: number; onTimeRate: number | null; onTime: number; datedCompletions: number }
interface Analytics extends Totals {
  generatedAt: string; employeeCount: number; activeCount: number;
  people: (Totals & { id: string; name: string; employeeId: string; status: string })[];
  attention: { id: string; name: string; employee: string; status: string; deadline: string; overdue: boolean }[];
}
export const AdminAnalytics = () => {
  const [search, setSearch] = useState("");
  const [onlyOverdue, setOnlyOverdue] = useState(false);
  const query = useQuery({ queryKey: ["dashboard", "admin-analytics"], queryFn: () => api.get<Analytics>("/api/v1/dashboard/analytics"), refetchInterval: 30_000 });
  const data = query.data;
  if (!data) return <main className="p-8" aria-live="polite">{query.isError ? <><p role="alert">Analytics could not be loaded. Please try again.</p><Button onClick={() => void query.refetch()}>Retry</Button></> : "Loading workforce analytics…"}</main>;
  const people = data.people.filter((person) => `${person.name} ${person.employeeId}`.toLowerCase().includes(search.toLowerCase()) && (!onlyOverdue || person.overdue > 0)).sort((a, b) => b.overdue - a.overdue || b.open - a.open || a.name.localeCompare(b.name));
  const cards = [
    { label: "Employees", value: data.employeeCount, detail: `${data.activeCount} with Active employment status`, link: "/employees" },
    { label: "Open tasks", value: data.open, detail: "Includes work waiting for review", link: "/work" },
    { label: "Overdue tasks", value: data.overdue, detail: "Open tasks past their deadline", link: "#attention" },
    { label: "Waiting for review", value: data.review, detail: "Submitted work awaiting a decision", link: "#attention" }
  ];
  return <main className="mx-auto w-full max-w-[1440px] space-y-6 p-4 sm:p-8">
    <header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-medium text-brand-700">Super Admin overview</p><h1 className="mt-1 text-3xl font-bold">Your team at a glance</h1><p className="mt-2 text-sm text-slate-500">Current task status across your organization. Deleted and cancelled tasks are excluded.</p></div><Button variant="secondary" disabled={query.isFetching} onClick={() => void query.refetch()}>{query.isFetching ? "Refreshing…" : "Refresh"}</Button></header>
    <p className="text-xs text-slate-500">Updated {new Date(data.generatedAt).toLocaleString()} · Refreshes every 30 seconds while this page is open · All-time task totals</p>
    {query.isError && <p role="alert" className="rounded-xl bg-amber-50 p-4 text-amber-800">Refresh failed. These are the last successfully loaded numbers.</p>}
    <section aria-label="Overview totals" className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map((card) => <Link key={card.label} to={card.link} className="rounded-2xl border bg-white p-5 shadow-sm hover:border-brand-400 focus-visible:outline focus-visible:outline-brand-600"><p className="text-sm text-slate-600">{card.label}</p><p className="my-3 text-4xl font-bold">{card.value}</p><p className="text-xs text-slate-500">{card.detail}</p></Link>)}</section>
    <div className="grid gap-6 lg:grid-cols-2">
      <section className="rounded-2xl border bg-white p-5"><h2 className="text-lg font-semibold">How much work is finished?</h2><p className="mt-3 text-3xl font-bold">{data.completed} <span className="text-base font-normal text-slate-500">of {data.total} tasks completed</span></p><div className="my-4 h-3 overflow-hidden rounded-full bg-slate-100" role="progressbar" aria-label="Completed tasks" aria-valuenow={data.completed} aria-valuemin={0} aria-valuemax={Math.max(data.total, 1)}><div className="h-full bg-emerald-500" style={{ width: `${data.total ? data.completed / data.total * 100 : 0}%` }}/></div><p className="text-sm text-slate-600">{data.total ? `${Math.round(data.completed / data.total * 100)}% completed · ${data.open} still open · ${data.blocked} blocked` : "No tasks yet. Create a task to start tracking delivery."}</p><Link className="mt-4 inline-block text-sm text-brand-700 underline" to="/work">Open task board</Link></section>
      <section className="rounded-2xl border bg-white p-5"><h2 className="text-lg font-semibold">Are tasks delivered on time?</h2><p className="mt-3 text-3xl font-bold">{data.onTimeRate === null ? "No data yet" : `${data.onTimeRate}%`}</p><p className="mt-3 text-sm text-slate-600">{data.datedCompletions ? `${data.onTime} of ${data.datedCompletions} completed tasks with a recorded completion date met their deadline.` : "This rate appears after a task has a recorded completion date."}</p><p className="mt-3 text-xs text-slate-500">{data.completed - data.datedCompletions} completed tasks without a completion date are excluded. This measures delivery timing, not employee performance.</p></section>
    </div>
    <section id="attention" className="scroll-mt-6 rounded-2xl border bg-white p-5"><h2 className="text-lg font-semibold">What needs your attention?</h2><p className="mt-1 text-sm text-slate-500">Overdue, blocked, or awaiting review. Showing up to 12 tasks, earliest deadline first. A task may have more than one issue.</p><div className="mt-4 divide-y">{data.attention.length ? data.attention.map((task) => <Link key={task.id} to={`/work?task=${task.id}`} className="flex flex-wrap items-center justify-between gap-3 py-4 hover:bg-slate-50"><div><p className="font-medium">{task.name}</p><p className="text-sm text-slate-500">{task.employee} · Due {new Date(task.deadline).toLocaleString()}</p></div><span className={`rounded-full px-3 py-1 text-xs ${task.overdue ? "bg-red-50 text-red-700" : "bg-amber-50 text-amber-800"}`}>{task.overdue ? "Overdue · " : ""}{task.status.replaceAll("_", " ").toLowerCase()} →</span></Link>) : <p className="py-5 text-sm text-slate-500">No overdue, blocked, or review tasks right now.</p>}</div></section>
    <section className="rounded-2xl border bg-white p-5"><h2 className="text-lg font-semibold">Who needs help with their workload?</h2><p className="mt-1 text-sm text-slate-500">Employees with overdue tasks appear first. Remaining hours are estimates for open work, excluding tasks in review.</p><div className="my-4 flex flex-wrap items-center gap-4"><input aria-label="Search employees" placeholder="Search employee name or ID" value={search} onChange={(event) => setSearch(event.target.value)} className="h-11 w-full max-w-sm rounded-xl border px-3"/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={onlyOverdue} onChange={(event) => setOnlyOverdue(event.target.checked)}/>Only employees with overdue tasks</label></div><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead><tr className="border-b text-slate-500">{["Employee", "Open", "Overdue", "In review", "Completed", "Hours remaining"].map((label) => <th className="px-2 py-3 font-medium" scope="col" key={label}>{label}</th>)}</tr></thead><tbody>{people.map((person) => <tr className="border-b last:border-0" key={person.id}><td className="px-2 py-3"><Link to={`/employees/${person.id}`} className="font-medium text-brand-700 underline">{person.name}</Link><p className="text-xs text-slate-500">{person.employeeId} · {person.status.replaceAll("_", " ").toLowerCase()}</p></td><td className="px-2">{person.open}</td><td className={`px-2 ${person.overdue ? "font-semibold text-red-700" : ""}`}>{person.overdue}</td><td className="px-2">{person.review}</td><td className="px-2">{person.completed}</td><td className="px-2">{person.remainingHours}h</td></tr>)}</tbody></table></div>{!people.length && <p className="py-5 text-sm text-slate-500">No employees match these filters.</p>}<p className="mt-4 text-xs text-slate-500">Showing {people.length} of {data.employeeCount} employees. Workload counts help plan support; they are not performance scores.</p></section>
  </main>;
};
