import { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, CalendarRange, CheckCircle2, ClipboardCheck, HeartHandshake, RefreshCw, TrendingUp } from "lucide-react";
import { Button } from "@/components/ui/Button"; import { Input } from "@/components/ui/Input"; import { useAuth } from "@/features/auth/AuthProvider"; import { contributionApi } from "@/features/contribution/contributionApi";
const field = "mt-2 min-h-24 w-full rounded-xl border bg-white px-3.5 py-3 text-sm outline-none focus:border-brand-500 focus:ring-2 focus:ring-brand-100";
const split = (value:string) => value.split("\n").map((line)=>line.trim()).filter(Boolean);
const currentMonday = () => { const d=new Date(); const day=(d.getDay()+6)%7; d.setDate(d.getDate()-day); return d.toISOString().slice(0,10); };
const areas = ["delivery","quality","reliability","impact","collaboration","growth"] as const;
export const ContributionPage = () => {
  const { user }=useAuth(); const qc=useQueryClient(); const management=user?.role!=="EMPLOYEE"; const [tab,setTab]=useState("overview"); const [employee,setEmployee]=useState(""); const [period,setPeriod]=useState(new Date().toISOString().slice(0,7));
  const people=useQuery({queryKey:["contribution-employees"],queryFn:contributionApi.employees}); useEffect(()=>{ if(!employee&&people.data?.items[0]) setEmployee(people.data.items[0]._id); },[people.data,employee]);
  const weekly=useQuery({queryKey:["contribution-weekly",employee],queryFn:()=>contributionApi.weekly(employee),enabled:!!employee}); const checkIns=useQuery({queryKey:["contribution-checkins",employee],queryFn:()=>contributionApi.checkIns(employee),enabled:!!employee}); const reviews=useQuery({queryKey:["contribution-reviews",employee],queryFn:()=>contributionApi.reviews(employee),enabled:!!employee}); const snapshots=useQuery({queryKey:["contribution-snapshots",employee],queryFn:()=>contributionApi.snapshots(employee),enabled:!!employee});
  const review=reviews.data?.items.find((x)=>x.period===period); const snapshot=snapshots.data?.items.find((x)=>x.period===period) ?? snapshots.data?.items[0];
  const refresh=()=>Promise.all([qc.invalidateQueries({queryKey:["contribution-weekly"]}),qc.invalidateQueries({queryKey:["contribution-checkins"]}),qc.invalidateQueries({queryKey:["contribution-reviews"]}),qc.invalidateQueries({queryKey:["contribution-snapshots"]})]);
  const [week,setWeek]=useState({weekStart:currentMonday(),accomplishments:"",priorities:"",blocker:"",helpNeeded:"",nextWeekPlan:"",external:false}); const saveWeek=useMutation({mutationFn:()=>contributionApi.saveWeekly({weekStart:week.weekStart,accomplishments:split(week.accomplishments),currentPriorities:split(week.priorities),blockers:week.blocker?[{description:week.blocker,category:"OTHER",external:week.external}]:[],helpNeeded:week.helpNeeded||undefined,nextWeekPlan:week.nextWeekPlan||undefined}),onSuccess:async()=>{setWeek({...week,accomplishments:"",priorities:"",blocker:"",helpNeeded:"",nextWeekPlan:""});await refresh();}});
  const acknowledge=useMutation({mutationFn:(id:string)=>contributionApi.acknowledgeWeekly(id,{managerComment:"Reviewed — support needs and blockers acknowledged."}),onSuccess:refresh});
  const [self,setSelf]=useState({accomplishments:"",impact:"",collaboration:"",growth:"",challenges:"",links:""}); const saveSelf=useMutation({mutationFn:()=>contributionApi.selfReview({period,...self,evidenceLinks:split(self.links),links:undefined}),onSuccess:refresh});
  const [ratings,setRatings]=useState<Record<string,number>>(Object.fromEntries(areas.map((x)=>[x,3]))); const [managerComment,setManagerComment]=useState(""); const saveManager=useMutation({mutationFn:()=>contributionApi.managerReview(review!._id,{ratings,comment:managerComment}),onSuccess:refresh});
  const [response,setResponse]=useState(""); const respondReview=useMutation({mutationFn:()=>contributionApi.respondReview(review!._id,{employeeResponse:response}),onSuccess:refresh});
  const [meeting,setMeeting]=useState({meetingDate:new Date().toISOString().slice(0,10),accomplishments:"",challenges:"",supportNeeded:"",careerGoals:"",actions:"",nextReviewDate:""}); const createMeeting=useMutation({mutationFn:()=>contributionApi.createCheckIn({employee,...meeting,agreedActions:split(meeting.actions).map((text)=>({text,completed:false})),nextReviewDate:meeting.nextReviewDate||undefined}),onSuccess:refresh});
  const respondMeeting=useMutation({mutationFn:({id,text}:{id:string;text:string})=>contributionApi.respondCheckIn(id,{employeeResponse:text}),onSuccess:refresh});
  const calculate=useMutation({mutationFn:()=>contributionApi.calculate({employee,period}),onSuccess:refresh});
  const selectedName=useMemo(()=>{const p=people.data?.items.find((x)=>x._id===employee);return p?`${p.firstName} ${p.lastName}`:"employee";},[people.data,employee]);
  return <main className="flex-1 overflow-x-clip px-4 py-6 sm:px-8 sm:py-8"><div className="mx-auto w-full min-w-0 max-w-[1440px]"><div className="flex min-w-0 flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div className="min-w-0"><p className="text-sm font-medium text-brand-700">Contribution & support</p><h1 className="mt-1 break-words text-2xl font-semibold sm:text-3xl">Evidence-based contribution</h1><p className="mt-2 max-w-3xl break-words text-sm leading-6 text-slate-500">Outcomes, quality, impact and growth—without screen, mouse or webcam surveillance. Missing evidence is excluded, and external blockers do not reduce reliability.</p></div><div className="flex w-full min-w-0 flex-col gap-2 sm:w-auto sm:flex-row">{management&&<select className="h-11 w-full min-w-0 rounded-xl border bg-white px-3 text-sm sm:max-w-64" value={employee} onChange={(e)=>setEmployee(e.target.value)}>{people.data?.items.map((p)=><option key={p._id} value={p._id}>{p.firstName} {p.lastName}</option>)}</select>}<Input className="w-full sm:w-40" type="month" value={period} onChange={(e)=>setPeriod(e.target.value)}/></div></div>
  <div className="mt-6 flex flex-wrap gap-2">{[["overview","Overview",TrendingUp],["weekly","Weekly updates",ClipboardCheck],["reviews","Reviews",CheckCircle2],["checkins","1:1 check-ins",HeartHandshake]].map(([key,label,Icon])=><Button key={String(key)} variant={tab===key?"primary":"secondary"} onClick={()=>setTab(String(key))}><Icon size={15}/>{String(label)}</Button>)}</div>
  {tab==="overview"&&<div className="mt-6 min-w-0 space-y-5"><section className="min-w-0 overflow-hidden rounded-2xl border bg-white p-4 shadow-soft sm:p-6"><div className="flex min-w-0 flex-col items-start justify-between gap-4 sm:flex-row"><div className="min-w-0"><h2 className="break-words font-semibold">{selectedName} · {snapshot?.period??period}</h2><p className="mt-1 break-words text-xs leading-5 text-slate-400">Private to the employee and authorized management. This is decision support, not an automated employment decision.</p></div><Button className="h-auto min-h-11 w-full whitespace-normal py-2 sm:w-auto" disabled={!employee||calculate.isPending} onClick={()=>calculate.mutate()}><RefreshCw size={15}/>Calculate from current evidence</Button></div>{snapshot?<><div className="mt-6 grid min-w-0 gap-4 sm:grid-cols-3"><Metric label="Contribution score" value={`${snapshot.totalScore}%`}/><Metric label="Evidence coverage" value={`${snapshot.evidenceCoverage}%`}/><Metric label="Classification" value={snapshot.classification.replaceAll("_"," ")}/></div><div className="mt-6 grid min-w-0 gap-4 lg:grid-cols-2">{snapshot.components.map((c)=><div key={c.key} className={`min-w-0 overflow-hidden rounded-xl border p-4 ${c.available?"":"bg-slate-50 opacity-70"}`}><div className="flex min-w-0 justify-between gap-3"><p className="min-w-0 break-words font-medium">{c.label}</p><p className="shrink-0 font-semibold">{c.available?`${c.score}%`:`Excluded`}</p></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-brand-500" style={{width:`${c.score}%`}}/></div><p className="mt-2 break-words text-xs text-slate-500">{c.explanation}</p><p className="mt-1 break-words text-[11px] text-slate-400">Configured {c.configuredWeight}% · effective {c.effectiveWeight}%</p></div>)}</div>{snapshot.alerts.length>0&&<div className="mt-6"><h3 className="font-semibold">Private support signals</h3><div className="mt-3 grid min-w-0 gap-3 sm:grid-cols-2">{snapshot.alerts.map((a)=><div className="min-w-0 rounded-xl border border-amber-200 bg-amber-50 p-4" key={a.type}><div className="flex min-w-0 gap-2"><AlertTriangle size={16} className="mt-0.5 shrink-0 text-amber-600"/><div className="min-w-0"><p className="break-words text-sm font-semibold">{a.title}</p><p className="mt-1 break-words text-xs text-amber-800">{a.detail}</p></div></div></div>)}</div></div>}</>:<p className="py-16 text-center text-sm text-slate-400">Calculate the first contribution summary for this period.</p>}</section></div>}
  {tab==="weekly"&&<div className="mt-6 grid gap-5 xl:grid-cols-[.9fr_1.1fr]">{!management&&<form className="rounded-2xl border bg-white p-6 shadow-soft" onSubmit={(e)=>{e.preventDefault();saveWeek.mutate();}}><h2 className="font-semibold">Submit weekly outcome update</h2><label className="mt-4 block text-sm font-medium">Week starting<Input type="date" className="mt-2" value={week.weekStart} onChange={(e)=>setWeek({...week,weekStart:e.target.value})}/></label><Area label="Accomplishments (one per line)" value={week.accomplishments} onChange={(v)=>setWeek({...week,accomplishments:v})}/><Area label="Current priorities" value={week.priorities} onChange={(v)=>setWeek({...week,priorities:v})}/><Area label="Blocker, if any" value={week.blocker} onChange={(v)=>setWeek({...week,blocker:v})}/><label className="mt-3 flex items-center gap-2 text-sm"><input type="checkbox" checked={week.external} onChange={(e)=>setWeek({...week,external:e.target.checked})}/>This blocker is outside my control</label><Area label="Help needed" value={week.helpNeeded} onChange={(v)=>setWeek({...week,helpNeeded:v})}/><Area label="Next week plan" value={week.nextWeekPlan} onChange={(v)=>setWeek({...week,nextWeekPlan:v})}/><Button className="mt-5" disabled={saveWeek.isPending}>Save weekly update</Button></form>}<section className="rounded-2xl border bg-white shadow-soft"><h2 className="border-b p-5 font-semibold">Recent updates</h2><div className="divide-y">{weekly.data?.items.map((x)=><div className="p-5" key={x._id}><p className="text-sm font-semibold">Week of {new Date(x.weekStart).toLocaleDateString()}</p><ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-slate-600">{x.accomplishments.map((a)=><li key={a}>{a}</li>)}</ul>{x.blockers.map((b)=><p className="mt-2 rounded-lg bg-amber-50 p-2 text-xs text-amber-800" key={b.description}>Blocker: {b.description}{b.external?" · external":""}</p>)}{x.helpNeeded&&<p className="mt-2 text-xs text-slate-500">Help needed: {x.helpNeeded}</p>}{x.acknowledgedAt?<p className="mt-3 text-xs font-medium text-emerald-700">Acknowledged by {x.acknowledgedBy?.name??"manager"}</p>:management&&<Button className="mt-3 h-9" variant="secondary" onClick={()=>acknowledge.mutate(x._id)}>Acknowledge & support</Button>}</div>)}{weekly.data?.items.length===0&&<Empty text="No weekly updates yet."/>}</div></section></div>}
  {tab==="reviews"&&<div className="mt-6 grid gap-5 xl:grid-cols-2">{!management&&<form className="rounded-2xl border bg-white p-6 shadow-soft" onSubmit={(e)=>{e.preventDefault();saveSelf.mutate();}}><h2 className="font-semibold">Self review · {period}</h2><Area label="Key accomplishments" value={self.accomplishments} onChange={(v)=>setSelf({...self,accomplishments:v})}/><Area label="Business or customer impact" value={self.impact} onChange={(v)=>setSelf({...self,impact:v})}/><Area label="Collaboration" value={self.collaboration} onChange={(v)=>setSelf({...self,collaboration:v})}/><Area label="Learning and growth" value={self.growth} onChange={(v)=>setSelf({...self,growth:v})}/><Area label="Challenges and context" value={self.challenges} onChange={(v)=>setSelf({...self,challenges:v})}/><Area label="Evidence links (one URL per line)" value={self.links} onChange={(v)=>setSelf({...self,links:v})}/><Button className="mt-5" disabled={saveSelf.isPending}>Submit self review</Button></form>}<section className="rounded-2xl border bg-white p-6 shadow-soft"><h2 className="font-semibold">Review record · {period}</h2>{review?<><p className="mt-3 text-xs font-medium text-brand-700">{review.status.replaceAll("_"," ")}</p>{review.selfReview&&<div className="mt-4 rounded-xl bg-slate-50 p-4 text-sm"><p className="font-medium">Employee evidence</p><p className="mt-2 text-slate-600">{review.selfReview.accomplishments}</p><p className="mt-2 text-slate-600">Impact: {review.selfReview.impact}</p></div>}{management&&<form className="mt-5" onSubmit={(e)=>{e.preventDefault();saveManager.mutate();}}><p className="text-sm font-medium">Manager evidence ratings</p><div className="mt-3 grid grid-cols-2 gap-3">{areas.map((a)=><label className="text-xs capitalize" key={a}>{a}<Input type="number" min="1" max="5" className="mt-1" value={ratings[a]} onChange={(e)=>setRatings({...ratings,[a]:Number(e.target.value)})}/></label>)}</div><Area label="Evidence and coaching comment" value={managerComment} onChange={setManagerComment}/><Button className="mt-4" disabled={saveManager.isPending}>Save manager review</Button></form>}{review.managerReview&&<div className="mt-5 rounded-xl border p-4"><p className="text-sm font-medium">Manager review</p><p className="mt-2 text-sm text-slate-600">{review.managerReview.comment}</p></div>}{!management&&review.managerReview&&!review.employeeResponse&&<form onSubmit={(e)=>{e.preventDefault();respondReview.mutate();}}><Area label="Employee response / context" value={response} onChange={setResponse}/><Button className="mt-4">Acknowledge with response</Button></form>}</>:<Empty text="No review record for this period."/>}</section></div>}
  {tab==="checkins"&&<div className="mt-6 grid gap-5 xl:grid-cols-[.9fr_1.1fr]">{management&&<form className="rounded-2xl border bg-white p-6 shadow-soft" onSubmit={(e)=>{e.preventDefault();createMeeting.mutate();}}><h2 className="font-semibold">Record private 1:1</h2><label className="mt-4 block text-sm font-medium">Meeting date<Input type="date" className="mt-2" value={meeting.meetingDate} onChange={(e)=>setMeeting({...meeting,meetingDate:e.target.value})}/></label><Area label="Accomplishments" value={meeting.accomplishments} onChange={(v)=>setMeeting({...meeting,accomplishments:v})}/><Area label="Challenges" value={meeting.challenges} onChange={(v)=>setMeeting({...meeting,challenges:v})}/><Area label="Support needed" value={meeting.supportNeeded} onChange={(v)=>setMeeting({...meeting,supportNeeded:v})}/><Area label="Career goals" value={meeting.careerGoals} onChange={(v)=>setMeeting({...meeting,careerGoals:v})}/><Area label="Agreed actions (one per line)" value={meeting.actions} onChange={(v)=>setMeeting({...meeting,actions:v})}/><label className="mt-4 block text-sm font-medium">Next review date<Input type="date" className="mt-2" value={meeting.nextReviewDate} onChange={(e)=>setMeeting({...meeting,nextReviewDate:e.target.value})}/></label><Button className="mt-5">Save check-in</Button></form>}<section className="rounded-2xl border bg-white shadow-soft"><h2 className="border-b p-5 font-semibold">Check-in history</h2><div className="divide-y">{checkIns.data?.items.map((x)=><CheckInCard key={x._id} item={x} employeeMode={!management} onRespond={(text)=>respondMeeting.mutate({id:x._id,text})}/>) }{checkIns.data?.items.length===0&&<Empty text="No check-ins recorded yet."/>}</div></section></div>}
  </div></main>;
};
const Metric=({label,value}:{label:string;value:string})=><div className="min-w-0 overflow-hidden rounded-xl bg-brand-50 p-4"><p className="break-words text-xs text-brand-700">{label}</p><p className="mt-1 break-words text-xl font-semibold">{value}</p></div>;
const areaPlaceholder = (label: string) => label.toLowerCase().includes("link")
  ? "https://example.com — enter one URL per line"
  : `Enter ${label.replace(/\s*\([^)]*\)\s*/g, "").toLowerCase()}...`;
const Area=({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void})=><label className="mt-4 block text-sm font-medium">{label}<textarea className={field} placeholder={areaPlaceholder(label)} value={value} onChange={(e)=>onChange(e.target.value)}/></label>;
const Empty=({text}:{text:string})=><p className="p-10 text-center text-sm text-slate-400">{text}</p>;
const CheckInCard=({item,employeeMode,onRespond}:{item:import("@/features/contribution/contributionApi").CheckIn;employeeMode:boolean;onRespond:(text:string)=>void})=>{const [text,setText]=useState("");return <div className="min-w-0 p-4 sm:p-5"><div className="flex min-w-0 items-start gap-2"><CalendarRange size={15} className="mt-0.5 shrink-0 text-brand-600"/><p className="min-w-0 break-words text-sm font-semibold">{new Date(item.meetingDate).toLocaleDateString()} · {item.manager.name}</p></div>{item.supportNeeded&&<p className="mt-3 break-words text-sm text-slate-600">Support: {item.supportNeeded}</p>}{item.agreedActions.length>0&&<ul className="mt-2 list-disc break-words pl-5 text-sm text-slate-600">{item.agreedActions.map((a)=><li key={a.text}>{a.text}</li>)}</ul>}{item.employeeResponse?<p className="mt-3 break-words rounded-lg bg-emerald-50 p-3 text-xs text-emerald-800">Employee response: {item.employeeResponse}</p>:employeeMode&&<div className="mt-3 flex min-w-0 flex-col gap-2 sm:flex-row"><Input placeholder="Add your response or context" value={text} onChange={(e)=>setText(e.target.value)}/><Button className="w-full sm:w-auto" onClick={()=>onRespond(text)}>Acknowledge</Button></div>}</div>};
