import { useQuery } from "@tanstack/react-query";
import { AlertTriangle, ArrowUpRight, CalendarClock, ShieldCheck, Sparkles, Trophy } from "lucide-react";
import { api } from "@/api/client";
import { Skeleton } from "@/components/ui/Skeleton";
import { useAuth } from "@/features/auth/AuthProvider";
import { AskMobiusPanel, DailyTodoPanel, MoodBreakPanel } from "@/features/ai/AiWorkspacePanels";

interface Metric { label:string; value:number|string; detail:string }
interface Person { _id:string; firstName:string; lastName:string; employeeId:string }
interface Summary { greetingName:string; metrics:Metric[]; topPerformers:{employee:Person;score:number;classification:string}[]; upcomingDeadlines:{id:string;name:string;deadline:string;priority:string;employee:Person}[]; workloadAttention:{employee:Person;estimatedHours:number;openTasks:number;classification:string}[]; needsAttention:{employee:Person;score:number;developmentAreas:string[]}[] }

export const DashboardPage = () => {
  const { user }=useAuth(); const {data,isLoading}=useQuery({queryKey:["dashboard","summary"],queryFn:()=>api.get<Summary>("/api/v1/dashboard/summary")});
  const firstName=data?.greetingName??user?.name.split(" ")[0]; const employeeView=user?.role==="EMPLOYEE";
  const metrics=data?.metrics.map((metric,index)=>employeeView&&index===0?{label:"My employee profile",value:"Active",detail:"Your personal workforce scope"}:metric);
  return <main className="flex-1 overflow-x-clip px-4 py-6 sm:px-8 sm:py-9"><div className="mx-auto w-full min-w-0 max-w-[1440px]">
    <div className="flex min-w-0 flex-col justify-between gap-4 sm:flex-row sm:items-end sm:gap-5"><div className="min-w-0"><p className="text-sm font-medium text-brand-700">{employeeView?"Your overview":"Workforce overview"}</p><h1 className="mt-1 max-w-full break-words text-2xl font-semibold tracking-tight sm:text-4xl">Good morning, {firstName}</h1><p className="mt-2 max-w-2xl break-words text-sm leading-6 text-slate-500">{employeeView?"Your current work, capability, goals and growth in one place.":"Live capability, delivery and workforce signals within your permitted scope."}</p></div><div className="flex max-w-full self-start items-center gap-2 rounded-xl border bg-white px-3 py-2 text-xs text-slate-500 sm:self-auto"><span className="size-2 shrink-0 rounded-full bg-emerald-500"/>{employeeView?"Live personal view":"Live management view"}</div></div>
    <section aria-label="Key workforce metrics" className="mt-6 grid min-w-0 gap-4 sm:mt-8 sm:grid-cols-2 xl:grid-cols-4">{isLoading?Array.from({length:4},(_,i)=><Skeleton key={i} className="h-36"/>):metrics?.map((metric,index)=><article key={metric.label} className="min-w-0 overflow-hidden rounded-2xl border bg-white p-4 shadow-soft sm:p-5"><div className="flex min-w-0 items-start justify-between gap-3"><p className="min-w-0 break-words text-sm font-medium text-slate-500">{metric.label}</p><div className="grid size-8 shrink-0 place-items-center rounded-xl bg-slate-50 text-slate-500">{index===2?<ShieldCheck size={16}/>:<ArrowUpRight size={16}/>}</div></div><p className="mt-4 break-words text-3xl font-semibold tracking-tight">{metric.value}</p><p className="mt-2 break-words text-xs leading-5 text-slate-400">{metric.detail}</p></article>)}</section>
    <div className="mt-5 grid min-w-0 gap-5 xl:grid-cols-2"><section className="min-w-0 overflow-hidden rounded-2xl border bg-white shadow-soft"><div className="flex min-w-0 items-start border-b p-4 sm:items-center sm:p-5"><Trophy size={17} className="mt-0.5 shrink-0 text-amber-500 sm:mt-0"/><div className="ml-3 min-w-0"><h2 className="break-words font-semibold">{employeeView?"My performance evidence":"Top performance evidence"}</h2><p className="break-words text-xs text-slate-400">Latest explainable snapshot—not a permanent rank.</p></div></div><div className="divide-y">{data?.topPerformers.length?data.topPerformers.map((item,index)=><div className="flex min-w-0 items-center gap-3 p-4 sm:p-5" key={item.employee._id}><span className="grid size-8 shrink-0 place-items-center rounded-xl bg-slate-100 text-xs font-semibold">{index+1}</span><div className="min-w-0 flex-1"><p className="break-words text-sm font-semibold">{item.employee.firstName} {item.employee.lastName}</p><p className="break-words text-xs text-slate-400">{item.classification}</p></div><p className="shrink-0 text-xl font-semibold text-brand-700">{item.score}%</p></div>):<p className="p-8 text-center text-sm text-slate-400 sm:p-10">No performance snapshots yet.</p>}</div></section>
    <section className="min-w-0 overflow-hidden rounded-2xl border bg-white shadow-soft"><div className="flex min-w-0 items-start border-b p-4 sm:items-center sm:p-5"><CalendarClock size={17} className="mt-0.5 shrink-0 text-brand-600 sm:mt-0"/><div className="ml-3 min-w-0"><h2 className="font-semibold">Upcoming deadlines</h2><p className="break-words text-xs text-slate-400">The next work requiring attention.</p></div></div><div className="divide-y">{data?.upcomingDeadlines.length?data.upcomingDeadlines.map((item)=><div className="flex min-w-0 items-start gap-3 p-4 sm:items-center sm:p-5" key={item.id}><div className="min-w-0 flex-1"><p className="break-words text-sm font-semibold">{item.name}</p><p className="break-words text-xs text-slate-400">{item.employee.firstName} {item.employee.lastName}</p></div><div className="shrink-0 text-right"><p className="text-xs font-medium">{new Date(item.deadline).toLocaleDateString()}</p><p className="text-[10px] text-slate-400">{item.priority}</p></div></div>):<p className="p-8 text-center text-sm text-slate-400 sm:p-10">No upcoming task deadlines.</p>}</div></section></div>
    <div className="mt-5 grid min-w-0 gap-5 lg:grid-cols-2"><section className="min-w-0 overflow-hidden rounded-2xl border bg-white p-4 shadow-soft sm:p-5"><div className="flex items-center"><AlertTriangle size={17} className="shrink-0 text-amber-600"/><h2 className="ml-2 font-semibold">Workload attention</h2></div><div className="mt-4 space-y-2">{data?.workloadAttention.length?data.workloadAttention.map((item)=><div className="flex min-w-0 flex-col items-start gap-2 rounded-xl bg-amber-50/70 p-3 sm:flex-row sm:items-center" key={item.employee._id}><div className="min-w-0 flex-1"><p className="break-words text-sm font-semibold">{item.employee.firstName} {item.employee.lastName}</p><p className="break-words text-xs text-amber-700">{item.openTasks} tasks · {item.estimatedHours}h remaining</p></div><span className="max-w-full rounded-full bg-white px-2 py-1 text-[10px] font-semibold text-amber-700">{item.classification.replaceAll("_"," ")}</span></div>):<p className="py-8 text-center text-sm text-slate-400">No high-workload signals.</p>}</div></section><section className="min-w-0 overflow-hidden rounded-2xl bg-ink p-5 text-white shadow-soft sm:p-6"><div className="flex items-center gap-2 text-violet-200"><Sparkles size={18} className="shrink-0"/><span className="text-xs font-semibold uppercase tracking-wider">Decision principle</span></div><h2 className="mt-5 break-words text-xl font-semibold sm:text-2xl">Evidence informs. People decide.</h2><p className="mt-3 break-words text-sm leading-6 text-white/60">Scores remain deterministic and explainable. Recommendations never decide promotion, termination, salary or discipline.</p></section></div>
    <div className={`mt-5 grid min-w-0 gap-5 ${employeeView ? "xl:grid-cols-2" : ""}`}><AskMobiusPanel/>{employeeView && <DailyTodoPanel/>}</div>
    {employeeView && <div className="mt-5 max-w-2xl"><MoodBreakPanel/></div>}
  </div></main>;
};
