import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient, type UseMutationResult } from "@tanstack/react-query";
import { ArrowLeft, BadgeCheck, BriefcaseBusiness, CalendarDays, LockKeyhole, Sparkles, Target, UserRound } from "lucide-react";
import { useNavigate, useParams } from "react-router-dom";
import { employeeApi, type Employee360 } from "@/features/employees/employeeApi";
import { EmployeeLifecycleActions } from "@/features/employees/EmployeeLifecycleActions";
import { Skeleton } from "@/components/ui/Skeleton";
import { Button } from "@/components/ui/Button";
import { aiApi, type AiSummary } from "@/features/ai/aiApi";
import { useAuth } from "@/features/auth/AuthProvider";

const tabs = ["Overview", "AI summaries", "Skills", "Tasks", "Projects", "Goals", "KPIs", "Performance", "Learning", "Documents", "Activity"] as const;
type Tab = typeof tabs[number];
const levelStyle: Record<string, string> = { Basic: "bg-sky-50 text-sky-700", Intermediate: "bg-amber-50 text-amber-700", Advanced: "bg-violet-50 text-violet-700" };

const SkillsPanel = ({ data }: { data: Employee360 }) => {
  const assessment = data.roleSkillAssessment;
  const grouped = useMemo(() => assessment ? Object.entries(assessment.scores.reduce<Record<string, typeof assessment.scores>>((groups, item) => { (groups[item.level] ??= []).push(item); return groups; }, {})) : [], [assessment]);
  if (!assessment) return <section className="mt-5 rounded-2xl border bg-white p-12 text-center shadow-soft"><LockKeyhole className="mx-auto text-slate-300" size={28}/><h2 className="mt-3 font-semibold">Role skill assessment not submitted</h2><p className="mt-1 text-sm text-slate-400">This employee has not completed the one-time skill form yet.</p></section>;
  return <div className="mt-5 space-y-5">
    <section className="rounded-2xl border bg-white p-5 shadow-soft"><div className="flex flex-col gap-4 sm:flex-row sm:items-center"><div><p className="text-xs font-semibold uppercase tracking-wide text-brand-700">One-time role assessment</p><h2 className="mt-1 text-2xl font-semibold">{assessment.role}</h2><p className="mt-1 text-sm font-medium text-slate-600">Designation: {assessment.designation ?? data.employee.designation.name}</p><p className="mt-1 text-xs text-slate-400">Submitted {new Date(assessment.submittedAt).toLocaleString()} · {assessment.scores.length} skills · Locked</p></div><div className="rounded-2xl bg-brand-50 px-6 py-3 text-center sm:ml-auto"><p className="text-xs text-brand-600">Average score</p><p className="text-3xl font-semibold text-brand-700">{assessment.averageRating}<span className="text-base">/10</span></p></div></div></section>
    {grouped.map(([level, skills]) => <section className="rounded-2xl border bg-white shadow-soft" key={level}><div className="flex items-center border-b p-5"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${levelStyle[level] ?? "bg-slate-100 text-slate-700"}`}>{level}</span><span className="ml-auto text-xs text-slate-400">{skills.length} skills</span></div><div className="divide-y">{skills.map((skill) => <div className="p-5" key={skill.skillId}><div className="flex flex-col gap-3 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><p className="font-semibold">{skill.name}</p><p className="mt-1 text-xs leading-5 text-slate-500">{skill.description}</p><p className="mt-1 text-[11px] text-slate-400">{skill.category} · {skill.tools}</p></div><div className="shrink-0 rounded-xl bg-brand-50 px-4 py-2 text-center"><p className="text-xl font-semibold text-brand-700">{skill.rating}/10</p><p className="text-[10px] text-brand-600">Employee score</p></div></div>{skill.implementationNote && <div className="mt-4 rounded-xl border bg-slate-50 p-3"><p className="text-[10px] font-semibold uppercase tracking-wide text-slate-400">How the employee implemented this skill</p><p className="mt-1 whitespace-pre-wrap text-sm leading-6 text-slate-600">{skill.implementationNote}</p></div>}</div>)}</div></section>)}
  </div>;
};

const GenericPanel = ({ tab, items }: { tab: Exclude<Tab, "Overview" | "AI summaries" | "Skills">; items: unknown[] }) => <section className="mt-5 rounded-2xl border bg-white shadow-soft"><div className="flex items-center border-b p-5"><UserRound size={17} className="text-brand-600"/><h2 className="ml-2 font-semibold">{tab}</h2><span className="ml-auto text-xs text-slate-400">{items.length}</span></div><div className="divide-y">{items.length ? items.map((raw, index) => { const item = raw as Record<string, unknown>; const skill = item.skill as { name?: string } | undefined; const kpi = item.kpi as { name?: string } | undefined; const training = item.training as { name?: string } | undefined; const title = String(item.name ?? item.title ?? item.originalName ?? skill?.name ?? kpi?.name ?? training?.name ?? item.type ?? `${tab} item`); return <div className="p-5" key={String(item._id ?? index)}><p className="text-sm font-semibold">{title}</p><p className="mt-1 text-xs text-slate-400">{String(item.status ?? item.classification ?? item.verificationStatus ?? item.category ?? item.period ?? "Recorded")}</p>{item.progress !== undefined && <div className="mt-3 h-1.5 rounded-full bg-slate-100"><div className="h-full rounded-full bg-brand-500" style={{ width: `${Number(item.progress)}%` }}/></div>}</div>; }) : <div className="p-12 text-center text-sm text-slate-400">No {tab.toLowerCase()} records yet.</div>}</div></section>;

const SummaryCard = ({ title, description, mutation, existing }: { title: string; description: string; mutation: UseMutationResult<AiSummary, Error, void>; existing?: AiSummary }) => { const summary = mutation.data ?? existing; return <section className="min-w-0 rounded-2xl border bg-white p-5 shadow-soft"><div className="flex flex-col gap-3 sm:flex-row sm:items-start"><div className="grid size-10 shrink-0 place-items-center rounded-xl bg-brand-50 text-brand-700"><Sparkles size={18}/></div><div className="min-w-0 flex-1"><h2 className="font-semibold">{title}</h2><p className="mt-1 text-xs leading-5 text-slate-400">{description}</p></div><Button className="w-full shrink-0 sm:w-auto" disabled={mutation.isPending} onClick={() => mutation.mutate()}>{mutation.isPending ? "Generating…" : summary ? "Regenerate draft" : "Generate draft"}</Button></div>{summary && <div className="mt-5 rounded-xl border bg-slate-50 p-4"><p className="whitespace-pre-wrap text-sm leading-6 text-slate-700">{summary.summary}</p><div className="mt-4 border-t pt-3 text-[10px] text-slate-400">Advisory draft · {summary.provider} · {summary.model} · {new Date(summary.generatedAt).toLocaleString()}</div></div>}{mutation.error && <p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{mutation.error.message}</p>}</section>; };
const AiSummariesPanel = ({ employeeId }: { employeeId: string }) => {
  const qc = useQueryClient(); const existing = useQuery({ queryKey: ["ai-summaries", employeeId], queryFn: () => aiApi.employeeSummaries(employeeId) }); const refresh = () => qc.invalidateQueries({ queryKey: ["ai-summaries", employeeId] });
  const contribution = useMutation<AiSummary, Error, void>({ mutationFn: () => aiApi.contributionSummary(employeeId), onSuccess: refresh });
  const performance = useMutation<AiSummary, Error, void>({ mutationFn: () => aiApi.performanceSummary(employeeId), onSuccess: refresh });
  return <div className="mt-5 grid min-w-0 gap-5 xl:grid-cols-2"><SummaryCard title="AI contribution summary" description="Summarizes tasks, weekly updates, outcomes, support and evidence gaps. It does not invent work or make employment decisions." mutation={contribution} existing={existing.data?.items.find((item) => item.kind === "CONTRIBUTION")}/><SummaryCard title="AI performance review draft" description="Explains existing performance evidence and drafts strengths, development areas and next-period goals without changing scores." mutation={performance} existing={existing.data?.items.find((item) => item.kind === "PERFORMANCE")}/></div>;
};

export const EmployeeProfilePage = () => {
  const { id = "" } = useParams();
  const { user } = useAuth();
  const navigate = useNavigate();
  const [tab, setTab] = useState<Tab>("Overview");
  const management = user ? ["SUPER_ADMIN", "HR_ADMIN", "DEPARTMENT_HEAD", "MANAGER"].includes(user.role) : false;
  const visibleTabs = management ? tabs : tabs.filter((item) => item !== "AI summaries");
  const query = useQuery({ queryKey: ["employee", id, "360"], queryFn: () => employeeApi.profile(id), enabled: !!id });
  if (query.isLoading) return <main className="p-8"><Skeleton className="h-56"/></main>;
  if (!query.data) return <main className="grid min-h-96 place-items-center">Employee profile unavailable.</main>;
  const data = query.data;
  const employee = data.employee;
  const collections: Record<Exclude<Tab, "Overview" | "AI summaries" | "Skills">, unknown[]> = { Tasks: data.tasks, Projects: data.projects, Goals: data.goals, KPIs: data.kpis, Performance: data.performance, Learning: data.training, Documents: data.documents, Activity: data.timeline };
  return <main className="flex-1 px-5 py-8 sm:px-8"><div className="mx-auto max-w-[1440px]"><button className="flex items-center gap-2 text-sm text-slate-500 hover:text-ink" onClick={() => navigate("/employees")}><ArrowLeft size={16}/> Employees</button><section className="mt-5 rounded-3xl border bg-white p-6 shadow-soft sm:p-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-center"><div className="grid size-20 place-items-center overflow-hidden rounded-3xl bg-brand-50 text-2xl font-semibold text-brand-700">{employee.profilePhotoUrl ? <img src={employee.profilePhotoUrl} alt={`${employee.firstName} ${employee.lastName}`} className="size-full object-cover"/> : <>{employee.firstName[0]}{employee.lastName[0]}</>}</div><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-3xl font-semibold">{employee.firstName} {employee.lastName}</h1><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-[10px] font-semibold text-emerald-700">{employee.status}</span></div><p className="mt-1 text-sm text-slate-500">{employee.employeeId} · {employee.designation.name}</p><div className="mt-4 flex flex-wrap gap-x-6 gap-y-2 text-xs text-slate-500"><span>{employee.department.name}{employee.team && ` / ${employee.team.name}`}</span><span>{employee.employmentType.replaceAll("_", " ")}</span><span>Joined {new Date(employee.dateOfJoining).toLocaleDateString()}</span></div></div><div className="flex flex-wrap gap-2 sm:ml-auto">{management && <Button variant="secondary" onClick={() => setTab("AI summaries")}><Sparkles size={15}/> AI summaries</Button>}<EmployeeLifecycleActions employeeId={employee._id}/></div><div className="sm:text-right"><p className="text-xs text-slate-400">Profile completion</p><p className="text-2xl font-semibold text-brand-700">{employee.profileCompletion}%</p></div></div></section><div className="mt-5 flex gap-1 overflow-x-auto rounded-xl border bg-white p-1">{visibleTabs.map((item) => <button className={`h-10 whitespace-nowrap rounded-lg px-3 text-sm ${tab === item ? "bg-ink text-white" : "text-slate-500 hover:bg-slate-50"}`} key={item} onClick={() => setTab(item)}>{item}</button>)}</div>
    {tab === "Overview" ? <div className="mt-5 grid gap-5 lg:grid-cols-3"><section className="rounded-2xl border bg-white p-5 shadow-soft lg:col-span-2"><h2 className="font-semibold">Professional overview</h2><p className="mt-3 text-sm leading-6 text-slate-500">{employee.professionalSummary || "No professional summary has been added."}</p><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4">{[{ label: "Rated skills", value: data.roleSkillAssessment?.scores.length ?? data.skills.length, icon: BadgeCheck }, { label: "Open tasks", value: data.tasks.filter((x) => !["COMPLETED", "CANCELLED"].includes(x.status)).length, icon: BriefcaseBusiness }, { label: "Active goals", value: data.goals.filter((x) => x.status !== "COMPLETED").length, icon: Target }, { label: "Experience", value: employee.employmentType.replaceAll("_", " "), icon: CalendarDays }].map(({ label, value, icon: Icon }) => <div className="rounded-xl bg-slate-50 p-4" key={label}><Icon size={16} className="text-brand-600"/><p className="mt-3 text-lg font-semibold">{value}</p><p className="text-[11px] text-slate-400">{label}</p></div>)}</div></section><section className="rounded-2xl border bg-white p-5 shadow-soft"><h2 className="font-semibold">Recognition</h2><div className="mt-4 space-y-2">{data.recognition.length ? data.recognition.map((item) => <div className="rounded-xl bg-violet-50 p-3" key={item._id}><p className="text-xs font-semibold text-violet-700">{item.badge.replaceAll("_", " ")}</p><p className="mt-1 text-xs text-violet-600">{item.explanation}</p></div>) : <p className="py-8 text-center text-sm text-slate-400">No recognition yet.</p>}</div></section></div> : tab === "AI summaries" ? <AiSummariesPanel employeeId={employee._id}/> : tab === "Skills" ? <SkillsPanel data={data}/> : <GenericPanel tab={tab} items={collections[tab]}/>} </div></main>;
};
