import { useState } from "react";
import { Link } from "react-router-dom";
import { ArrowRight, Check, Layers3, Mic, Users, ChartNoAxesCombined, ShieldCheck, ChevronDown } from "lucide-react";
import logo from "@/assets/mobius-mark.png";
import { useAuth } from "@/features/auth/AuthProvider";
import "./landing.css";

const previews = {
  Overview: { title: "A clear view of the day.", stats: [["Team members", "24"], ["Tasks completed", "38"], ["Need attention", "3"]], rows: [["Website launch", "Design team", "In review"], ["Client onboarding", "Customer success", "On track"], ["Monthly reporting", "Operations", "Needs support"]] },
  Tasks: { title: "Every task has an owner.", stats: [["Open tasks", "12"], ["In review", "4"], ["Completed", "38"]], rows: [["Prepare launch assets", "Priya Sharma", "In review"], ["Follow up with client", "Ayush Rajak", "On track"], ["Review project brief", "Vandana Thapa", "Needs support"]] },
  People: { title: "Know your people. Help them grow.", stats: [["Team members", "24"], ["Departments", "5"], ["Learning plans", "8"]], rows: [["Priya Sharma", "Product design", "In review"], ["Ayush Rajak", "Engineering", "On track"], ["Vandana Thapa", "People operations", "Needs support"]] }
};
export const LandingPage = () => {
  const { user } = useAuth();
  const [tab, setTab] = useState<keyof typeof previews>("Overview");
  const preview = previews[tab];
  const destination = user ? "/" : "/register";
  return <div className="marketing">
    <a className="sr-only focus:not-sr-only" href="#main-content">Skip to content</a>
    <header className="marketing-nav"><Link to="/welcome" className="marketing-logo"><img src={logo} alt=""/>MobiusBloom<span>WORKFORCE</span></Link><nav aria-label="Main navigation"><a href="#platform">Platform</a><a href="#how-it-works">How it works</a><a href="#questions">Questions</a></nav><div className="marketing-nav-actions"><Link to={user ? "/" : "/login"}>{user ? "My workspace" : "Sign in"}</Link><Link className="marketing-button" to={destination}>Get started <ArrowRight size={16}/></Link></div></header>
    <main id="main-content">
      <section className="marketing-hero"><div className="marketing-hero-copy"><p className="marketing-eyebrow"><span/> PEOPLE. PURPOSE. PROGRESS.</p><h1>Great work starts<br/>with a team<br/><em>in sync.</em></h1><p className="marketing-lead">Bring your people, tasks, and growth into one clear workspace. Give every employee direction—and every manager the visibility to help.</p><div className="marketing-hero-actions"><Link className="marketing-button" to={destination}>Build a better workday <ArrowRight size={18}/></Link><a className="marketing-text-link" href="#platform">Explore the platform ↗</a></div><p className="marketing-small">One place for your workforce. More room for meaningful work.</p></div>
      <div className="marketing-preview"><div className="preview-top"><span className="preview-dot"/> Your company workspace <span className="preview-demo">Illustrative demo</span></div><div className="preview-body"><div className="preview-tabs" role="group" aria-label="Explore product preview">{(Object.keys(previews) as (keyof typeof previews)[]).map((name) => <button key={name} aria-pressed={tab === name} onClick={() => setTab(name)} className={tab === name ? "selected" : ""}>{name}</button>)}</div><p className="marketing-eyebrow">MONDAY, MADE MANAGEABLE</p><h2>{preview.title}</h2><div className="preview-stats">{preview.stats.map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><div className="preview-chart"><div><strong>Progress you can see</strong><span>Sample weekly activity</span></div><div className="preview-bars" aria-label="Illustrative weekly activity chart">{[35, 55, 44, 78, 64, 88, 72].map((height, index) => <div key={index}><i style={{ height: `${height}px` }}/><span>{["M", "T", "W", "T", "F", "S", "S"][index]}</span></div>)}</div></div><div className="preview-rows" aria-live="polite">{preview.rows.map(([name, person, state]) => <div key={name}><span className="preview-avatar">{name[0]}</span><div><strong>{name}</strong><small>{person}</small></div><span className={`preview-status ${state === "Needs support" ? "attention" : ""}`}>{state}</span></div>)}</div></div><div className="preview-bottom"><ShieldCheck size={15}/> Clear responsibilities. Shared progress. Human decisions.</div></div>
      </section>
      <section className="marketing-strip" aria-label="Platform capabilities">{["Employee management", "Tasks & projects", "Attendance & leave", "Skills & growth", "Workforce analytics"].map((name) => <span key={name}><Check size={15}/>{name}</span>)}</section>
      <section className="marketing-section" id="platform"><div className="marketing-section-heading"><p className="marketing-eyebrow">LESS CHASING. MORE CLARITY.</p><h2>Everything your team needs.<br/><em>Finally, connected.</em></h2><p>Scattered spreadsheets and status messages make simple work harder. Give your company a shared picture of who is doing what, where work is stuck, and what comes next.</p></div><div className="marketing-features">{[
        { Icon: Users, tag: "PEOPLE", title: "See the person behind the role.", text: "Keep employee profiles, departments, onboarding, attendance, and leave organized in one workspace.", benefit: "Less searching for employee information." },
        { Icon: Layers3, tag: "DELIVERY", title: "Turn plans into clear ownership.", text: "Assign tasks, track deadlines, review outcomes, and reassign work when priorities change.", benefit: "Fewer missed handoffs and unclear responsibilities." },
        { Icon: ChartNoAxesCombined, tag: "VISIBILITY", title: "Spot the work that needs support.", text: "Understand overdue tasks, review queues, and estimated workload with straightforward analytics.", benefit: "Better conversations, backed by actual work." }
      ].map(({ Icon, tag, title, text, benefit }) => <article key={tag}><Icon size={26}/><p className="marketing-eyebrow">{tag}</p><h3>{title}</h3><p>{text}</p><div><Check size={16}/>{benefit}</div></article>)}</div></section>
      <section className="marketing-voice"><div><p className="marketing-eyebrow">FROM A CONVERSATION TO A PLAN</p><h2>Say the work.<br/><em>Make it actionable.</em></h2><p>Capture a voice command, review the suggested assignments, and confirm. Employees receive their tasks in the app, with ownership and deadlines in view.</p><Link to={user ? "/work" : "/login"} className="marketing-text-link">Explore voice tasks <ArrowRight size={18}/></Link></div><div className="voice-example"><span className="voice-icon"><Mic size={28}/></span><p>“Vandana ko report banana hai, aur Ayush ko client follow-up karna hai.”</p><span className="marketing-small">Example command · Review before confirming</span><div><span><Check size={16}/> Report preparation <small>Vandana</small></span><span><Check size={16}/> Client follow-up <small>Ayush</small></span></div></div></section>
      <section className="marketing-section" id="how-it-works"><div className="marketing-section-heading"><p className="marketing-eyebrow">A BETTER WAY TO WORK, TOGETHER</p><h2>From scattered updates<br/>to shared understanding.</h2></div><div className="marketing-steps">{[["01", "Bring your team together", "Set up your organization, add employees, and organize departments and responsibilities."], ["02", "Give work a clear direction", "Create projects, assign tasks, set deadlines, and capture progress in one place."], ["03", "Help your people move forward", "Review outcomes, identify blockers, and use skills and learning records to support growth."]].map(([number, title, text]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
      <section className="marketing-principle"><ShieldCheck size={30}/><h2>Built around people.<br/>Guided by evidence.</h2><p>Role-based access keeps work within the right scope. Recorded activity brings context to changes. AI assistance supports the conversation, while your people make the decisions.</p></section>
      <section className="marketing-section marketing-faq" id="questions"><div><p className="marketing-eyebrow">GOOD QUESTIONS</p><h2>A little more clarity.</h2></div><div>{[["Who is MobiusBloom for?", "Companies that want to organize their employees, daily work, and development in a shared workspace. Administrators get an organization overview, while employees access their own work and records."], ["What can my employees do?", "Employees can manage their profiles, track assigned work, submit completion evidence, record attendance, request leave, and build their skills."], ["Does AI make decisions about employees?", "No. AI provides assistance and drafts. Managers review the evidence and remain responsible for employment decisions."], ["Are the numbers on this page real company data?", "No. The interactive preview uses illustrative sample data. Your signed-in dashboard shows your organization's actual records."]].map(([question, answer]) => <details key={question}><summary>{question}<ChevronDown size={18}/></summary><p>{answer}</p></details>)}</div></section>
      <section className="marketing-cta"><p className="marketing-eyebrow">MAKE SPACE FOR BETTER WORK</p><h2>Your people have potential.<br/><em>Give it a place to grow.</em></h2><Link to={destination} className="marketing-button">Create your workspace <ArrowRight size={18}/></Link><Link to={user ? "/" : "/login"} className="marketing-text-link">{user ? "Return to dashboard" : "Already part of a team? Sign in"}</Link></section>
    </main><footer className="marketing-footer"><Link to="/welcome" className="marketing-logo"><img src={logo} alt=""/>MobiusBloom</Link><p>People connected. Work moving forward.</p><Link to={user ? "/" : "/login"}>Go to workspace ↗</Link></footer>
  </div>;
};
