import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Camera, Save } from "lucide-react";
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";
import { Skeleton } from "@/components/ui/Skeleton";
import { employeeApi } from "@/features/employees/employeeApi";

export const MyProfilePage = () => {
  const queryClient = useQueryClient();
  const query = useQuery({ queryKey: ["employee", "me"], queryFn: employeeApi.me });
  const [form, setForm] = useState({ firstName: "", lastName: "", phone: "", personalEmail: "", address: "", emergencyContact: "", professionalSummary: "" });
  useEffect(() => { const employee = query.data?.employee; if (employee) setForm({ firstName: employee.firstName, lastName: employee.lastName, phone: employee.phone ?? "", personalEmail: employee.personal?.personalEmail ?? "", address: employee.personal?.address ?? "", emergencyContact: employee.personal?.emergencyContact ?? "", professionalSummary: employee.professionalSummary ?? "" }); }, [query.data?.employee]);
  const save = useMutation({ mutationFn: () => employeeApi.updateMe({ firstName: form.firstName, lastName: form.lastName, phone: form.phone || undefined, professionalSummary: form.professionalSummary || undefined, personal: { personalEmail: form.personalEmail || undefined, address: form.address || undefined, emergencyContact: form.emergencyContact || undefined } }), onSuccess: () => queryClient.invalidateQueries({ queryKey: ["employee"] }) });
  const photo = useMutation({ mutationFn: employeeApi.uploadProfilePhoto, onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ["employee"] }); } });
  if (query.isLoading) return <main className="p-8"><Skeleton className="h-96"/></main>;
  const employee = query.data?.employee; if (!employee) return <main className="grid min-h-96 place-items-center text-sm text-slate-500">Your employee profile is unavailable.</main>;
  const message = save.error?.message ?? photo.error?.message;
  return <main className="p-4 sm:p-8"><div className="mx-auto max-w-4xl"><div><p className="text-sm font-medium text-brand-700">Employee profile</p><h1 className="mt-1 text-3xl font-semibold">Edit my profile</h1><p className="mt-2 text-sm text-slate-500">Keep your personal and professional details current.</p></div><section className="mt-7 rounded-3xl border bg-white p-6 shadow-soft sm:p-8"><div className="flex flex-col gap-5 border-b pb-7 sm:flex-row sm:items-center"><div className="grid size-24 shrink-0 place-items-center overflow-hidden rounded-3xl bg-brand-50 text-2xl font-semibold text-brand-700">{employee.profilePhotoUrl ? <img src={employee.profilePhotoUrl} alt={`${employee.firstName} ${employee.lastName}`} className="size-full object-cover"/> : `${employee.firstName[0] ?? ""}${employee.lastName[0] ?? ""}`}</div><div><h2 className="text-xl font-semibold">Profile picture</h2><p className="mt-1 text-sm text-slate-500">Upload a JPG, PNG or WebP image up to 5 MB.</p><label className="mt-3 inline-flex cursor-pointer items-center gap-2 rounded-xl border px-4 py-2 text-sm font-medium hover:bg-slate-50"><Camera size={16}/>{photo.isPending ? "Uploading..." : "Upload picture"}<input type="file" accept="image/jpeg,image/png,image/webp" className="hidden" disabled={photo.isPending} onChange={(event) => { const file = event.target.files?.[0]; if (file) photo.mutate(file); }}/></label></div></div><div className="mt-7 grid gap-5 sm:grid-cols-2"><Field label="First name" required value={form.firstName} onChange={(value) => setForm({ ...form, firstName: value })}/><Field label="Last name" required value={form.lastName} onChange={(value) => setForm({ ...form, lastName: value })}/><Field label="Phone" value={form.phone} onChange={(value) => setForm({ ...form, phone: value })}/><Field label="Personal email" type="email" value={form.personalEmail} onChange={(value) => setForm({ ...form, personalEmail: value })}/><Field label="Emergency contact" value={form.emergencyContact} onChange={(value) => setForm({ ...form, emergencyContact: value })}/><Field label="Address" value={form.address} onChange={(value) => setForm({ ...form, address: value })}/><label className="text-sm font-medium sm:col-span-2">Professional summary<textarea className="mt-2 min-h-36 w-full rounded-xl border p-3 text-sm" maxLength={2000} value={form.professionalSummary} onChange={(event) => setForm({ ...form, professionalSummary: event.target.value })}/></label></div>{message && <p role="alert" className="mt-5 rounded-xl bg-red-50 p-3 text-sm text-red-700">{message}</p>}{save.isSuccess && <p className="mt-5 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">Your profile has been updated.</p>}<div className="mt-7 flex justify-end"><Button onClick={() => save.mutate()} disabled={save.isPending || !form.firstName.trim() || !form.lastName.trim()}><Save size={16}/>{save.isPending ? "Saving..." : "Save profile"}</Button></div></section></div></main>;
};
const Field = ({ label, value, onChange, type = "text", required = false }: { label: string; value: string; onChange: (value: string) => void; type?: string; required?: boolean }) => <label className="text-sm font-medium">{label}{required && <span className="text-red-500"> *</span>}<Input className="mt-2" type={type} required={required} value={value} onChange={(event) => onChange(event.target.value)}/></label>;
