import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, ArrowRight, Check, FileCheck2, FileText, GraduationCap, Sparkles, UserRound } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";
import { useAuth } from "@/features/auth/AuthProvider";
import { employeeApi } from "@/features/employees/employeeApi";
import { governanceApi } from "@/features/governance/governanceApi";
import { skillApi } from "@/features/skills/skillApi";

const steps = [{ label: "Personal information", icon: UserRound }, { label: "Professional information", icon: GraduationCap }, { label: "Previous experience", icon: GraduationCap }, { label: "Skills", icon: Sparkles }, { label: "Certifications", icon: FileCheck2 }, { label: "Documents", icon: FileText }, { label: "Review and complete", icon: Check }];
const documentCategories = ["RESUME","ID_DOCUMENT","NDA","EXPERIENCE_LETTER","OTHER"];

export const OnboardingPage = () => {
  const navigate = useNavigate(); const queryClient = useQueryClient(); const { user, setUser } = useAuth(); const [index, setIndex] = useState(0);
  const [data, setData] = useState({ personalEmail: "", address: "", emergencyContact: "", professionalSummary: "", company: "", experienceRole: "", startDate: "" });
  const [skill, setSkill] = useState({ skill: "", selfRating: 5, yearsOfExperience: 0, evidenceUrl: "" });
  const [certificate, setCertificate] = useState<File | null>(null); const [documentFile, setDocumentFile] = useState<File | null>(null); const [documentCategory, setDocumentCategory] = useState("RESUME");
  const employee = useQuery({ queryKey: ["employee", "me"], queryFn: employeeApi.me });
  const skills = useQuery({ queryKey: ["skills"], queryFn: skillApi.list, enabled: index === 3 });
  const mine = useQuery({ queryKey: ["skills", "mine"], queryFn: skillApi.mine, enabled: index >= 3 });
  const documents = useQuery({ queryKey: ["documents"], queryFn: governanceApi.documents, enabled: index >= 4 });
  const upload = async (file: File, category: string) => { const employeeId = employee.data?.employee._id; if (!employeeId) throw new Error("Employee profile is still loading"); const form = new FormData(); form.append("file", file); form.append("employee", employeeId); form.append("category", category); await governanceApi.upload(form); };
  const save = useMutation({ mutationFn: async () => {
    const step = index + 2;
    if (index === 0) await employeeApi.onboarding({ step, personal: { personalEmail: data.personalEmail || undefined, address: data.address || undefined, emergencyContact: data.emergencyContact || undefined } });
    if (index === 1) await employeeApi.onboarding({ step, professionalSummary: data.professionalSummary });
    if (index === 2) await employeeApi.onboarding({ step, ...(data.company && data.experienceRole && data.startDate ? { previousExperience: [{ company: data.company, role: data.experienceRole, startDate: data.startDate }] } : {}) });
    if (index === 3) { if (skill.skill) await skillApi.claim({ skill: skill.skill, selfRating: Number(skill.selfRating), yearsOfExperience: Number(skill.yearsOfExperience), evidence: skill.evidenceUrl ? [{ type: "PROJECT", url: skill.evidenceUrl }] : [] }); await employeeApi.onboarding({ step }); }
    if (index === 4) { if (certificate) await upload(certificate, "CERTIFICATE"); await employeeApi.onboarding({ step }); }
    if (index === 5) { if (documentFile) await upload(documentFile, documentCategory); await employeeApi.onboarding({ step }); }
    if (index === 6) await employeeApi.onboarding({ step: 8, complete: true });
  }, onSuccess: async () => { await Promise.all([queryClient.invalidateQueries({ queryKey: ["employee", "me"] }), queryClient.invalidateQueries({ queryKey: ["skills", "mine"] }), queryClient.invalidateQueries({ queryKey: ["documents"] })]); if (index === steps.length - 1 && user) { setUser({ ...user, onboardingComplete: true }); navigate("/", { replace: true }); } else setIndex((value) => Math.min(steps.length - 1, value + 1)); } });
  const current = steps[index]!; const Icon = current.icon; const completion = employee.data?.employee.profileCompletion ?? 35;
  return <main className="min-h-screen bg-[#faf8ff] px-4 py-6 sm:p-8"><div className="mx-auto max-w-5xl"><header className="flex items-center justify-between"><div><p className="text-sm font-semibold">MobiusBloom Employee</p><p className="text-xs text-slate-400">Profile onboarding</p></div><div className="text-right"><p className="text-xs text-slate-500">Profile completion</p><p className="font-semibold text-brand-700">{completion}%</p></div></header><div className="mt-5 h-1.5 rounded-full bg-brand-100"><div className="h-full rounded-full bg-brand-500 transition-all" style={{ width: `${completion}%` }}/></div><div className="mt-8 grid gap-6 lg:grid-cols-[250px_1fr]"><aside className="hidden rounded-2xl border bg-white p-3 lg:block">{steps.map((step, stepIndex) => <div key={step.label} className={`flex items-center rounded-xl p-3 text-sm ${stepIndex === index ? "bg-brand-50 font-medium text-brand-700" : "text-slate-400"}`}><span className="grid size-7 place-items-center rounded-lg bg-white">{stepIndex < index ? <Check size={14}/> : stepIndex + 2}</span><span className="ml-3">{step.label}</span></div>)}</aside><section className="min-h-[500px] rounded-3xl border bg-white p-6 shadow-soft sm:p-9"><div className="grid size-11 place-items-center rounded-2xl bg-brand-50 text-brand-700"><Icon size={20}/></div><p className="mt-5 text-xs font-semibold uppercase tracking-wider text-brand-700">Step {index + 2} of 8</p><h1 className="mt-1 text-2xl font-semibold">{current.label}</h1><p className="mt-2 text-sm text-slate-500">Save progress now and complete unfinished sections later from your workspace.</p><div className="mt-8">
    {index === 0 && <div className="space-y-4"><label className="block text-sm font-medium">Personal email<Input type="email" className="mt-2" value={data.personalEmail} onChange={(event) => setData({ ...data, personalEmail: event.target.value })}/></label><label className="block text-sm font-medium">Address<Input className="mt-2" value={data.address} onChange={(event) => setData({ ...data, address: event.target.value })}/></label><label className="block text-sm font-medium">Emergency contact<Input className="mt-2" value={data.emergencyContact} onChange={(event) => setData({ ...data, emergencyContact: event.target.value })}/></label></div>}
    {index === 1 && <label className="text-sm font-medium">Professional summary<textarea className="mt-2 min-h-40 w-full rounded-xl border p-3 text-sm" value={data.professionalSummary} onChange={(event) => setData({ ...data, professionalSummary: event.target.value })}/></label>}
    {index === 2 && <div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Previous company<Input className="mt-2" value={data.company} onChange={(event) => setData({ ...data, company: event.target.value })}/></label><label className="text-sm font-medium">Role<Input className="mt-2" value={data.experienceRole} onChange={(event) => setData({ ...data, experienceRole: event.target.value })}/></label><label className="text-sm font-medium">Start date<Input type="date" className="mt-2" value={data.startDate} onChange={(event) => setData({ ...data, startDate: event.target.value })}/></label></div>}
    {index === 3 && <div><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium sm:col-span-2">Skill<select className="mt-2 h-11 w-full rounded-xl border px-3" value={skill.skill} onChange={(event) => setSkill({ ...skill, skill: event.target.value })}><option value="">Skip for now</option>{skills.data?.items.map((item) => <option key={item._id} value={item._id}>{item.name} · {item.category}</option>)}</select></label><label className="text-sm font-medium">Self rating<Input type="number" min="1" max="10" className="mt-2" value={skill.selfRating} onChange={(event) => setSkill({ ...skill, selfRating: Number(event.target.value) })}/></label><label className="text-sm font-medium">Years of experience<Input type="number" min="0" max="60" step=".5" className="mt-2" value={skill.yearsOfExperience} onChange={(event) => setSkill({ ...skill, yearsOfExperience: Number(event.target.value) })}/></label><label className="text-sm font-medium sm:col-span-2">Evidence link<Input type="url" className="mt-2" placeholder="GitHub, portfolio or project URL" value={skill.evidenceUrl} onChange={(event) => setSkill({ ...skill, evidenceUrl: event.target.value })}/></label></div><p className="mt-4 text-xs text-slate-400">{mine.data?.items.length ?? 0} skill claim(s) currently saved.</p></div>}
    {index === 4 && <UploadField label="Certificate file" file={certificate} onChange={setCertificate} help="PDF, DOCX, JPG, PNG or WebP; maximum 10 MB. You may skip if you have no certificate."/>}
    {index === 5 && <div className="space-y-4"><label className="block text-sm font-medium">Document category<select className="mt-2 h-11 w-full rounded-xl border px-3" value={documentCategory} onChange={(event) => setDocumentCategory(event.target.value)}>{documentCategories.map((category) => <option key={category}>{category.replaceAll("_", " ")}</option>)}</select></label><UploadField label="Private document" file={documentFile} onChange={setDocumentFile} help="Your file is stored privately and is available only after authorization."/></div>}
    {index === 6 && <div className="rounded-2xl bg-brand-50 p-6"><h2 className="font-semibold">Review your saved profile</h2><div className="mt-4 grid gap-3 sm:grid-cols-3"><Summary label="Profile completion" value={`${completion}%`}/><Summary label="Skills" value={String(mine.data?.items.length ?? 0)}/><Summary label="Documents" value={String(documents.data?.items.length ?? 0)}/></div><p className="mt-4 text-sm text-slate-600">You can enter the workspace now and complete optional missing sections later.</p></div>}
  </div>{save.error && <p role="alert" className="mt-5 rounded-xl bg-red-50 p-3 text-sm text-red-700">{save.error.message}{save.error.message.includes("storage") && " Ask your administrator to configure Cloudinary in server/.env."}</p>}<div className="mt-10 flex justify-between border-t pt-5"><Button variant="ghost" disabled={index === 0 || save.isPending} onClick={() => setIndex((value) => value - 1)}><ArrowLeft size={16}/> Back</Button><Button disabled={save.isPending || employee.isLoading} onClick={() => save.mutate()}>{save.isPending ? "Saving…" : index === steps.length - 1 ? "Complete onboarding" : <>Save and continue <ArrowRight size={16}/></>}</Button></div></section></div></div></main>;
};

const UploadField = ({ label, file, onChange, help }: { label: string; file: File | null; onChange: (file: File | null) => void; help: string }) => <label className="block rounded-2xl border border-dashed bg-slate-50 p-6 text-sm font-medium">{label}<input type="file" accept=".pdf,.docx,.jpg,.jpeg,.png,.webp" className="mt-3 block w-full rounded-xl border bg-white p-2 text-sm" onChange={(event) => onChange(event.target.files?.[0] ?? null)}/><span className="mt-2 block text-xs font-normal text-slate-400">{file ? `Selected: ${file.name}` : help}</span></label>;
const Summary = ({ label, value }: { label: string; value: string }) => <div className="rounded-xl bg-white p-4"><p className="text-xs text-slate-400">{label}</p><p className="mt-1 text-xl font-semibold text-brand-700">{value}</p></div>;
