import { useEffect, useRef, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, ArrowRight, Check, FileCheck2, FileText, GraduationCap, Sparkles, UserRound } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";
import { useAuth } from "@/features/auth/AuthProvider";
import { employeeApi } from "@/features/employees/employeeApi";
import { governanceApi } from "@/features/governance/governanceApi";
import { skillApi } from "@/features/skills/skillApi";

const steps = [{ label: "Personal information", icon: UserRound }, { label: "Professional information", icon: GraduationCap }, { label: "Previous experience", icon: GraduationCap }, { label: "Skills", icon: Sparkles }, { label: "Certifications", icon: FileCheck2 }, { label: "Documents", icon: FileText }, { label: "Review and complete", icon: Check }];

export const OnboardingPage = () => {
  const navigate = useNavigate(); const queryClient = useQueryClient(); const { user, setUser } = useAuth(); const [index, setIndex] = useState(0); const hydrated = useRef(false);
  const [data, setData] = useState({ personalEmail: "", address: "", emergencyContact: "", professionalSummary: "", company: "", experienceRole: "", startDate: "" });
  const [skill, setSkill] = useState({ skill: "", selfRating: 5, yearsOfExperience: 0, evidenceUrl: "" });
  const [certificate, setCertificate] = useState<File | null>(null); const [resume, setResume] = useState<File | null>(null); const [identityDocument, setIdentityDocument] = useState<File | null>(null);
  const employee = useQuery({ queryKey: ["employee", "me"], queryFn: employeeApi.me });
  const skills = useQuery({ queryKey: ["skills"], queryFn: skillApi.list, enabled: index === 3 });
  const mine = useQuery({ queryKey: ["skills", "mine"], queryFn: skillApi.mine, enabled: index >= 3 });
  const documents = useQuery({ queryKey: ["documents"], queryFn: governanceApi.documents, enabled: index >= 4 });
  useEffect(() => { const current = employee.data?.employee; if (!current || hydrated.current) return; hydrated.current = true; const experience = current.previousExperience?.[0]; setData({ personalEmail: current.personal?.personalEmail ?? "", address: current.personal?.address ?? "", emergencyContact: current.personal?.emergencyContact ?? "", professionalSummary: current.professionalSummary ?? "", company: experience?.company ?? "", experienceRole: experience?.role ?? "", startDate: experience?.startDate?.slice(0, 10) ?? "" }); }, [employee.data?.employee]);
  const hasDocument = (category: string) => Boolean(documents.data?.items.some((item) => item.category === category));
  const upload = async (file: File, category: string) => { const employeeId = employee.data?.employee._id; if (!employeeId) throw new Error("Employee profile is still loading"); const form = new FormData(); form.append("file", file); form.append("employee", employeeId); form.append("category", category); await governanceApi.upload(form); };
  const save = useMutation({ mutationFn: async () => {
    const step = index + 2;
    if (index === 0) { if (!data.personalEmail.trim() || !data.address.trim() || !data.emergencyContact.trim()) throw new Error("Fill in personal email, address and emergency contact."); await employeeApi.onboarding({ step, personal: { personalEmail: data.personalEmail, address: data.address, emergencyContact: data.emergencyContact } }); }
    if (index === 1) { if (data.professionalSummary.trim().length < 20) throw new Error("Write a professional summary of at least 20 characters."); await employeeApi.onboarding({ step, professionalSummary: data.professionalSummary }); }
    if (index === 2) { if (!data.company.trim() || !data.experienceRole.trim() || !data.startDate) throw new Error("Fill in your previous company, role and start date."); await employeeApi.onboarding({ step, previousExperience: [{ company: data.company, role: data.experienceRole, startDate: data.startDate }] }); }
    if (index === 3) { if (!skill.skill && !mine.data?.items.length) throw new Error("Select and save at least one skill."); if (skill.skill) await skillApi.claim({ skill: skill.skill, selfRating: Number(skill.selfRating), yearsOfExperience: Number(skill.yearsOfExperience), evidence: skill.evidenceUrl ? [{ type: "PROJECT", url: skill.evidenceUrl }] : [] }); await employeeApi.onboarding({ step }); }
    if (index === 4) { if (!certificate && !hasDocument("CERTIFICATE")) throw new Error("Upload a certificate to continue."); if (certificate) await upload(certificate, "CERTIFICATE"); await queryClient.invalidateQueries({ queryKey: ["documents"] }); await employeeApi.onboarding({ step }); }
    if (index === 5) { if (!resume && !hasDocument("RESUME")) throw new Error("Upload your résumé to continue."); if (!identityDocument && !hasDocument("ID_DOCUMENT")) throw new Error("Upload your identity document to continue."); if (resume) await upload(resume, "RESUME"); if (identityDocument) await upload(identityDocument, "ID_DOCUMENT"); await queryClient.invalidateQueries({ queryKey: ["documents"] }); await employeeApi.onboarding({ step }); }
    if (index === 6) await employeeApi.onboarding({ step: 8, complete: true });
  }, onSuccess: async () => { await Promise.all([queryClient.invalidateQueries({ queryKey: ["employee", "me"] }), queryClient.invalidateQueries({ queryKey: ["skills", "mine"] }), queryClient.invalidateQueries({ queryKey: ["documents"] })]); if (index === steps.length - 1 && user) { setUser({ ...user, onboardingComplete: true }); navigate("/", { replace: true }); } else setIndex((value) => Math.min(steps.length - 1, value + 1)); } });
  const current = steps[index]!; const Icon = current.icon; const completion = employee.data?.employee.profileCompletion ?? 35;
  return <main className="min-h-screen bg-[#faf8ff] px-4 py-6 sm:p-8"><div className="mx-auto max-w-5xl"><header className="flex items-center justify-between"><div><p className="text-sm font-semibold">MobiusBloom Employee</p><p className="text-xs text-slate-400">Required profile onboarding</p></div><div className="text-right"><p className="text-xs text-slate-500">Profile completion</p><p className="font-semibold text-brand-700">{completion}%</p></div></header><div className="mt-5 h-1.5 rounded-full bg-brand-100"><div className="h-full rounded-full bg-brand-500 transition-all" style={{ width: `${completion}%` }}/></div><div className="mt-8 grid gap-6 lg:grid-cols-[250px_1fr]"><aside className="hidden rounded-2xl border bg-white p-3 lg:block">{steps.map((step, stepIndex) => <div key={step.label} className={`flex items-center rounded-xl p-3 text-sm ${stepIndex === index ? "bg-brand-50 font-medium text-brand-700" : "text-slate-400"}`}><span className="grid size-7 place-items-center rounded-lg bg-white">{stepIndex < index ? <Check size={14}/> : stepIndex + 2}</span><span className="ml-3">{step.label}</span></div>)}</aside><section className="min-h-[500px] rounded-3xl border bg-white p-6 shadow-soft sm:p-9"><div className="grid size-11 place-items-center rounded-2xl bg-brand-50 text-brand-700"><Icon size={20}/></div><p className="mt-5 text-xs font-semibold uppercase tracking-wider text-brand-700">Step {index + 2} of 8</p><h1 className="mt-1 text-2xl font-semibold">{current.label}</h1><p className="mt-2 text-sm text-slate-500">Every section is required. Complete this step to continue.</p><div className="mt-8">
    {index === 0 && <div className="space-y-4"><Field label="Personal email *" type="email" value={data.personalEmail} onChange={(value) => setData({ ...data, personalEmail: value })}/><Field label="Address *" value={data.address} onChange={(value) => setData({ ...data, address: value })}/><Field label="Emergency contact *" value={data.emergencyContact} onChange={(value) => setData({ ...data, emergencyContact: value })}/></div>}
    {index === 1 && <label className="text-sm font-medium">Professional summary *<textarea className="mt-2 min-h-40 w-full rounded-xl border p-3 text-sm" minLength={20} value={data.professionalSummary} onChange={(event) => setData({ ...data, professionalSummary: event.target.value })}/><span className="mt-1 block text-xs font-normal text-slate-400">Minimum 20 characters.</span></label>}
    {index === 2 && <div className="grid gap-4 sm:grid-cols-2"><Field label="Previous company *" value={data.company} onChange={(value) => setData({ ...data, company: value })}/><Field label="Role *" value={data.experienceRole} onChange={(value) => setData({ ...data, experienceRole: value })}/><Field label="Start date *" type="date" value={data.startDate} onChange={(value) => setData({ ...data, startDate: value })}/></div>}
    {index === 3 && <div><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium sm:col-span-2">Skill *<select className="mt-2 h-11 w-full rounded-xl border px-3" value={skill.skill} onChange={(event) => setSkill({ ...skill, skill: event.target.value })}><option value="">Select a skill</option>{skills.data?.items.map((item) => <option key={item._id} value={item._id}>{item.name} · {item.category}</option>)}</select></label><Field label="Self rating (1–10) *" type="number" value={String(skill.selfRating)} onChange={(value) => setSkill({ ...skill, selfRating: Number(value) })}/><Field label="Years of experience *" type="number" value={String(skill.yearsOfExperience)} onChange={(value) => setSkill({ ...skill, yearsOfExperience: Number(value) })}/><label className="text-sm font-medium sm:col-span-2">Evidence link<Input type="url" className="mt-2" placeholder="GitHub, portfolio or project URL" value={skill.evidenceUrl} onChange={(event) => setSkill({ ...skill, evidenceUrl: event.target.value })}/></label></div><p className="mt-4 text-xs text-slate-400">{mine.data?.items.length ?? 0} skill claim(s) currently saved.</p></div>}
    {index === 4 && <UploadField label="Certificate file *" file={certificate} onChange={setCertificate} help={hasDocument("CERTIFICATE") ? "Certificate already uploaded." : "Required: PDF, DOCX, JPG, PNG or WebP; maximum 10 MB."}/>}
    {index === 5 && <div className="space-y-4"><UploadField label="Résumé *" file={resume} onChange={setResume} help={hasDocument("RESUME") ? "Résumé already uploaded." : "Required private document."}/><UploadField label="Identity document *" file={identityDocument} onChange={setIdentityDocument} help={hasDocument("ID_DOCUMENT") ? "Identity document already uploaded." : "Required private document."}/></div>}
    {index === 6 && <div className="rounded-2xl bg-brand-50 p-6"><h2 className="font-semibold">Review your completed profile</h2><div className="mt-4 grid gap-3 sm:grid-cols-3"><Summary label="Profile completion" value={`${completion}%`}/><Summary label="Skills" value={String(mine.data?.items.length ?? 0)}/><Summary label="Documents" value={String(documents.data?.items.length ?? 0)}/></div><p className="mt-4 text-sm text-slate-600">Completing onboarding unlocks your employee workspace. Required information cannot be skipped.</p></div>}
  </div>{save.error && <p role="alert" className="mt-5 rounded-xl bg-red-50 p-3 text-sm text-red-700">{save.error.message}</p>}<div className="mt-10 flex justify-between border-t pt-5"><Button variant="ghost" disabled={index === 0 || save.isPending} onClick={() => setIndex((value) => value - 1)}><ArrowLeft size={16}/> Back</Button><Button disabled={save.isPending || employee.isLoading} onClick={() => save.mutate()}>{save.isPending ? "Saving…" : index === steps.length - 1 ? "Complete onboarding" : <>Save and continue <ArrowRight size={16}/></>}</Button></div></section></div></div></main>;
};
const Field = ({ label, value, onChange, type = "text" }: { label: string; value: string; onChange: (value: string) => void; type?: string }) => <label className="block text-sm font-medium">{label}<Input type={type} className="mt-2" value={value} onChange={(event) => onChange(event.target.value)}/></label>;
const UploadField = ({ label, file, onChange, help }: { label: string; file: File | null; onChange: (file: File | null) => void; help: string }) => <label className="block rounded-2xl border border-dashed bg-slate-50 p-6 text-sm font-medium">{label}<input type="file" accept=".pdf,.docx,.jpg,.jpeg,.png,.webp" className="mt-3 block w-full rounded-xl border bg-white p-2 text-sm" onChange={(event) => onChange(event.target.files?.[0] ?? null)}/><span className="mt-2 block text-xs font-normal text-slate-400">{file ? `Selected: ${file.name}` : help}</span></label>;
const Summary = ({ label, value }: { label: string; value: string }) => <div className="rounded-xl bg-white p-4"><p className="text-xs text-slate-400">{label}</p><p className="mt-1 text-xl font-semibold text-brand-700">{value}</p></div>;
