import { useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { Link, useNavigate, useSearchParams } from "react-router-dom";
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";
import { authApi } from "@/features/auth/authApi";
export const ForgotPasswordPage = () => { const [email, setEmail] = useState(""); const mutation = useMutation({ mutationFn: () => authApi.requestPasswordReset({ email }) }); return <AuthShell title="Forgot Super Admin password"><p className="text-sm text-slate-500">This recovery option is reserved for the configured Super Admin account.</p><form className="mt-6 space-y-4" onSubmit={(e) => { e.preventDefault(); mutation.mutate(); }}><label className="block text-sm font-medium">Super Admin email<Input required type="email" className="mt-2" value={email} onChange={(e) => setEmail(e.target.value)}/></label>{mutation.error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">Unable to process request.</p>}{mutation.isSuccess && <p className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{mutation.data?.message}</p>}<Button className="w-full" disabled={mutation.isPending}>{mutation.isPending ? "Sending…" : "Send reset link"}</Button></form><Link className="mt-5 block text-center text-sm text-brand-700 underline" to="/login">Back to sign in</Link></AuthShell>; };
export const ResetPasswordPage = () => { const [params] = useSearchParams(); const navigate = useNavigate(); const [password, setPassword] = useState(""); const mutation = useMutation({ mutationFn: () => authApi.resetPassword({ email: params.get("email") ?? "", token: params.get("token") ?? "", newPassword: password }), onSuccess: () => navigate("/login", { replace: true, state: { passwordChanged: true } }) }); return <AuthShell title="Set a new password"><form className="mt-6 space-y-4" onSubmit={(e) => { e.preventDefault(); mutation.mutate(); }}><label className="block text-sm font-medium">New password<Input required minLength={12} type="password" className="mt-2" value={password} onChange={(e) => setPassword(e.target.value)}/></label>{mutation.error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{mutation.error.message}</p>}<Button className="w-full" disabled={mutation.isPending}>{mutation.isPending ? "Saving…" : "Reset password"}</Button></form></AuthShell>; };
const AuthShell = ({ title, children }: { title: string; children: React.ReactNode }) => <main className="grid min-h-screen place-items-center bg-slate-50 px-6"><section className="w-full max-w-md rounded-2xl border bg-white p-8 shadow-soft"><p className="text-sm font-medium text-brand-700">MobiusEMS</p><h1 className="mt-2 text-2xl font-semibold">{title}</h1>{children}</section></main>;
