import { useRef, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, BrainCircuit, CheckCircle2, ChevronDown, ChevronUp, Clock3, FileSearch, FileText, ShieldCheck, Sparkles, Upload, XCircle } from "lucide-react";
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";
import { Skeleton } from "@/components/ui/Skeleton";
import { JdLibrary } from "@/pages/JdLibrary";
import { governanceApi, type FitClassification, type ResumeScreeningItem, type ScreeningResult } from "@/features/governance/governanceApi";

const fit = {
  STRONG_FIT: { label: "Strong fit", color: "bg-emerald-50 text-emerald-700 ring-emerald-100", bar: "bg-emerald-500", icon: CheckCircle2 },
  POTENTIAL_FIT: { label: "Potential fit", color: "bg-amber-50 text-amber-700 ring-amber-100", bar: "bg-amber-500", icon: AlertTriangle },
  NOT_FIT: { label: "Not fit", color: "bg-red-50 text-red-700 ring-red-100", bar: "bg-red-500", icon: XCircle }
} satisfies Record<FitClassification, { label: string; color: string; bar: string; icon: typeof CheckCircle2 }>;

export const ResumeScreenerPage = () => {
  const inputRef = useRef<HTMLInputElement>(null); const queryClient = useQueryClient();
  const [jobTitle, setJobTitle] = useState(""); const [jobDescription, setJobDescription] = useState(""); const [files, setFiles] = useState<File[]>([]); const [fileError, setFileError] = useState(""); const [active, setActive] = useState<ResumeScreeningItem | null>(null); const [expanded, setExpanded] = useState<string | null>(null); const [editingJd, setEditingJd] = useState<string | null>(null); const [jdTitle, setJdTitle] = useState(""); const [jdDescription, setJdDescription] = useState("");
  const jds = useQuery({ queryKey: ["job-descriptions"], queryFn: governanceApi.jobDescriptions });
  const history = useQuery({ queryKey: ["resume-screenings"], queryFn: governanceApi.resumeScreenings });
  const saveJd = useMutation({ mutationFn: () => editingJd && editingJd !== "NEW" ? governanceApi.updateJobDescription(editingJd, { title: jdTitle, description: jdDescription }) : governanceApi.createJobDescription({ title: jdTitle, description: jdDescription }), onSuccess: async ({ item }) => { setJobTitle(item.title); setJobDescription(item.description); setEditingJd(null); setJdTitle(""); setJdDescription(""); await queryClient.invalidateQueries({ queryKey: ["job-descriptions"] }); } });
  const deleteJd = useMutation({ mutationFn: governanceApi.deleteJobDescription, onSuccess: async (_, id) => { const selected = jds.data?.items.find((item) => item._id === id); if (selected?.title === jobTitle) { setJobTitle(""); setJobDescription(""); } await queryClient.invalidateQueries({ queryKey: ["job-descriptions"] }); } });
  const screen = useMutation({ mutationFn: () => { const data = new FormData(); data.append("jobTitle", jobTitle); data.append("jobDescription", jobDescription); files.forEach((file) => data.append("files", file)); return governanceApi.screenResumes(data); }, onSuccess: async ({ item }) => { setActive(item); setExpanded(item.results[0]?.applicant ?? null); await queryClient.invalidateQueries({ queryKey: ["resume-screenings"] }); } });
  const chooseFiles = (selected: FileList | null) => { setFileError(""); screen.reset(); const next = Array.from(selected ?? []); if (next.length > 10) return setFileError("Upload a maximum of 10 resumes in one screening."); const invalid = next.find((file) => (!file.name.toLowerCase().endsWith(".pdf") && !file.name.toLowerCase().endsWith(".docx")) || file.size > 10 * 1024 * 1024); if (invalid) return setFileError(invalid.size > 10 * 1024 * 1024 ? `${invalid.name} is larger than 10 MB.` : `${invalid.name} is not a PDF or DOCX file.`); setFiles(next); };
  const loadHistory = async (id: string) => { const { item } = await governanceApi.resumeScreening(id); setActive(item); setExpanded(item.results[0]?.applicant ?? null); };
  const canRun = jobTitle.trim().length >= 2 && jobDescription.trim().length >= 100 && files.length > 0 && !screen.isPending;

  return <main className="flex-1 px-5 py-8 sm:px-8"><div className="mx-auto max-w-[1440px]">
    <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-2 text-sm font-semibold text-brand-700"><Sparkles size={16}/> Recruitment intelligence</div><h1 className="mt-2 text-3xl font-semibold tracking-tight">Resume Screener</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Compare applicant evidence with one job description, rank the results, and document a clear fit or non-fit reason for human review.</p></div><div className="flex items-center gap-2 rounded-xl border border-emerald-100 bg-emerald-50 px-4 py-3 text-xs font-medium text-emerald-700"><ShieldCheck size={17}/> Super Admin only · Private & audited</div></div>

    <section className="mt-8 grid gap-6 xl:grid-cols-[1.08fr_.92fr]"><div className="rounded-2xl border bg-white p-6 shadow-soft"><div className="flex items-center gap-3"><div className="grid size-11 place-items-center rounded-xl bg-brand-50 text-brand-700"><FileSearch size={20}/></div><div><h2 className="font-semibold">1. Job description</h2><p className="text-xs text-slate-400">The score is specific to this role.</p></div></div><label className="mt-6 block text-sm font-medium">Job title<Input className="mt-2" value={jobTitle} onChange={(event) => setJobTitle(event.target.value)} placeholder="For example: Senior React Developer" maxLength={160}/></label><label className="mt-5 block text-sm font-medium">Full job description<textarea className="mt-2 min-h-64 w-full resize-y rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm leading-6 outline-none transition placeholder:text-slate-400 focus:border-brand-400 focus:ring-4 focus:ring-brand-50" value={jobDescription} onChange={(event) => setJobDescription(event.target.value)} placeholder="Paste responsibilities, mandatory skills, preferred skills, experience and education..." maxLength={30000}/><span className="mt-1 flex justify-between text-xs font-normal text-slate-400"><span>Minimum 100 characters for a meaningful comparison.</span><span>{jobDescription.length.toLocaleString()} / 30,000</span></span></label></div>
      <div className="rounded-2xl border bg-white p-6 shadow-soft"><div className="flex items-center gap-3"><div className="grid size-11 place-items-center rounded-xl bg-violet-50 text-violet-700"><Upload size={20}/></div><div><h2 className="font-semibold">2. Applicant resumes</h2><p className="text-xs text-slate-400">Upload up to 10 searchable PDF or DOCX files.</p></div></div><button type="button" className="mt-6 grid min-h-48 w-full place-items-center rounded-2xl border-2 border-dashed border-slate-200 bg-slate-50/70 p-6 text-center transition hover:border-brand-300 hover:bg-brand-50/40" onClick={() => inputRef.current?.click()}><span><span className="mx-auto grid size-12 place-items-center rounded-full bg-white text-brand-700 shadow-sm"><Upload size={20}/></span><span className="mt-3 block text-sm font-semibold">Choose resume files</span><span className="mt-1 block text-xs text-slate-400">PDF or DOCX · 10 MB each · multiple selection supported</span></span></button><input ref={inputRef} className="hidden" type="file" accept="application/pdf,.pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document,.docx" multiple onChange={(event) => chooseFiles(event.target.files)}/>
        {files.length > 0 && <div className="mt-4 max-h-48 space-y-2 overflow-y-auto">{files.map((file) => <div className="flex items-center gap-3 rounded-xl border bg-white px-3 py-2.5" key={`${file.name}-${file.size}`}><FileText size={16} className="shrink-0 text-red-500"/><span className="min-w-0 flex-1 truncate text-xs font-medium">{file.name}</span><span className="text-[10px] text-slate-400">{(file.size / 1024 / 1024).toFixed(1)} MB</span></div>)}</div>}
        {fileError && <p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{fileError}</p>}{screen.error && <p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{screen.error.message}</p>}
        <Button className="mt-5 w-full" disabled={!canRun} onClick={() => screen.mutate()}>{screen.isPending ? <><BrainCircuit className="animate-pulse" size={17}/> Screening {files.length} resume{files.length === 1 ? "" : "s"}...</> : <><Sparkles size={17}/> Screen and rank applicants</>}</Button><p className="mt-3 text-center text-[11px] leading-5 text-slate-400">Advisory output only. A human reviewer must verify every result before making a hiring decision.</p>
      </div></section>

    <JdLibrary items={jds.data?.items ?? []} loading={jds.isLoading} selectedTitle={jobTitle} editingId={editingJd} title={jdTitle} description={jdDescription} pending={saveJd.isPending} error={saveJd.error?.message} onSelect={(item) => { setJobTitle(item.title); setJobDescription(item.description); }} onStartNew={() => { setEditingJd("NEW"); setJdTitle(""); setJdDescription(""); saveJd.reset(); }} onEdit={(item) => { setEditingJd(item._id); setJdTitle(item.title); setJdDescription(item.description); saveJd.reset(); }} onDelete={(item) => { if (window.confirm(`Delete the saved JD “${item.title}”? Past screenings and applicants will remain unchanged.`)) deleteJd.mutate(item._id); }} onCancel={() => setEditingJd(null)} onTitle={setJdTitle} onDescription={setJdDescription} onSave={() => saveJd.mutate()}/>
    {active && <Results screening={active} expanded={expanded} setExpanded={setExpanded}/>} 
    <section className="mt-8 overflow-hidden rounded-2xl border bg-white shadow-soft"><div className="flex items-center border-b p-5"><Clock3 size={18} className="text-brand-700"/><div className="ml-3"><h2 className="font-semibold">Screening history</h2><p className="text-xs text-slate-400">The 30 most recent comparisons</p></div></div>{history.isLoading ? <div className="space-y-3 p-5"><Skeleton className="h-14"/><Skeleton className="h-14"/></div> : history.data?.items.length ? <div className="divide-y">{history.data.items.map((item) => <button type="button" className="flex w-full items-center gap-4 px-5 py-4 text-left hover:bg-slate-50" key={item._id} onClick={() => void loadHistory(item._id)}><div className="grid size-10 place-items-center rounded-xl bg-slate-100 text-slate-600"><FileSearch size={17}/></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{item.jobTitle}</p><p className="mt-1 text-xs text-slate-400">{item.results.length} applicant{item.results.length === 1 ? "" : "s"} · {new Date(item.createdAt).toLocaleString()}</p></div><span className="text-xs font-semibold text-brand-700">View results</span></button>)}</div> : <p className="p-8 text-center text-sm text-slate-400">No screenings completed yet.</p>}</section>
  </div></main>;
};

const Results = ({ screening, expanded, setExpanded }: { screening: ResumeScreeningItem; expanded: string | null; setExpanded: (id: string | null) => void }) => <section className="mt-8"><div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-brand-700">Ranked results</p><h2 className="mt-1 text-2xl font-semibold">{screening.jobTitle}</h2></div><p className="text-xs text-slate-400">{screening.results.length} applicants · screened {new Date(screening.createdAt).toLocaleString()}</p></div><div className="mt-5 space-y-3">{screening.results.map((result, index) => <ResultCard key={result.applicant} result={result} rank={index + 1} open={expanded === result.applicant} toggle={() => setExpanded(expanded === result.applicant ? null : result.applicant)}/>)}</div></section>;

const ResultCard = ({ result, rank, open, toggle }: { result: ScreeningResult; rank: number; open: boolean; toggle: () => void }) => { const state = fit[result.classification]; const Icon = state.icon; return <article className="overflow-hidden rounded-2xl border bg-white shadow-soft"><button type="button" className="flex w-full items-center gap-4 p-5 text-left" onClick={toggle}><div className="grid size-11 shrink-0 place-items-center rounded-xl bg-ink text-sm font-bold text-white">#{rank}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="text-base font-semibold">{result.candidateName}</h3><span className={`inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-[11px] font-semibold ring-1 ${state.color}`}><Icon size={12}/>{state.label}</span></div><p className="mt-1 truncate text-xs text-slate-500">{result.summary}</p></div><div className="hidden w-36 sm:block"><div className="flex items-center justify-between text-xs"><span className="text-slate-400">Match score</span><strong>{result.score}%</strong></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${state.bar}`} style={{ width: `${result.score}%` }}/></div></div>{open ? <ChevronUp className="text-slate-400" size={18}/> : <ChevronDown className="text-slate-400" size={18}/>}</button>{open && <div className="border-t bg-slate-50/50 p-5"><div className="rounded-xl border bg-white p-4"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Written assessment</p><p className="mt-2 text-sm leading-6 text-slate-700">{result.writtenReason}</p></div><div className="mt-4 grid gap-4 lg:grid-cols-3"><Evidence title="Matched requirements" items={result.matchedRequirements} tone="good"/><Evidence title="Missing or not demonstrated" items={result.missingRequirements} tone="bad"/><Evidence title="Resume evidence" items={result.evidence} tone="neutral"/></div></div>}</article>; };
const Evidence = ({ title, items, tone }: { title: string; items: string[]; tone: "good" | "bad" | "neutral" }) => <div className="rounded-xl border bg-white p-4"><h4 className="text-xs font-semibold uppercase tracking-wide text-slate-500">{title}</h4><ul className="mt-3 space-y-2">{items.length ? items.map((item, index) => <li className="flex gap-2 text-xs leading-5 text-slate-600" key={`${item}-${index}`}><span className={`mt-1.5 size-1.5 shrink-0 rounded-full ${tone === "good" ? "bg-emerald-500" : tone === "bad" ? "bg-red-500" : "bg-brand-500"}`}/>{item}</li>) : <li className="text-xs text-slate-400">No items reported.</li>}</ul></div>;
