import { Router } from "express";
import { authRouter } from "./authRoutes.js";
import { dashboardRouter } from "./dashboardRoutes.js";
import { employeeRouter } from "./employeeRoutes.js";
import { organizationRouter } from "./organizationRoutes.js";
import { skillRouter } from "./skillRoutes.js";
import { workRouter } from "./workRoutes.js";
import { outcomeRouter } from "./outcomeRoutes.js";
import { developmentRouter } from "./developmentRoutes.js";
import { governanceRouter } from "./governanceRoutes.js";
import { peopleOpsRouter } from "./peopleOpsRoutes.js";
import { attendanceRouter } from "./attendanceRoutes.js";
import { contributionRouter } from "./contributionRoutes.js";
import { aiRouter } from "./aiRoutes.js";
import { todoRouter } from "./todoRoutes.js";
import { emailAutomationRouter } from "./emailAutomationRoutes.js";
export const apiRouter = Router();
apiRouter.use("/auth", authRouter);
apiRouter.use("/dashboard", dashboardRouter);
apiRouter.use("/employees", employeeRouter);
apiRouter.use("/organization", organizationRouter);
apiRouter.use("/skills", skillRouter);
apiRouter.use("/work", workRouter);
apiRouter.use("/outcomes", outcomeRouter);
apiRouter.use("/development", developmentRouter);
apiRouter.use("/governance", governanceRouter);
apiRouter.use("/people-ops", peopleOpsRouter);
apiRouter.use("/attendance", attendanceRouter);
apiRouter.use("/contribution", contributionRouter);
apiRouter.use("/ai", aiRouter);
apiRouter.use("/todos", todoRouter);
apiRouter.use("/email-automation", emailAutomationRouter);
