import { Router } from "express"; import * as controller from "../controllers/organizationController.js"; import { authenticate, requirePermission } from "../middleware/auth.js"; import { validate } from "../middleware/validate.js"; import { asyncHandler } from "../utils/asyncHandler.js"; import { departmentSchema, designationSchema, teamSchema, updateDepartmentSchema, updateTeamSchema, updateDesignationSchema, updateDesignationSkillsSchema, generateSkillsSchema } from "../validators/organizationValidators.js";
export const organizationRouter = Router(); organizationRouter.use(authenticate);
organizationRouter.get("/hierarchy-flow", asyncHandler(controller.getHierarchyFlow));
organizationRouter.get("/", requirePermission("department.view"), asyncHandler(controller.list));
organizationRouter.post("/departments", requirePermission("department.create"), validate(departmentSchema), asyncHandler(controller.createDepartment));
organizationRouter.patch("/departments/:id", requirePermission("department.update"), validate(updateDepartmentSchema), asyncHandler(controller.updateDepartment));
organizationRouter.post("/teams", requirePermission("department.create"), validate(teamSchema), asyncHandler(controller.createTeam));
organizationRouter.patch("/teams/:id", requirePermission("department.update"), validate(updateTeamSchema), asyncHandler(controller.updateTeam));
organizationRouter.post("/designations", requirePermission("department.create"), validate(designationSchema), asyncHandler(controller.createDesignation));
organizationRouter.patch("/designations/:id", requirePermission("department.update"), validate(updateDesignationSchema), asyncHandler(controller.updateDesignation));
organizationRouter.put("/designations/:id/skills", requirePermission("department.update"), validate(updateDesignationSkillsSchema), asyncHandler(controller.updateDesignationSkills));
organizationRouter.get("/skill-catalog/:role", requirePermission("department.view"), asyncHandler(controller.getSkillCatalogForRole));
organizationRouter.post("/generate-skills", requirePermission("department.update"), validate(generateSkillsSchema), asyncHandler(controller.generateSkills));
organizationRouter.post("/auto-structure", requirePermission("employee.update"), asyncHandler(controller.autoStructureHierarchy));
organizationRouter.patch("/employees/:id/manager", requirePermission("employee.update"), asyncHandler(controller.updateEmployeeManager));
