import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, CheckCircle2, Clock3, LockKeyhole, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/Button";
import { Skeleton } from "@/components/ui/Skeleton";
import { skillApi, type CatalogSkill, type RoleSkillAssessment, type RoleSkillScore } from "@/features/skills/skillApi";

const levelStyle: Record<string, string> = { Basic: "bg-sky-50 text-sky-700", Intermediate: "bg-amber-50 text-amber-700", Advanced: "bg-violet-50 text-violet-700" };
const groupByLevel = <T extends { level: string }>(items: T[]) => Object.entries(items.reduce<Record<string, T[]>>((groups, item) => { (groups[item.level] ??= []).push(item); return groups; }, {}));

const evidenceStyle = { JUSTIFIED: "bg-emerald-50 text-emerald-700", IN_PROGRESS: "bg-blue-50 text-blue-700", NEEDS_EVIDENCE: "bg-amber-50 text-amber-700" };
const SavedSkill = ({ skill, evidence }: { skill: RoleSkillScore; evidence?: NonNullable<RoleSkillAssessment["evidenceAnalytics"]>[number] }) => <div className="p-5">
  <div className="flex flex-col gap-3 sm:flex-row sm:items-center">
    <div className="min-w-0 flex-1"><p className="font-semibold">{skill.name}</p><p className="mt-1 text-xs leading-5 text-slate-500">{skill.description}</p><p className="mt-1 text-[11px] text-slate-400">{skill.category} · {skill.tools}</p></div>
    <div className="shrink-0 rounded-xl bg-brand-50 px-4 py-2 text-center"><p className="text-xl font-semibold text-brand-700">{skill.rating}/10</p><p className="text-[10px] text-brand-600">Self-score</p></div>
  </div>
  {skill.implementationNote && <div className="mt-4 rounded-xl border bg-slate-50 p-3"><p className="text-[10px] font-semibold uppercase tracking-wide text-slate-400">How I implemented this skill</p><p className="mt-1 whitespace-pre-wrap text-sm leading-6 text-slate-600">{skill.implementationNote}</p></div>}
  {evidence && <div className="mt-4 rounded-xl border p-4"><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold ${evidenceStyle[evidence.status]}`}>{evidence.status.replaceAll("_", " ")}</span><span className="text-xs text-slate-500">Evidence confidence {evidence.justificationScore}%</span><span className="ml-auto text-xs text-slate-500">{evidence.completedTasks} completed · {evidence.onTimeRate}% on time{evidence.averageQuality ? ` · ${evidence.averageQuality}/5 quality` : ""}</span></div><p className="mt-2 text-xs leading-5 text-slate-600">{evidence.message}</p>{evidence.tasks.length > 0 && <div className="mt-3 space-y-2">{evidence.tasks.map((task) => <div className="flex items-center gap-2 text-xs" key={task.id}>{task.status === "COMPLETED" ? <CheckCircle2 size={13} className="text-emerald-600"/> : task.overdue ? <AlertTriangle size={13} className="text-red-500"/> : <Clock3 size={13} className="text-blue-500"/>}<span className="font-medium text-slate-700">{task.taskId}</span><span className="min-w-0 truncate text-slate-500">{task.name}</span><span className="ml-auto shrink-0 text-slate-400">{task.status.replaceAll("_", " ")}</span></div>)}</div>}</div>}
</div>;

const Results = ({ assessment }: { assessment: RoleSkillAssessment }) => {
  const groups = useMemo(() => groupByLevel(assessment.scores), [assessment.scores]);
  const analytics = useMemo(() => new Map(assessment.evidenceAnalytics?.map((item) => [item.skillId, item]) ?? []), [assessment.evidenceAnalytics]);
  const justified = assessment.evidenceAnalytics?.filter((item) => item.status === "JUSTIFIED").length ?? 0;
  return <div className="mx-auto max-w-[1440px]">
    <section className="rounded-3xl border bg-white p-6 shadow-soft sm:p-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-center"><div className="grid size-12 place-items-center rounded-2xl bg-emerald-50 text-emerald-700"><CheckCircle2 size={24}/></div><div><p className="text-sm font-medium text-emerald-700">Assessment completed</p><h1 className="mt-1 text-3xl font-semibold">{assessment.role}</h1>{assessment.designation && <p className="mt-1 text-sm font-medium text-slate-600">Designation: {assessment.designation}</p>}<p className="mt-2 text-sm text-slate-500">Submitted {new Date(assessment.submittedAt).toLocaleString()} · Your answers are locked and cannot be edited.</p></div><div className="sm:ml-auto sm:text-right"><p className="text-xs uppercase tracking-wide text-slate-400">Overall self-score</p><p className="mt-1 text-3xl font-semibold text-brand-700">{assessment.averageRating}<span className="text-base text-slate-400"> / 10</span></p></div></div></section>
    {assessment.evidenceAnalytics && <section className="mt-5 rounded-2xl border bg-white p-5 shadow-soft"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-brand-50 text-brand-700"><Sparkles size={18}/></div><div><h2 className="font-semibold">AI work-evidence monitor</h2><p className="text-xs text-slate-500">Continuously compares your ratings with related assigned tasks, delivery time and manager quality reviews.</p></div><div className="ml-auto text-right"><p className="text-2xl font-semibold text-brand-700">{justified}/{assessment.scores.length}</p><p className="text-[10px] text-slate-400">ratings justified</p></div></div></section>}
    <div className="mt-5 space-y-5">{groups.map(([level, skills]) => <section className="rounded-2xl border bg-white shadow-soft" key={level}><div className="flex items-center border-b p-5"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${levelStyle[level] ?? "bg-slate-100 text-slate-700"}`}>{level}</span><span className="ml-auto text-xs text-slate-400">{skills.length} skills</span></div><div className="divide-y">{skills.map((skill) => <SavedSkill key={skill.skillId} skill={skill} evidence={analytics.get(skill.skillId)}/>)}</div></section>)}</div>
  </div>;
};

const RatingButtons = ({ skill, value, onChange }: { skill: CatalogSkill; value?: number; onChange: (rating: number) => void }) => <fieldset className="shrink-0"><legend className="mb-2 text-xs font-medium text-slate-500">How good are you? <span className="text-brand-700">{value ? `${value}/10` : "Not rated"}</span></legend><div className="flex flex-wrap gap-1.5">{Array.from({ length: 10 }, (_, index) => index + 1).map((rating) => <button type="button" aria-label={`${skill.name}: ${rating} out of 10`} className={`grid size-9 place-items-center rounded-lg border text-xs font-semibold transition ${value === rating ? "border-brand-600 bg-brand-600 text-white" : "bg-white text-slate-500 hover:border-brand-300 hover:bg-brand-50"}`} key={rating} onClick={() => onChange(rating)}>{rating}</button>)}</div></fieldset>;

const EditableSkill = ({ skill, rating, note, onRating, onNote }: { skill: CatalogSkill; rating?: number; note: string; onRating: (rating: number) => void; onNote: (note: string) => void }) => <div className="p-5">
  <div className="flex flex-col gap-4 lg:flex-row lg:items-center"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold">{skill.name}</h2><span className="rounded-full bg-slate-100 px-2 py-0.5 text-[10px] font-medium text-slate-500">{skill.category}</span></div><p className="mt-1 text-xs leading-5 text-slate-500">{skill.description}</p><p className="mt-1 text-[11px] text-slate-400">Tools: {skill.tools}</p></div><RatingButtons skill={skill} value={rating} onChange={onRating}/></div>
  {skill.assessmentQuestion && <div className="mt-4 rounded-xl border border-brand-100 bg-brand-50 p-3"><p className="text-[10px] font-semibold uppercase tracking-wide text-brand-700">Assessment question</p><p className="mt-1 text-sm leading-6 text-brand-900">{skill.assessmentQuestion}</p></div>}
  <label className="mt-4 block text-xs font-medium text-slate-600">Your evidence-based answer <span className="text-red-500">*</span><textarea required minLength={10} maxLength={1000} rows={3} className={`mt-2 w-full resize-y rounded-xl border px-3 py-2.5 text-sm leading-5 placeholder:text-slate-400 focus:bg-white ${note.trim().length > 0 && note.trim().length < 10 ? "border-red-300 bg-red-50" : "bg-slate-50"}`} placeholder="Required: explain the situation, your action, the result and supporting evidence..." value={note} onChange={(event) => onNote(event.target.value)}/><span className={`mt-1 block text-right text-[10px] ${note.trim().length > 0 && note.trim().length < 10 ? "text-red-500" : "text-slate-400"}`}>{note.length}/1000 · minimum 10 characters</span></label>
</div>;

export const RoleSkillsAssessment = () => {
  const queryClient = useQueryClient();
  const query = useQuery({ queryKey: ["skills", "role-assessment"], queryFn: skillApi.roleAssessment });
  const [ratings, setRatings] = useState<Record<string, number>>({});
  const [notes, setNotes] = useState<Record<string, string>>({});
  const roleSkills = useMemo(() => query.data?.catalog ?? [], [query.data?.catalog]);
  const grouped = useMemo(() => groupByLevel(roleSkills), [roleSkills]);
  const completed = roleSkills.filter((skill) => ratings[skill.id] && (notes[skill.id]?.trim().length ?? 0) >= 10).length;
  const submit = useMutation({ mutationFn: () => skillApi.submitRoleAssessment({ ratings: roleSkills.map((skill) => ({ skillId: skill.id, rating: ratings[skill.id]!, implementationNote: notes[skill.id]!.trim() })) }), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ["skills", "role-assessment"] }); } });
  const confirmSubmit = () => { if (completed === roleSkills.length && window.confirm(`Submit all ${roleSkills.length} completed skill blocks for ${query.data?.designation.name}? This is a one-time form and cannot be edited after submission.`)) submit.mutate(); };

  if (query.isLoading) return <main className="flex-1 px-5 py-8 sm:px-8"><Skeleton className="h-72"/></main>;
  if (query.isError || !query.data) return <main className="grid min-h-96 flex-1 place-items-center text-sm text-red-600">Unable to load the role skill catalog.</main>;
  if (query.data.assessment) return <main className="flex-1 px-5 py-8 sm:px-8"><Results assessment={query.data.assessment}/></main>;

  return <main className="flex-1 px-5 py-8 sm:px-8"><div className="mx-auto max-w-[1440px]">
    <div><p className="text-sm font-medium text-brand-700">One-time employee form</p><h1 className="mt-1 text-3xl font-semibold">Designation skill self-assessment</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">Your designation was assigned by Super Admin. Complete every corresponding skill block with a 1–10 rating and an implementation explanation; your response cannot be edited after submission.</p></div>
    <section className="mt-7 rounded-2xl border bg-white p-5 shadow-soft"><div className="grid gap-4 md:grid-cols-2"><label className="block text-sm font-semibold">Assigned designation<input readOnly className="mt-2 h-12 w-full cursor-not-allowed rounded-xl border bg-slate-50 px-3 text-sm text-slate-600" value={`${query.data.designation.name} (${query.data.designation.code})`}/></label><label className="block text-sm font-semibold">Assigned skill catalogue<input readOnly className="mt-2 h-12 w-full cursor-not-allowed rounded-xl border bg-slate-50 px-3 text-sm text-slate-600" value={`${query.data.assignedRole} (${roleSkills.length} skills)`}/></label></div><div className="mt-5 flex flex-col gap-3 border-t pt-5 sm:flex-row sm:items-center"><div className="flex-1"><div className="flex justify-between text-xs"><span className="font-medium">Completed skill blocks</span><span>{completed} of {roleSkills.length} complete</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-brand-500 transition-all" style={{ width: `${roleSkills.length ? completed / roleSkills.length * 100 : 0}%` }}/></div></div><div className="flex items-center gap-2 text-xs text-slate-500"><LockKeyhole size={14}/> Locks after submission</div></div></section>
    <div className="mt-5 space-y-5">{grouped.map(([level, skills]) => <section className="rounded-2xl border bg-white shadow-soft" key={level}><div className="flex items-center border-b p-5"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${levelStyle[level] ?? "bg-slate-100 text-slate-700"}`}>{level}</span><span className="ml-auto text-xs text-slate-400">{skills.length} skills</span></div><div className="divide-y">{skills.map((skill) => <EditableSkill key={skill.id} skill={skill} rating={ratings[skill.id]} note={notes[skill.id] ?? ""} onRating={(rating) => setRatings((current) => ({ ...current, [skill.id]: rating }))} onNote={(note) => setNotes((current) => ({ ...current, [skill.id]: note }))}/>)}</div></section>)}<section className="sticky bottom-4 z-10 flex flex-col gap-3 rounded-2xl border bg-white/95 p-4 shadow-xl backdrop-blur sm:flex-row sm:items-center"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-brand-50 text-brand-700"><Sparkles size={18}/></div><div><p className="text-sm font-semibold">{completed === roleSkills.length ? "Ready to submit" : `${roleSkills.length - completed} skill blocks remaining`}</p><p className="text-xs text-slate-400">Every block requires both a score and implementation explanation.</p></div></div><Button className="sm:ml-auto" disabled={!roleSkills.length || completed !== roleSkills.length || submit.isPending} onClick={confirmSubmit}>{submit.isPending ? "Submitting..." : `Submit ${roleSkills.length} completed skills`}</Button>{submit.isError && <p className="text-xs text-red-600">{submit.error.message}</p>}</section></div>
  </div></main>;
};
