import { api } from "@/api/client";
export interface Skill { _id: string; name: string; category: string; description?: string }
export interface SkillClaim { _id: string; skill: Skill; employee?: { _id: string; firstName: string; lastName: string; employeeId: string }; selfRating: number; verifiedRating?: number; yearsOfExperience: number; verificationStatus: string; evidence: { type: string; url?: string; comment?: string }[] }
export interface Assessment { _id: string; name: string; skill: Skill; difficulty: string; maximumScore: number; passingScore: number; timeLimitMinutes: number; assignedEmployee: { _id: string; firstName: string; lastName: string; employeeId: string }; score?: number; result?: string }
export interface CatalogSkill { id: string; role: string; level: string; category: string; name: string; tools: string; description: string }
export interface RoleSkillScore extends Omit<CatalogSkill, "id" | "role"> { skillId: string; rating: number; implementationNote?: string }
export interface RoleSkillAssessment { _id: string; role: string; scores: RoleSkillScore[]; averageRating: number; submittedAt: string }
export interface RoleAssessmentData { roles: { role: string; skillCount: number }[]; catalog: CatalogSkill[]; assessment: RoleSkillAssessment | null }
export const skillApi = { list: () => api.get<{ items: Skill[] }>("/api/v1/skills"), create: (body: { name: string; category: string; description?: string }) => api.post("/api/v1/skills", body), mine: () => api.get<{ items: SkillClaim[]; gap: { roleMatch: number; items: { skill: string; required: number; actual: number; gap: number; isCritical: boolean }[] } }>("/api/v1/skills/mine"), claim: (body: { skill: string; selfRating: number; yearsOfExperience: number; description?: string; evidence: { type: string; url?: string }[] }) => api.post("/api/v1/skills/mine", body), roleAssessment: () => api.get<RoleAssessmentData>("/api/v1/skills/role-assessment"), submitRoleAssessment: (body: { role: string; ratings: { skillId: string; rating: number; implementationNote?: string }[] }) => api.post<{ assessment: RoleSkillAssessment }>("/api/v1/skills/role-assessment", body), pending: () => api.get<{ items: SkillClaim[] }>("/api/v1/skills/verifications/pending"), verify: (id: string, body: { status: string; verifiedRating?: number; method: string; justification: string }) => api.patch(`/api/v1/skills/verifications/${id}`, body), heatmap: () => api.get<{ items: SkillClaim[] }>("/api/v1/skills/heatmap"), assessments: () => api.get<{ items: Assessment[] }>("/api/v1/skills/assessments"), assignAssessment: (body: unknown) => api.post("/api/v1/skills/assessments", body), recordResult: (id: string, body: unknown) => api.patch(`/api/v1/skills/assessments/${id}/result`, body) };
