import { z } from "zod"; import { EMPLOYEE_STATUSES, EMPLOYMENT_TYPES } from "../models/Employee.js";
const objectId = z.string().regex(/^[a-f\d]{24}$/i, "Invalid identifier");
const optionalObjectId = z.preprocess((value) => value === "" ? undefined : value, objectId.optional());
export const createEmployeeSchema = z.object({ body: z.object({
  firstName: z.string().trim().min(1).max(80), lastName: z.string().trim().min(1).max(80), officialEmail: z.string().email().max(254).transform((v) => v.toLowerCase()), phone: z.string().trim().max(30).optional(),
  department: objectId, team: optionalObjectId, designation: objectId, reportingManager: optionalObjectId, dateOfJoining: z.coerce.date(), employmentType: z.enum(EMPLOYMENT_TYPES), officeLocation: z.string().trim().max(120).optional(), role: z.literal("EMPLOYEE").default("EMPLOYEE"), status: z.enum(EMPLOYEE_STATUSES).default("ONBOARDING")
}) });
export const listEmployeesSchema = z.object({ query: z.object({ page: z.coerce.number().int().min(1).default(1), limit: z.coerce.number().int().min(1).max(100).default(20), search: z.string().trim().max(100).optional(), department: objectId.optional(), status: z.enum(EMPLOYEE_STATUSES).optional() }) });
export const onboardingSchema = z.object({ body: z.object({ step: z.number().int().min(2).max(8), personal: z.object({ personalEmail: z.string().email().optional(), dateOfBirth: z.coerce.date().optional(), address: z.string().trim().max(500).optional(), emergencyContact: z.string().trim().max(120).optional() }).optional(), professionalSummary: z.string().trim().max(2000).optional(), previousExperience: z.array(z.object({ company: z.string().trim().min(1).max(120), role: z.string().trim().min(1).max(120), startDate: z.coerce.date(), endDate: z.coerce.date().optional(), summary: z.string().trim().max(1000).optional() })).max(20).optional(), complete: z.boolean().optional() }) });
export const updateEmployeeSchema = z.object({ params: z.object({ id: objectId }), body: z.object({ firstName: z.string().trim().min(1).max(80).optional(), lastName: z.string().trim().min(1).max(80).optional(), phone: z.string().trim().max(30).optional(), department: objectId.optional(), team: objectId.nullable().optional(), designation: objectId.optional(), reportingManager: objectId.nullable().optional(), employmentType: z.enum(EMPLOYMENT_TYPES).optional(), officeLocation: z.string().trim().max(120).optional(), status: z.enum(EMPLOYEE_STATUSES).optional() }).refine((body) => Object.keys(body).length > 0, "At least one field is required") });
export const updateMyProfileSchema = z.object({ body: z.object({ firstName: z.string().trim().min(1).max(80).optional(), lastName: z.string().trim().min(1).max(80).optional(), phone: z.string().trim().min(5).max(30).optional(), professionalSummary: z.string().trim().min(20).max(2000).optional(), personal: z.object({ personalEmail: z.string().email().optional(), address: z.string().trim().min(5).max(500).optional(), emergencyContact: z.string().trim().min(5).max(120).optional() }).optional() }).refine((body) => Object.keys(body).length > 0, "At least one field is required") });
export const employeeIdSchema = z.object({ params: z.object({ id: objectId }) });
