import { z } from "zod";
const objectId = z.string().regex(/^[a-f\d]{24}$/i, "Invalid identifier");
const code = z.string().trim().min(2).max(20).regex(/^[A-Za-z0-9_-]+$/).transform((v) => v.toUpperCase());
const capabilities = z.array(z.enum(["SALES_MODULE"])).default([]);
export const departmentSchema = z.object({ body: z.object({ name: z.string().trim().min(2).max(120), code, description: z.string().trim().max(500).optional(), capabilities }) });
export const teamSchema = z.object({ body: z.object({ name: z.string().trim().min(2).max(120), code, department: objectId, description: z.string().trim().max(500).optional() }) });
export const designationSchema = z.object({ body: z.object({ name: z.string().trim().min(2).max(120), code, department: objectId.optional(), level: z.string().trim().max(50).optional(), description: z.string().trim().max(500).optional(), catalogRole: z.string().trim().min(1).max(120) }) });
export const updateDepartmentSchema = z.object({ params: z.object({ id: objectId }), body: z.object({ name: z.string().trim().min(2).max(120).optional(), code: code.optional(), description: z.string().trim().max(500).optional(), capabilities: capabilities.optional() }) });
export const updateTeamSchema = z.object({ params: z.object({ id: objectId }), body: z.object({ name: z.string().trim().min(2).max(120).optional(), code: code.optional(), department: objectId.optional(), description: z.string().trim().max(500).optional() }) });
export const updateDesignationSchema = z.object({ params: z.object({ id: objectId }), body: z.object({ name: z.string().trim().min(2).max(120).optional(), code: code.optional(), department: objectId.optional(), level: z.string().trim().max(50).optional(), description: z.string().trim().max(500).optional(), catalogRole: z.string().trim().min(1).max(120).optional() }) });
