import { z } from "zod"; import { GOAL_STATUSES } from "../models/Goal.js"; import { REVIEW_CATEGORIES, REVIEW_TYPES } from "../models/PerformanceReview.js";
const objectId = z.string().regex(/^[a-f\d]{24}$/i, "Invalid identifier");
export const goalSchema = z.object({ body: z.object({ name: z.string().trim().min(2).max(200), description: z.string().trim().max(3000).optional(), employee: objectId, period: z.string().trim().min(1).max(50), weight: z.number().min(0).max(100), startDate: z.coerce.date(), endDate: z.coerce.date(), progress: z.number().min(0).max(100).default(0), status: z.enum(GOAL_STATUSES).default("NOT_STARTED"), managerComment: z.string().trim().max(2000).optional() }) });
export const kpiSchema = z.object({ body: z.object({ name: z.string().trim().min(2).max(160), description: z.string().trim().max(2000).optional(), target: z.number(), unit: z.string().trim().min(1).max(40), weight: z.number().min(0).max(100), period: z.string().trim().min(1).max(50), role: objectId.optional(), department: objectId.optional() }) });
export const evaluateKpiSchema = z.object({ params: z.object({ id: objectId }), body: z.object({ employee: objectId, period: z.string().trim().min(1).max(50), actual: z.number(), comment: z.string().trim().max(2000).optional() }) });
export const reviewSchema = z.object({ body: z.object({ employee: objectId, type: z.enum(REVIEW_TYPES), period: z.string().trim().min(1).max(50), ratings: z.array(z.object({ category: z.enum(REVIEW_CATEGORIES), rating: z.number().int().min(1).max(5), comment: z.string().trim().max(1000).optional() })).min(1).max(10), comments: z.string().trim().max(3000).optional(), employeeResponse: z.string().trim().max(3000).optional() }) });
export const snapshotSchema = z.object({ body: z.object({ employee: objectId, period: z.string().trim().min(1).max(50), periodType: z.enum(REVIEW_TYPES) }) });
export const performanceAnalyticsSchema = z.object({ query: z.object({ period: z.string().trim().min(1).max(50), periodType: z.enum(REVIEW_TYPES), department: objectId.optional() }) });
export const calculateAllSnapshotsSchema = z.object({ body: z.object({ period: z.string().trim().min(1).max(50), periodType: z.enum(REVIEW_TYPES), department: objectId.optional() }) });
