import { z } from "zod"; import { PROJECT_STATUSES, PRIORITIES } from "../models/Project.js"; import { BLOCKER_REASONS, COMPLEXITIES, TASK_STATUSES } from "../models/Task.js";
import { LEAD_WORK_STATUSES } from "../models/LeadWorkItem.js";
import { INTERACTION_OUTCOMES, INTERACTION_TYPES } from "../models/LeadWorkActivity.js";
const objectId = z.string().regex(/^[a-f\d]{24}$/i, "Invalid identifier");
export const projectSchema = z.object({ body: z.object({ name: z.string().trim().min(2).max(160), code: z.string().trim().min(2).max(30).regex(/^[A-Za-z0-9_-]+$/).transform((v) => v.toUpperCase()).optional(), description: z.string().trim().max(3000).optional(), department: objectId, projectManager: objectId, teamMembers: z.array(objectId).max(100).default([]), startDate: z.coerce.date(), expectedEndDate: z.coerce.date().optional(), status: z.enum(PROJECT_STATUSES).default("PLANNING"), priority: z.enum(PRIORITIES).default("MEDIUM") }) });
export const taskSchema = z.object({ body: z.object({ name: z.string().trim().min(2).max(200), description: z.string().trim().max(5000).optional(), project: objectId, assignedEmployee: objectId, skillId: z.string().trim().max(100).optional(), skillName: z.string().trim().max(150).optional(), priority: z.enum(PRIORITIES).default("MEDIUM"), complexity: z.enum(COMPLEXITIES).default("MEDIUM"), estimatedHours: z.number().positive().max(10000), startDate: z.coerce.date().optional(), deadline: z.coerce.date(), reviewer: objectId.optional() }) });
export const manualTaskSchema = z.object({ body: z.object({ name: z.string().trim().min(2).max(200), description: z.string().trim().max(5000).optional(), project: objectId, verbalAssigner: z.string().trim().min(2).max(120), skillId: z.string().trim().max(100).optional(), skillName: z.string().trim().max(150).optional(), priority: z.enum(PRIORITIES).default("MEDIUM"), complexity: z.enum(COMPLEXITIES).default("MEDIUM"), estimatedHours: z.number().positive().max(10000), deadline: z.coerce.date() }) });
export const taskTransitionSchema = z.object({ params: z.object({ id: objectId }), body: z.object({ status: z.enum(TASK_STATUSES), actualHours: z.number().min(0).max(10000).optional(), completionNote: z.string().trim().max(3000).optional(), deliverableUrl: z.string().url().max(1000).optional().or(z.literal("")), businessImpact: z.string().trim().max(2000).optional(), blockerReason: z.enum(BLOCKER_REASONS).optional(), blockerComment: z.string().trim().max(1000).optional(), blockerExternal: z.boolean().optional(), resolutionComment: z.string().trim().max(1000).optional() }).superRefine((value, context) => { if (value.status === "BLOCKED" && !value.blockerReason) context.addIssue({ code: "custom", path: ["blockerReason"], message: "Blocker reason is required" }); if (value.status === "IN_REVIEW" && (!value.completionNote || value.completionNote.length < 10)) context.addIssue({ code: "custom", path: ["completionNote"], message: "Add a short completion note describing the delivered outcome" }); }) });
export const taskReviewSchema = z.object({ params: z.object({ id: objectId }), body: z.object({ qualityRating: z.number().int().min(1).max(5), reviewComment: z.string().trim().max(2000).optional(), approve: z.boolean() }) });
export const taskIdSchema = z.object({ params: z.object({ id: objectId }) });
export const taskReassignSchema = z.object({ params: z.object({ id: objectId }), body: z.object({ assignedEmployee: objectId }) });
const importRow = z.object({ rowNumber: z.number().int().min(2), values: z.record(z.string(), z.string().max(5000)), excluded: z.boolean().optional() });
export const leadImportCommitSchema = z.object({ body: z.object({ idempotencyKey: z.string().uuid(), fileName: z.string().trim().min(1).max(255), fileHash: z.string().regex(/^[a-f\d]{64}$/i), sheetName: z.string().max(120).optional(), mapping: z.record(z.string(), z.enum(["name","firstName","lastName","phone","email","companyName","market","source","notes","estimatedValue","custom"])), rows: z.array(importRow).min(1).max(5000), task: taskSchema.shape.body }) });
export const leadWorkListSchema = z.object({ params: z.object({ id: objectId }), query: z.object({ page: z.coerce.number().int().min(1).optional(), limit: z.coerce.number().int().min(1).max(100).optional(), status: z.enum(LEAD_WORK_STATUSES).optional(), followUp: z.enum(["overdue","all"]).optional(), search: z.string().trim().max(120).optional() }) });
export const leadWorkItemSchema = z.object({ params: z.object({ id: objectId, workItemId: objectId }) });
export const leadActivitySchema = z.object({ params: z.object({ id: objectId, workItemId: objectId }), body: z.object({ interactionType: z.enum(INTERACTION_TYPES), outcome: z.enum(INTERACTION_OUTCOMES), status: z.enum(LEAD_WORK_STATUSES), note: z.string().trim().min(3).max(2000), nextFollowUpAt: z.coerce.date().optional(), version: z.number().int().min(0) }) });
const voiceLanguage = z.enum(["auto", "en-IN", "hi-IN", "bn-IN", "ta-IN", "te-IN", "mr-IN", "gu-IN", "kn-IN", "ml-IN", "pa-IN", "ur-IN"]);
export const voiceTextPreviewSchema = z.object({ body: z.object({ transcript: z.string().trim().min(2).max(10_000), language: voiceLanguage.optional().default("auto"), timezoneOffsetMinutes: z.number().int().min(-840).max(840).optional().default(0) }) });
const voiceDraftSchema = z.object({
  action: z.enum(["CREATE_TASK", "UPDATE_STATUS"]), name: z.string().trim().min(2).max(200).optional(), description: z.string().trim().max(5000).optional(),
  project: objectId.optional(), assignedEmployee: objectId.optional(), verbalAssigner: z.string().trim().min(2).max(120).optional(),
  priority: z.enum(PRIORITIES).optional(), complexity: z.enum(COMPLEXITIES).optional(), estimatedHours: z.number().positive().max(10000).optional(), deadline: z.coerce.date().optional(),
  task: objectId.optional(), status: z.enum(TASK_STATUSES).optional(), actualHours: z.number().min(0).max(10000).optional(), completionNote: z.string().trim().max(3000).optional(), blockerReason: z.enum(BLOCKER_REASONS).optional(), blockerComment: z.string().trim().max(1000).optional()
}).superRefine((value, context) => {
  if (value.action === "CREATE_TASK") for (const field of ["name", "project", "deadline"] as const) if (!value[field]) context.addIssue({ code: "custom", path: [field], message: `${field} is required` });
  if (value.action === "UPDATE_STATUS") { if (!value.task) context.addIssue({ code: "custom", path: ["task"], message: "task is required" }); if (!value.status) context.addIssue({ code: "custom", path: ["status"], message: "status is required" }); if (value.status === "IN_REVIEW" && (!value.completionNote || value.completionNote.length < 10)) context.addIssue({ code: "custom", path: ["completionNote"], message: "Add a short completion note" }); }
});
export const voiceCommandSchema = z.object({ params: z.object({ id: objectId }), body: z.union([
  voiceDraftSchema,
  z.object({ drafts: z.array(voiceDraftSchema).min(1).max(25) })
]) });
export const voiceCommandIdSchema = z.object({ params: z.object({ id: objectId }) });
