import { Employee } from "../models/Employee.js";
import { User } from "../models/User.js";
import { Role } from "../models/Role.js";
import { WeeklyUpdate } from "../models/WeeklyUpdate.js";
import { OneToOne } from "../models/OneToOne.js";
import { ContributionReview, CONTRIBUTION_AREAS, type ContributionArea } from "../models/ContributionReview.js";
import { ContributionSnapshot } from "../models/ContributionSnapshot.js";
import { Task } from "../models/Task.js";
import { EmployeeKPI } from "../models/EmployeeKPI.js";
import { Goal } from "../models/Goal.js";
import { Recognition } from "../models/Recognition.js";
import { EmployeeTraining } from "../models/EmployeeTraining.js";
import { EmployeeSkill } from "../models/EmployeeSkill.js";
import { SalesLead } from "../models/SalesLead.js";
import { SalesRevenueTransaction } from "../models/SalesRevenueTransaction.js";
import { SalesTarget } from "../models/SalesTarget.js";
import { AppError } from "../utils/AppError.js";
import { writeAudit } from "./auditService.js";
import { notify } from "./notificationService.js";
import { normalizeContributionAreas, reliabilityEligible } from "./contributionMath.js";

type Viewer = { id: string; role: string };
const clamp = (value: number) => Math.max(0, Math.min(100, value));
const monthBounds = (period: string) => { const [year, month] = period.split("-").map(Number); return { start: new Date(Date.UTC(year!, month! - 1, 1)), end: new Date(Date.UTC(year!, month!, 1)) }; };
const employeeIds = async (viewer: Viewer) => {
  if (!['EMPLOYEE','MANAGER'].includes(viewer.role)) return Employee.find({ isActive: true }).distinct("_id");
  const own = await Employee.findOne({ user: viewer.id, isActive: true }).select("_id");
  if (!own) return [];
  return viewer.role === "EMPLOYEE" ? [own._id] : Employee.find({ isActive: true, $or: [{ _id: own._id }, { reportingManager: own._id }] }).distinct("_id");
};
const scopedEmployee = async (id: string, viewer: Viewer) => {
  const ids = await employeeIds(viewer); if (!ids.some((value) => value.toString() === id)) throw new AppError("Employee is outside your permitted scope", 403);
  const employee = await Employee.findById(id); if (!employee) throw new AppError("Employee not found", 404); return employee;
};
const ownEmployee = async (viewer: Viewer) => { const employee = await Employee.findOne({ user: viewer.id, isActive: true }); if (!employee) throw new AppError("Employee profile not found", 404); return employee; };
const managementOnly = (viewer: Viewer) => { if (viewer.role === "EMPLOYEE") throw new AppError("This action is reserved for managers", 403); };

export const listEmployees = async (viewer: Viewer) => Employee.find({ _id: { $in: await employeeIds(viewer) }, isActive: true }).select("firstName lastName employeeId officialEmail").sort({ firstName: 1 }).lean();
export const listWeekly = async (employee: string | undefined, viewer: Viewer) => { const ids = await employeeIds(viewer); const filter = employee ? { employee: (await scopedEmployee(employee, viewer))._id } : { employee: { $in: ids } }; return WeeklyUpdate.find(filter).populate("employee", "firstName lastName employeeId").populate("acknowledgedBy", "name").sort({ weekStart: -1 }).limit(24).lean(); };
export const saveWeekly = async (input: { weekStart: Date; accomplishments: string[]; currentPriorities: string[]; blockers: { description: string; category: string; external: boolean }[]; helpNeeded?: string; nextWeekPlan?: string }, viewer: Viewer) => { const employee = await ownEmployee(viewer); const week = new Date(input.weekStart); week.setUTCHours(0,0,0,0); const day = (week.getUTCDay() + 6) % 7; week.setUTCDate(week.getUTCDate() - day); const item = await WeeklyUpdate.findOneAndUpdate({ employee: employee._id, weekStart: week }, { $set: { ...input, weekStart: week, employee: employee._id, submittedAt: new Date() }, $unset: { acknowledgedBy: 1, acknowledgedAt: 1 } }, { upsert: true, new: true, runValidators: true }); await writeAudit({ user: viewer.id, action: "WEEKLY_UPDATE_SUBMITTED", entityType: "WeeklyUpdate", entityId: item.id }); return item; };
export const acknowledgeWeekly = async (id: string, managerComment: string | undefined, viewer: Viewer) => { managementOnly(viewer); const item = await WeeklyUpdate.findById(id); if (!item) throw new AppError("Weekly update not found", 404); const employee=await scopedEmployee(item.employee.toString(), viewer); item.managerComment = managerComment; item.acknowledgedBy = item.acknowledgedBy ?? (viewer.id as never); item.acknowledgedAt = new Date(); await item.save(); await notify({recipient:employee.user.toString(),type:"WEEKLY_UPDATE_ACKNOWLEDGED",title:"Your weekly update was reviewed",body:managerComment||"Your manager acknowledged your update and support needs.",entityType:"WeeklyUpdate",entityId:item.id}); return item; };
export const listCheckIns = async (employee: string | undefined, viewer: Viewer) => { const ids = await employeeIds(viewer); const filter = employee ? { employee: (await scopedEmployee(employee, viewer))._id } : { employee: { $in: ids } }; return OneToOne.find(filter).populate("employee", "firstName lastName employeeId").populate("manager", "name").sort({ meetingDate: -1 }).limit(24).lean(); };
export const createCheckIn = async (input: Record<string, unknown> & { employee: string }, viewer: Viewer) => { managementOnly(viewer); const employee = await scopedEmployee(input.employee, viewer); const item = await OneToOne.create({ ...input, employee: employee._id, manager: viewer.id }); await writeAudit({ user: viewer.id, action: "ONE_TO_ONE_RECORDED", entityType: "OneToOne", entityId: item.id }); await notify({recipient:employee.user.toString(),type:"ONE_TO_ONE_RECORDED",title:"A 1:1 check-in was recorded",body:"Review the agreed actions and add your response or context.",entityType:"OneToOne",entityId:item.id}); return item; };
export const respondCheckIn = async (id: string, employeeResponse: string, viewer: Viewer) => { const employee = await ownEmployee(viewer); const item = await OneToOne.findOne({ _id: id, employee: employee._id }); if (!item) throw new AppError("Check-in not found", 404); item.employeeResponse = employeeResponse; item.acknowledgedAt = new Date(); await item.save(); return item; };
export const listReviews = async (employee: string | undefined, viewer: Viewer) => { const ids = await employeeIds(viewer); const filter = employee ? { employee: (await scopedEmployee(employee, viewer))._id } : { employee: { $in: ids } }; return ContributionReview.find(filter).populate("employee", "firstName lastName employeeId").populate("managerReview.reviewedBy", "name").sort({ period: -1 }).limit(24).lean(); };
export const submitSelfReview = async (input: { period: string; accomplishments: string; impact: string; collaboration: string; growth: string; challenges?: string; evidenceLinks: string[] }, viewer: Viewer) => { const employee = await ownEmployee(viewer); const item = await ContributionReview.findOneAndUpdate({ employee: employee._id, period: input.period }, { $set: { selfReview: { ...input, submittedAt: new Date() }, status: "SELF_SUBMITTED" } }, { upsert: true, new: true, runValidators: true }); return item; };
export const submitManagerReview = async (id: string, input: { ratings: Record<ContributionArea, number>; comment: string }, viewer: Viewer) => { managementOnly(viewer); const item = await ContributionReview.findById(id); if (!item) throw new AppError("Contribution review not found", 404); const employee=await scopedEmployee(item.employee.toString(), viewer); item.managerReview = { ...input, reviewedBy: viewer.id as never, reviewedAt: new Date() }; item.status = "MANAGER_REVIEWED"; await item.save(); await notify({recipient:employee.user.toString(),type:"CONTRIBUTION_REVIEW_READY",title:`Contribution review ready for ${item.period}`,body:"Review the evidence and manager comments, then add your response.",entityType:"ContributionReview",entityId:item.id}); return item; };
export const respondReview = async (id: string, employeeResponse: string, viewer: Viewer) => { const employee = await ownEmployee(viewer); const item = await ContributionReview.findOne({ _id: id, employee: employee._id }); if (!item) throw new AppError("Contribution review not found", 404); item.employeeResponse = employeeResponse; item.acknowledgedAt = new Date(); item.status = "ACKNOWLEDGED"; await item.save(); return item; };
export const listSnapshots = async (employee: string | undefined, viewer: Viewer) => { const ids = await employeeIds(viewer); const filter = employee ? { employee: (await scopedEmployee(employee, viewer))._id } : { employee: { $in: ids } }; return ContributionSnapshot.find(filter).populate("employee", "firstName lastName employeeId").sort({ period: -1 }).limit(24).lean(); };

export const calculateSnapshot = async (input: { employee: string; period: string }, viewer: Viewer) => {
  const employee = await scopedEmployee(input.employee, viewer); const { start, end } = monthBounds(input.period);
  const user = await User.findById(employee.user).select("role"); const role = user ? await Role.findById(user.role).select("name").lean() : null; const roleName = role?.name ?? "EMPLOYEE";
  const [tasks, kpis, goals, weekly, recognitionCount, trainingCount, skillCount, review, openTasks, salesLeads, salesRevenue, salesTargets] = await Promise.all([
    Task.find({ assignedEmployee: employee._id, isActive: true, $or: [{ completionDate: { $gte: start, $lt: end } }, { deadline: { $gte: start, $lt: end } }] }).lean(),
    EmployeeKPI.find({ employee: employee._id, period: input.period }).lean(), Goal.find({ employee: employee._id, period: input.period, isActive: true }).lean(),
    WeeklyUpdate.find({ employee: employee._id, weekStart: { $gte: start, $lt: end } }).lean(), Recognition.countDocuments({ employee: employee._id, awardedAt: { $gte: start, $lt: end } }),
    EmployeeTraining.countDocuments({ employee: employee._id, status: "COMPLETED", completedAt: { $gte: start, $lt: end } }), EmployeeSkill.countDocuments({ employee: employee._id, verificationStatus: { $in: ["VERIFIED","EXPERT_VERIFIED"] }, updatedAt: { $gte: start, $lt: end } }),
    ContributionReview.findOne({ employee: employee._id, period: input.period }).lean(), Task.find({ assignedEmployee: employee._id, isActive: true, status: { $nin: ["COMPLETED","CANCELLED"] } }).lean(),
    SalesLead.find({ ownerEmployee: employee._id, createdAt: { $gte: start, $lt: end } }).select("status").lean(),
    SalesRevenueTransaction.find({ employee: employee._id, transactionDate: { $gte: start, $lt: end } }).select("amount").lean(),
    SalesTarget.find({ employee: employee._id, isLatest: true, status: { $in: ["ACTIVE","CLOSED"] }, periodStart: { $lt: end }, periodEnd: { $gte: start } }).select("revenueTarget leadTarget conversionTarget customerAcquisitionTarget").lean()
  ]);
  const completed = tasks.filter((task) => task.status === "COMPLETED"); const reviewed = completed.filter((task) => task.qualityRating);
  const objective: Partial<Record<ContributionArea, { score: number; explanation: string }>> = {};
  if (tasks.length) objective.delivery = { score: completed.length / tasks.length * 100, explanation: `${completed.length} of ${tasks.length} due or completed tasks delivered` };
  const revenue = salesRevenue.reduce((sum, item) => sum + item.amount, 0); const revenueTarget = salesTargets.reduce((sum, item) => sum + item.revenueTarget, 0); const leadTarget = salesTargets.reduce((sum, item) => sum + (item.leadTarget ?? 0), 0); const convertedLeads = salesLeads.filter((lead) => lead.status === "CONVERTED").length; const conversionTarget = salesTargets.find((item) => item.conversionTarget != null)?.conversionTarget; const conversionRate = salesLeads.length ? convertedLeads / salesLeads.length * 100 : 0;
  const salesDelivery: number[] = []; if (revenueTarget) salesDelivery.push(clamp(revenue / revenueTarget * 100)); if (leadTarget) salesDelivery.push(clamp(salesLeads.length / leadTarget * 100));
  if (salesDelivery.length) { const score=salesDelivery.reduce((sum,value)=>sum+value,0)/salesDelivery.length; objective.delivery = objective.delivery ? { score:(objective.delivery.score+score)/2, explanation:`${objective.delivery.explanation}; sales target attainment ${score.toFixed(0)}%` } : { score, explanation:`Sales target attainment ${score.toFixed(0)}% from ${salesLeads.length} leads and ${salesRevenue.length} revenue records` }; }
  if (reviewed.length) { const average = reviewed.reduce((sum, task) => sum + (task.qualityRating ?? 0), 0) / reviewed.length * 20; const rework = completed.reduce((sum, task) => sum + task.reopenCount, 0); objective.quality = { score: clamp(average - Math.min(20, rework * 5)), explanation: `${average.toFixed(0)}% review quality across ${reviewed.length} tasks; ${rework} reopen events` }; }
  if (conversionTarget && salesLeads.length) { const score=clamp(conversionRate/conversionTarget*100); objective.quality = objective.quality ? { score:(objective.quality.score+score)/2, explanation:`${objective.quality.explanation}; ${conversionRate.toFixed(1)}% sales conversion against ${conversionTarget}% target` } : { score, explanation:`${convertedLeads} of ${salesLeads.length} leads converted (${conversionRate.toFixed(1)}% against ${conversionTarget}% target)` }; }
  const reliabilityTasks = completed.filter(reliabilityEligible); if (reliabilityTasks.length || weekly.length) { const onTime = reliabilityTasks.length ? reliabilityTasks.filter((task) => task.completionDate && task.completionDate <= task.deadline).length / reliabilityTasks.length * 100 : 0; const nowForPeriod=new Date(); const elapsedEnd=nowForPeriod<end&&nowForPeriod>=start?nowForPeriod:end; const expected=Math.max(1,Math.min(5,Math.ceil((elapsedEnd.getTime()-start.getTime())/(7*86400000)))); const consistency = Math.min(100, weekly.length / expected * 100); objective.reliability = { score: reliabilityTasks.length ? onTime * .75 + consistency * .25 : consistency, explanation: `${onTime.toFixed(0)}% on-time excluding external blockers; ${weekly.length}/${expected} weekly updates` }; }
  const impactParts: number[] = []; if (kpis.length) impactParts.push(kpis.reduce((sum, item) => sum + Math.min(100, item.achievement), 0) / kpis.length); if (goals.length) impactParts.push(goals.reduce((sum, item) => sum + item.progress, 0) / goals.length); const impactEvidence = completed.filter((task) => task.businessImpact).length; if (impactEvidence) impactParts.push(Math.min(100, impactEvidence / Math.max(1, completed.length) * 100)); if (revenueTarget) impactParts.push(clamp(revenue/revenueTarget*100)); if (impactParts.length) objective.impact = { score: impactParts.reduce((a,b) => a+b,0) / impactParts.length, explanation: `${kpis.length} KPI results, ${goals.length} goals, ${impactEvidence} documented task outcomes${revenueTarget ? ` and ${revenue.toFixed(0)} of ${revenueTarget.toFixed(0)} sales revenue` : ""}` };
  if (recognitionCount) objective.collaboration = { score: Math.min(100, recognitionCount * 25), explanation: `${recognitionCount} evidence-backed recognitions in this period` };
  if (trainingCount || skillCount) objective.growth = { score: Math.min(100, trainingCount * 33 + skillCount * 25), explanation: `${trainingCount} completed trainings and ${skillCount} newly verified skills` };
  const baseWeights: Record<ContributionArea, number> = roleName === "MANAGER" ? { delivery:20, quality:20, reliability:15, impact:20, collaboration:15, growth:10 } : { delivery:25, quality:25, reliability:15, impact:15, collaboration:10, growth:10 };
  const labels: Record<ContributionArea,string> = { delivery:"Delivery", quality:"Quality", reliability:"Reliability", impact:"Business impact", collaboration:"Collaboration", growth:"Growth" };
  const raw = CONTRIBUTION_AREAS.map((key) => { const manager = review?.managerReview?.ratings?.[key]; const evidence = objective[key]; const available = !!evidence || !!manager; const score = evidence && manager ? evidence.score * .7 + manager * 20 * .3 : evidence?.score ?? (manager ? manager * 20 : 0); return { key, label: labels[key], score: clamp(score), configuredWeight: baseWeights[key], available, explanation: evidence ? `${evidence.explanation}${manager ? `; manager rating ${manager}/5 (30% of this area)` : ""}` : manager ? `Manager evidence rating ${manager}/5` : "No evidence recorded; excluded from the total" }; });
  const normalized=normalizeContributionAreas(raw.map((item)=>({...item,score:Number(item.score.toFixed(1))}))); const availableWeight=normalized.evidenceWeight; const components=normalized.components; const totalScore=normalized.totalScore; const classification = totalScore >= 85 ? "OUTSTANDING" : totalScore >= 70 ? "STRONG" : totalScore >= 55 ? "SOLID" : totalScore >= 40 ? "DEVELOPING" : "INSUFFICIENT_EVIDENCE";
  const now = new Date(); const overdue = openTasks.filter((task) => task.deadline < now).length; const openHours = openTasks.reduce((sum,task) => sum + Math.max(0, task.estimatedHours - (task.actualHours ?? 0)),0); const longBlockers = openTasks.filter((task) => task.status === "BLOCKED" && task.blocker && now.getTime() - task.blocker.startedAt.getTime() > 7*86400000).length;
  const alerts: { type:string; severity:"INFO"|"ATTENTION"|"HIGH"; title:string; detail:string; private:boolean }[] = [];
  if (openHours > 45) alerts.push({ type:"WORKLOAD", severity:"HIGH", title:"High estimated workload", detail:`${openHours.toFixed(0)} remaining estimated hours. Review priorities or redistribute work.`, private:true });
  if (overdue) alerts.push({ type:"OVERDUE", severity: overdue > 3 ? "HIGH" : "ATTENTION", title:"Overdue work needs support", detail:`${overdue} active tasks are overdue. Discuss causes and remove blockers.`, private:true });
  if (longBlockers) alerts.push({ type:"BLOCKER", severity:"ATTENTION", title:"Long-running blockers", detail:`${longBlockers} blockers have remained open for more than seven days.`, private:true });
  if (!openTasks.length) alerts.push({ type:"ALLOCATION", severity:"INFO", title:"No active assignment", detail:"Confirm priorities so the employee has clear, meaningful work.", private:true });
  const previous=await ContributionSnapshot.findOne({employee:employee._id,period:{$lt:input.period}}).sort({period:-1}).select("totalScore period").lean(); if(previous&&previous.totalScore-totalScore>15) alerts.push({type:"TREND",severity:"ATTENTION",title:"Contribution trend needs a conversation",detail:`The score moved down ${Number(previous.totalScore-totalScore).toFixed(0)} points since ${previous.period}. Check changing priorities, workload and support needs before drawing conclusions.`,private:true});
  const snapshot = await ContributionSnapshot.findOneAndUpdate({ employee: employee._id, period: input.period }, { $set: { role: roleName, totalScore, classification, evidenceCoverage: availableWeight, components, alerts, calculatedBy: viewer.id, calculatedAt: new Date() } }, { upsert:true, new:true, runValidators:true });
  await writeAudit({ user: viewer.id, action:"CONTRIBUTION_SNAPSHOT_CALCULATED", entityType:"ContributionSnapshot", entityId:snapshot.id, newValue:{ employee:employee.employeeId, period:input.period, totalScore, evidenceCoverage:availableWeight } }); return snapshot;
};
