/* eslint-disable @typescript-eslint/no-explicit-any, no-control-regex */
import { createHash } from "node:crypto";
import readXlsxFile from "read-excel-file/node";
import { Employee } from "../models/Employee.js";
import { Task } from "../models/Task.js";
import { SalesLead } from "../models/SalesLead.js";
import { SalesActivity } from "../models/SalesActivity.js";
import { LeadImportBatch } from "../models/LeadImportBatch.js";
import { LeadWorkItem, type LeadWorkStatus } from "../models/LeadWorkItem.js";
import { LeadWorkActivity } from "../models/LeadWorkActivity.js";
import { AppError } from "../utils/AppError.js";
import { createTask } from "./workService.js";
import { getViewerHierarchyScope, assertEmployeeInScope } from "./hierarchyService.js";
import { writeAudit } from "./auditService.js";
import type { RoleName } from "@mobius-ems/shared";

const MAX_ROWS = 5000; const MAX_CELL = 5000;
const clean = (value: unknown) => String(value ?? "").replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/g, "").trim().slice(0, MAX_CELL);
const normalizeEmail = (v: string) => v.trim().toLowerCase();
const csvRows = (text: string): string[][] => { const rows: string[][] = []; let row: string[] = [], value = "", quoted = false; for (let i=0;i<text.length;i++) { const c=text[i]; if (c==='"') { if (quoted && text[i+1]==='"') { value+='"'; i++; } else quoted=!quoted; } else if (c===',' && !quoted) { row.push(value); value=""; } else if ((c==='\n'||c==='\r') && !quoted) { if (c==='\r'&&text[i+1]==='\n') i++; row.push(value); if (row.some((x)=>x.trim())) rows.push(row); row=[]; value=""; } else value+=c; } row.push(value); if(row.some((x)=>x.trim())) rows.push(row); return rows; };
const uniqueHeaders = (row: unknown[]) => row.map((v,i)=>clean(v)||`Column ${i+1}`).map((h,i,a)=>a.indexOf(h)===i?h:`${h} (${i+1})`);
const suggested = (h: string) => { const n=h.toLowerCase().replace(/[^a-z0-9]/g,""); if(/^(name|customername|leadname|contactname)$/.test(n)) return "name"; if(/mobile|phone|contactnumber/.test(n)) return "phone"; if(/email/.test(n)) return "email"; if(/company|organisation|organization/.test(n)) return "companyName"; if(/city|location|market/.test(n)) return "market"; if(/source/.test(n)) return "source"; if(/requirement|remark|note/.test(n)) return "notes"; if(/value|amount/.test(n)) return "estimatedValue"; return "custom"; };

export const previewLeadFile = async (file: Express.Multer.File, sheet?: string) => {
  let matrix: unknown[][]; let sheets: string[] = [];
  if (file.originalname.toLowerCase().endsWith(".csv")) matrix = csvRows(file.buffer.toString("utf8"));
  else { const workbook = await readXlsxFile(file.buffer); sheets = workbook.map((item) => item.sheet); const selected = workbook.find((item) => item.sheet === sheet) ?? workbook[0]; if (!selected) throw new AppError("The workbook has no worksheets", 422); matrix = selected.data as unknown[][]; }
  if (matrix.length < 2) throw new AppError("The file must contain a header and at least one lead row", 422, "EMPTY_LEAD_FILE");
  if (matrix.length-1 > MAX_ROWS) throw new AppError(`Lead files are limited to ${MAX_ROWS} rows`, 422, "LEAD_ROW_LIMIT");
  const columns=uniqueHeaders(matrix[0]!); const rows=matrix.slice(1).map((cells,index)=>({ rowNumber:index+2, values:Object.fromEntries(columns.map((h,i)=>[h,clean(cells[i])])) })).filter((r)=>Object.values(r.values).some(Boolean));
  return { fileName: clean(file.originalname), fileHash:createHash("sha256").update(file.buffer).digest("hex"), sheets, selectedSheet:sheet||sheets[0], columns, suggestedMapping:Object.fromEntries(columns.map((h)=>[h,suggested(h)])), totalRows:matrix.length-1, emptyRows:matrix.length-1-rows.length, rows:rows.slice(0,200), allRows:rows };
};

type Actor={id:string;role:string}; type CommitInput={ idempotencyKey:string; fileName:string; fileHash:string; sheetName?:string; task:{name:string;description?:string;project:string;assignedEmployee:string;priority:"LOW"|"MEDIUM"|"HIGH"|"CRITICAL";complexity:"EASY"|"MEDIUM"|"HARD"|"VERY_HARD";estimatedHours:number;startDate?:Date;deadline:Date;reviewer?:string}; mapping:Record<string,string>; rows:Array<{rowNumber:number;values:Record<string,string>;excluded?:boolean}> };
export const commitLeadImport = async (input:CommitInput, actor:Actor) => {
  const existing=await LeadImportBatch.findOne({idempotencyKey:input.idempotencyKey}).populate("task"); if(existing) return {batch:existing,task:existing.task,idempotent:true};
  const scope=await getViewerHierarchyScope(actor as {id:string;role:RoleName}); assertEmployeeInScope(scope,input.task.assignedEmployee,"Employee is outside your permitted scope");
  const assignee=await Employee.findOne({_id:input.task.assignedEmployee,isActive:true}).select("user firstName lastName"); if(!assignee) throw new AppError("Assignee not found",404);
  const usable=input.rows.filter((r)=>!r.excluded).slice(0,MAX_ROWS); if(!usable.length) throw new AppError("Select at least one valid lead",422);
  const get=(r:typeof usable[number],field:string)=>clean(Object.entries(input.mapping).find(([,v])=>v===field)?.[0] ? r.values[Object.entries(input.mapping).find(([,v])=>v===field)![0]] : "");
  const invalid=usable.filter((r)=>!get(r,"name")&&!get(r,"phone")&&!get(r,"email")); if(invalid.length) throw new AppError(`${invalid.length} rows have no lead name, phone, or email`,422,"INVALID_LEAD_ROWS");
  const task=await createTask({...input.task},actor.id); let duplicates=0; const items=[];
  for(const row of usable){ const phone=get(row,"phone"),email=normalizeEmail(get(row,"email")); const or:any[]=[]; if(phone) or.push({phone}); if(email) or.push({email}); let lead=or.length?await SalesLead.findOne({$or:or}):null; if(lead) duplicates++; else lead=await SalesLead.create({name:get(row,"name")||get(row,"companyName")||phone||email,phone,email:email||undefined,companyName:get(row,"companyName")||undefined,notes:get(row,"notes")||undefined,market:get(row,"market")||undefined,source:get(row,"source")||undefined,estimatedValue:Number(get(row,"estimatedValue"))||0,ownerEmployee:assignee._id,status:"NEW"}); items.push({task:task._id,lead:lead._id,assignedEmployee:assignee._id,sourceRow:row.rowNumber,originalData:row.values}); }
  await LeadWorkItem.insertMany(items);
  const batch=await LeadImportBatch.create({task:task._id,fileName:input.fileName,fileHash:input.fileHash,idempotencyKey:input.idempotencyKey,importedBy:actor.id,assignedEmployee:assignee._id,sheetName:input.sheetName,totalRows:input.rows.length,importedRows:items.length,rejectedRows:input.rows.length-items.length,duplicateLinks:duplicates,columns:Object.keys(input.mapping),mapping:input.mapping});
  await writeAudit({user:actor.id,action:"LEAD_LIST_IMPORTED",entityType:"Task",entityId:task.id,newValue:{rows:items.length,duplicates,fileName:input.fileName}});
  return {batch,task,idempotent:false};
};

const assertAccess=async(taskId:string,actor:Actor,write=false)=>{const task=await Task.findOne({_id:taskId,isActive:true});if(!task)throw new AppError("Task not found",404);const employee=await Employee.findOne({user:actor.id,isActive:true}).select("_id");if(!["SUPER_ADMIN","HR_ADMIN"].includes(actor.role)){const scope=await getViewerHierarchyScope(actor as {id:string;role:RoleName});assertEmployeeInScope(scope,task.assignedEmployee,"Task is outside your permitted scope");}if(write&&actor.role==="HR_ADMIN")throw new AppError("HR access is read-only",403);return {task,employee};};
export const listWorkItems=async(taskId:string,q:any,actor:Actor)=>{await assertAccess(taskId,actor);const page=Math.max(1,Number(q.page)||1),limit=Math.min(100,Math.max(1,Number(q.limit)||25));const filter:any={task:taskId};if(q.status)filter.status=q.status;if(q.followUp==="overdue")filter.nextFollowUpAt={$lt:new Date()};if(q.search){const leads=await SalesLead.find({$or:[{name:{$regex:String(q.search),$options:"i"}},{companyName:{$regex:String(q.search),$options:"i"}},{phone:{$regex:String(q.search).replace(/[$()*+.?[\]^{|}]/g,"\\$&")}}]}).select("_id").limit(500);filter.lead={$in:leads.map(x=>x._id)};}const [items,total]=await Promise.all([LeadWorkItem.find(filter).populate("lead","name phone email companyName market source status notes").populate("assignedEmployee","firstName lastName employeeId").sort({nextFollowUpAt:1,updatedAt:-1}).skip((page-1)*limit).limit(limit).lean(),LeadWorkItem.countDocuments(filter)]);return {items,page,limit,total,pages:Math.ceil(total/limit)};};
export const workItemDetail=async(taskId:string,id:string,actor:Actor)=>{await assertAccess(taskId,actor);const item=await LeadWorkItem.findOne({_id:id,task:taskId}).populate("lead").populate("assignedEmployee","firstName lastName employeeId").lean();if(!item)throw new AppError("Lead work item not found",404);const activities=await LeadWorkActivity.find({workItem:id}).populate("performedBy","name").sort({createdAt:-1}).lean();return {item,activities};};
export const addActivity=async(taskId:string,id:string,input:{interactionType:any;outcome:any;status:LeadWorkStatus;note:string;nextFollowUpAt?:Date;version:number},actor:Actor)=>{const {employee}=await assertAccess(taskId,actor,true);const item=await LeadWorkItem.findOne({_id:id,task:taskId});if(!item)throw new AppError("Lead work item not found",404);if(actor.role==="EMPLOYEE"&&item.assignedEmployee.toString()!==employee?._id.toString())throw new AppError("This lead is assigned to another employee",403);if(item.version!==input.version)throw new AppError("This lead changed since you opened it. Refresh and try again.",409,"STALE_LEAD_WORK_ITEM");if(input.status==="FOLLOW_UP"&&!input.nextFollowUpAt)throw new AppError("Next follow-up is required",422);const from=item.status,now=new Date();item.status=input.status;item.attemptCount+=1;item.lastAttemptAt=now;item.lastActivityAt=now;item.latestNote=input.note;item.nextFollowUpAt=input.nextFollowUpAt;item.version+=1;await item.save();await LeadWorkActivity.create({task:item.task,workItem:item._id,lead:item.lead,assignedEmployee:item.assignedEmployee,performedBy:actor.id,interactionType:input.interactionType,outcome:input.outcome,fromStatus:from,toStatus:input.status,note:input.note,nextFollowUpAt:input.nextFollowUpAt});const lead=await SalesLead.findById(item.lead);if(lead&&lead.status==="NEW"&&["CONNECTED","FOLLOW_UP","INTERESTED","QUALIFIED"].includes(input.status))lead.status=input.status==="QUALIFIED"?"QUALIFIED":"CONTACTED";if(lead&&lead.status!=="CONVERTED")await lead.save();await SalesActivity.create({entityType:"leads",entityId:item.lead,type:"CALL_LOG",content:input.note,metadata:{task:taskId,workItem:id,interactionType:input.interactionType,outcome:input.outcome,status:input.status,nextFollowUpAt:input.nextFollowUpAt},performedBy:actor.id});return item;};
export const leadSummary=async(taskId:string,actor:Actor)=>{await assertAccess(taskId,actor);const rows=await LeadWorkItem.aggregate([{$match:{task:new (await import("mongoose")).Types.ObjectId(taskId)}},{$group:{_id:"$status",count:{$sum:1},attempts:{$sum:"$attemptCount"},lastActivity:{$max:"$lastActivityAt"}}}]);const total=rows.reduce((s,r)=>s+r.count,0),attempts=rows.reduce((s,r)=>s+r.attempts,0),untouched=rows.find(r=>r._id==="NOT_STARTED")?.count||0;return {total,worked:total-untouched,untouched,attempts,statuses:Object.fromEntries(rows.map(r=>[r._id,r.count])),lastActivity:rows.reduce((d,r)=>!d||r.lastActivity>d?r.lastActivity:d,null)};};
const csvCell=(v:unknown)=>{let s=String(v??"");if(/^[=+\-@]/.test(s))s="'"+s;return `"${s.replace(/"/g,'""')}"`;};
export const markLeadTasks=async<T extends {_id:unknown}>(tasks:T[])=>{const batches=await LeadImportBatch.find({task:{$in:tasks.map(t=>t._id)}}).select("task").lean();const ids=new Set(batches.map(b=>b.task.toString()));return tasks.map(task=>({...task,taskType:ids.has(String(task._id))?"LEAD_LIST":"STANDARD"}));};
export const exportWorkItems=async(taskId:string,actor:Actor)=>{await assertAccess(taskId,actor);const items=await LeadWorkItem.find({task:taskId}).populate("lead","name phone email companyName status").populate("assignedEmployee","firstName lastName employeeId").lean();const original=[...new Set(items.flatMap(i=>Object.keys(i.originalData||{})))];const headers=[...original,"Assigned Employee","Operational Status","CRM Status","Attempts","Latest Note","Last Activity","Next Follow-up","Created At"];const lines=[headers.map(csvCell).join(","),...items.map((i:any)=>[...original.map(h=>i.originalData?.[h]),`${i.assignedEmployee?.firstName||""} ${i.assignedEmployee?.lastName||""}`.trim(),i.status,i.lead?.status,i.attemptCount,i.latestNote,i.lastActivityAt,i.nextFollowUpAt,i.createdAt].map(csvCell).join(","))];return lines.join("\r\n");};
