import type { FilterQuery, Types } from "mongoose";
import type { SessionUser } from "@mobius-ems/shared";
import { SalesLead, type SalesLeadDocument } from "../models/SalesLead.js"; import { SalesCustomer } from "../models/SalesCustomer.js"; import { SalesOpportunity } from "../models/SalesOpportunity.js"; import { SalesTarget } from "../models/SalesTarget.js"; import { SalesRevenueTransaction } from "../models/SalesRevenueTransaction.js"; import { ChannelPartner } from "../models/ChannelPartner.js"; import { EmployeeTerritoryAssignment } from "../models/EmployeeTerritoryAssignment.js"; import { SalesConfiguration } from "../models/SalesConfiguration.js"; import { Employee } from "../models/Employee.js"; import { SalesTerritory } from "../models/SalesTerritory.js";
import { calculateCapacity, calculateEstimatedOpportunityLost, calculateOpportunityScore, percentage, weightedPipelineValue } from "./salesMath.js"; import { assertSalesEmployeeScope, assertSalesGeoScope, assertSalesTerritoryScope, resolveSalesScope, type ResolvedSalesScope } from "./salesScopeService.js"; import { descendantGeoIds } from "./geoService.js";

const monthPeriod = (now = new Date()) => ({ start: new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), 1)), end: new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth() + 1, 1)) });
const defaultConfiguration = { defaultLeadCapacityPerEmployee: 300, responseSlaMinutes: 240, healthyConversionRate: 15, opportunityWeights: { demand: 20, coverageGap: 25, customerWhiteSpace: 15, pipelinePotential: 15, growth: 10, conversionPotential: 15 } };
type AnalyticsOptions = { employeeId?: string; territoryIds?: Types.ObjectId[]; geoIds?: Types.ObjectId[]; start?: Date; end?: Date };
const dateFilter = (start: Date, end: Date) => ({ $gte: start, $lt: end });

const analyticsForScope = async (scope: ResolvedSalesScope, options: AnalyticsOptions = {}) => {
  const period = options.start && options.end ? { start: options.start, end: options.end } : monthPeriod();
  const employeeIds = options.employeeId ? scope.allowedEmployeeIds.filter((id) => id.toString() === options.employeeId) : scope.allowedEmployeeIds;
  const territoryIds = options.territoryIds ?? scope.allowedTerritoryIds;
  const common: Record<string, unknown> = { ownerEmployee: { $in: employeeIds }, territory: { $in: territoryIds } }; if (options.geoIds) common.geoNode = { $in: options.geoIds };
  const leadFilter: FilterQuery<SalesLeadDocument> = { ...common, createdAt: dateFilter(period.start, period.end) };
  const revenueFilter: Record<string, unknown> = { employee: { $in: employeeIds }, territory: { $in: territoryIds }, transactionDate: dateFilter(period.start, period.end) }; if (options.geoIds) revenueFilter.geoNode = { $in: options.geoIds };
  const opportunityFilter: Record<string, unknown> = { ownerEmployee: { $in: employeeIds }, territory: { $in: territoryIds }, status: "OPEN" }; if (options.geoIds) opportunityFilter.geoNode = { $in: options.geoIds };
  const targetFilter: Record<string, unknown> = { status: { $in: ["ACTIVE", "CLOSED"] }, periodStart: { $lt: period.end }, periodEnd: { $gte: period.start }, $or: [{ employee: { $in: employeeIds } }, ...(territoryIds.length ? [{ territory: { $in: territoryIds } }] : [])] };
  const previousStart = new Date(period.start); previousStart.setUTCMonth(previousStart.getUTCMonth() - 1); const previousRevenueFilter = { ...revenueFilter, transactionDate: dateFilter(previousStart, period.start) };
  const [leads, customers, opportunities, targets, revenues, previousRevenue, employeeCount, partnerCount, assignments, storedConfig] = await Promise.all([
    SalesLead.find(leadFilter).select("status estimatedValue firstResponseAt createdAt currency").lean(), SalesCustomer.find({ ...common, status: "ACTIVE" }).select("_id").lean(), SalesOpportunity.find(opportunityFilter).select("estimatedValue probability currency").lean(), SalesTarget.find(targetFilter).select("revenueTarget currency").lean(), SalesRevenueTransaction.find(revenueFilter).select("amount currency transactionDate").lean(), SalesRevenueTransaction.find(previousRevenueFilter).select("amount").lean(), Employee.countDocuments({ _id: { $in: employeeIds }, isActive: true, status: { $in: ["ACTIVE", "ONBOARDING"] } }), ChannelPartner.countDocuments({ territory: { $in: territoryIds }, ...(options.geoIds ? { geoNode: { $in: options.geoIds } } : {}), status: "ACTIVE" }), EmployeeTerritoryAssignment.find({ employee: { $in: employeeIds }, territory: { $in: territoryIds }, isActive: true, effectiveFrom: { $lt: period.end }, $or: [{ effectiveTo: { $exists: false } }, { effectiveTo: { $gte: period.start } }] }).select("leadCapacityPerMonth").lean(), SalesConfiguration.findOne({ key: "DEFAULT" }).lean(),
  ]);
  const config = storedConfig ?? defaultConfiguration; const leadCount = leads.length; const qualifiedLeadCount = leads.filter((lead) => ["QUALIFIED", "CONVERTED"].includes(lead.status)).length; const convertedLeadCount = leads.filter((lead) => lead.status === "CONVERTED").length; const actualRevenue = revenues.reduce((sum, item) => sum + item.amount, 0); const targetRevenue = targets.reduce((sum, item) => sum + item.revenueTarget, 0); const pipelineValue = opportunities.reduce((sum, item) => sum + item.estimatedValue, 0); const weightedPipeline = weightedPipelineValue(opportunities); const responded = leads.filter((lead) => lead.firstResponseAt); const avgFirstResponseMinutes = responded.length ? Number((responded.reduce((sum, lead) => sum + (lead.firstResponseAt!.getTime() - (lead.createdAt as Date).getTime()) / 60000, 0) / responded.length).toFixed(2)) : 0; const now = new Date(); const delayed = leads.filter((lead) => lead.firstResponseAt ? (lead.firstResponseAt.getTime() - (lead.createdAt as Date).getTime()) / 60000 > config.responseSlaMinutes : now.getTime() - (lead.createdAt as Date).getTime() > config.responseSlaMinutes * 60000); const averageCapacity = assignments.length ? assignments.reduce((sum, assignment) => sum + (assignment.leadCapacityPerMonth ?? config.defaultLeadCapacityPerEmployee), 0) / assignments.length : config.defaultLeadCapacityPerEmployee; const capacity = calculateCapacity(leadCount, employeeCount, averageCapacity); const conversionRate = percentage(convertedLeadCount, leadCount); const previousActual = previousRevenue.reduce((sum, item) => sum + item.amount, 0); const growthScore = previousActual ? Math.min(100, Math.max(0, percentage(actualRevenue - previousActual, previousActual) + 50)) : actualRevenue ? 60 : 0; const opportunityInputs = { leadDemandScore: Math.min(100, percentage(leadCount, Math.max(1, employeeCount * averageCapacity))), coverageGapScore: 100 - capacity.coveragePercentage, customerWhiteSpaceScore: leadCount ? Math.max(0, 100 - percentage(customers.length, leadCount)) : 0, pipelinePotentialScore: targetRevenue ? Math.min(100, percentage(weightedPipeline, targetRevenue)) : weightedPipeline ? 60 : 0, growthScore, conversionPotentialScore: config.healthyConversionRate ? Math.min(100, Math.max(0, percentage(config.healthyConversionRate - conversionRate, config.healthyConversionRate))) : 0 }; const opportunity = calculateOpportunityScore(opportunityInputs, config.opportunityWeights); const averageDealValue = convertedLeadCount ? actualRevenue / convertedLeadCount : 0; const lost = calculateEstimatedOpportunityLost(delayed.length, config.healthyConversionRate, conversionRate, averageDealValue);
  return { generatedAt: new Date().toISOString(), scope: scope.level, period: { start: period.start.toISOString(), end: period.end.toISOString() }, currency: revenues[0]?.currency ?? targets[0]?.currency ?? opportunities[0]?.currency ?? leads[0]?.currency ?? "INR", targetRevenue, actualRevenue, targetAchievement: percentage(actualRevenue, targetRevenue), leadCount, qualifiedLeadCount, convertedLeadCount, conversionRate, customerCount: customers.length, pipelineValue, weightedPipeline, employeeCount, channelPartnerCount: partnerCount, avgFirstResponseMinutes, delayedLeadCount: delayed.length, ...capacity, ...opportunityInputs, ...opportunity, ...lost };
};

export const overviewAnalytics = async (viewer: SessionUser) => { const scope = await resolveSalesScope(viewer); return { ...(await analyticsForScope(scope)), trend: await salesTrend(scope) }; };
export const selfAnalytics = async (viewer: SessionUser) => { const scope = await resolveSalesScope(viewer); if (!scope.employeeId) return overviewAnalytics(viewer); return { ...(await analyticsForScope(scope, { employeeId: scope.employeeId })), trend: await salesTrend(scope, { employeeId: scope.employeeId }) }; };
export const employeeAnalytics = async (viewer: SessionUser, employeeId: string) => { const scope = await resolveSalesScope(viewer); assertSalesEmployeeScope(scope, employeeId); return { ...(await analyticsForScope(scope, { employeeId })), trend: await salesTrend(scope, { employeeId }) }; };
export const territoryAnalytics = async (viewer: SessionUser, territoryId: string) => { const scope = await resolveSalesScope(viewer); assertSalesTerritoryScope(scope, territoryId); const descendants = await SalesTerritory.find({ $or: [{ _id: territoryId }, { ancestors: territoryId }] }).distinct("_id"); const allowed = descendants.filter((id) => scope.allowedTerritoryIds.some((allowedId) => allowedId.equals(id))); return { ...(await analyticsForScope(scope, { territoryIds: allowed })), trend: await salesTrend(scope, { territoryIds: allowed }) }; };
export const geoAnalytics = async (viewer: SessionUser, geoId: string) => { const scope = await resolveSalesScope(viewer); assertSalesGeoScope(scope, geoId); const descendants = await descendantGeoIds(geoId); const allowed = descendants.filter((id) => scope.allowedGeoIds.some((candidate) => candidate.equals(id))); return { ...(await analyticsForScope(scope, { geoIds: allowed })), trend: await salesTrend(scope, { geoIds: allowed }) }; };
export const salesTrend = async (scope: ResolvedSalesScope, options: Pick<AnalyticsOptions, "employeeId" | "territoryIds" | "geoIds"> = {}) => { const start = new Date(); start.setUTCDate(1); start.setUTCHours(0, 0, 0, 0); start.setUTCMonth(start.getUTCMonth() - 5); const employeeIds = options.employeeId ? scope.allowedEmployeeIds.filter((id) => id.toString() === options.employeeId) : scope.allowedEmployeeIds; const territoryIds = options.territoryIds ?? scope.allowedTerritoryIds; return SalesRevenueTransaction.aggregate<{ _id: string; revenue: number }>([{ $match: { employee: { $in: employeeIds }, territory: { $in: territoryIds }, transactionDate: { $gte: start }, ...(options.geoIds ? { geoNode: { $in: options.geoIds } } : {}) } }, { $group: { _id: { $dateToString: { date: "$transactionDate", format: "%Y-%m" } }, revenue: { $sum: "$amount" } } }, { $sort: { _id: 1 } }]); };
export const listSalesEmployees = async (viewer: SessionUser) => { const scope = await resolveSalesScope(viewer); return Employee.find({ _id: { $in: scope.allowedEmployeeIds }, isActive: true }).select("firstName lastName employeeId status department designation reportingManager workLocation").populate("department designation reportingManager", "name code firstName lastName employeeId").sort({ firstName: 1 }).lean(); };
