/* eslint-disable @typescript-eslint/no-unused-expressions */
import { useMemo, useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { FileSpreadsheet, Upload, X } from "lucide-react";
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";
import { workApi, type LeadImportPreview, type Project, type Task } from "./workApi";

const canonical=[['custom','Preserve as imported data'],['name','Full lead name'],['firstName','First name'],['lastName','Last name'],['phone','Phone'],['email','Email'],['companyName','Company'],['market','City / market'],['source','Source'],['notes','Existing notes / requirement'],['estimatedValue','Lead value']];
export const LeadImportDialog=({projects,employees,onClose,onCreated}:{projects:Project[];employees:Array<{_id:string;firstName:string;lastName:string;status?:string}>;onClose:()=>void;onCreated:(task:Task)=>Promise<void>})=>{
 const [step,setStep]=useState(1); const [file,setFile]=useState<File>(); const [preview,setPreview]=useState<LeadImportPreview>(); const [mapping,setMapping]=useState<Record<string,string>>({}); const [excluded,setExcluded]=useState<Set<number>>(new Set());
 const [task,setTask]=useState({name:"",description:"",project:"",assignedEmployee:"",priority:"MEDIUM",complexity:"MEDIUM",estimatedHours:4,deadline:new Date(Date.now()+7*86400000).toISOString().slice(0,10)});
 const parse=useMutation({mutationFn:(sheet?:string)=>workApi.previewLeadImport(file!,sheet),onSuccess:(data)=>{setPreview(data);setMapping(data.suggestedMapping);setStep(3);}});
 const commit=useMutation({mutationFn:()=>workApi.commitLeadImport({idempotencyKey:crypto.randomUUID(),fileName:preview!.fileName,fileHash:preview!.fileHash,sheetName:preview!.selectedSheet,mapping,rows:preview!.allRows.map(r=>({...r,excluded:excluded.has(r.rowNumber)})),task:{...task,estimatedHours:Number(task.estimatedHours)}}),onSuccess:async(data)=>{await onCreated(data.task);onClose();}});
 const valid=useMemo(()=>preview?.allRows.filter(r=>!excluded.has(r.rowNumber)&&Object.values(r.values).some(Boolean)).length??0,[preview,excluded]);
 return <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/45 p-3 backdrop-blur-sm sm:p-8"><div role="dialog" aria-modal="true" aria-labelledby="lead-import-title" className="mx-auto w-full max-w-5xl rounded-2xl bg-white shadow-2xl"><header className="flex items-start border-b p-5"><div className="grid size-11 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><FileSpreadsheet/></div><div className="ml-3"><h2 id="lead-import-title" className="text-xl font-semibold">Create lead list task</h2><p className="mt-1 text-sm text-slate-500">Assign a private spreadsheet as accountable lead work.</p></div><button type="button" aria-label="Close" className="ml-auto grid size-11 place-items-center rounded-xl hover:bg-slate-100" onClick={onClose}><X size={18}/></button></header>
 <div className="border-b px-5 py-4"><ol className="flex gap-2 text-xs font-semibold">{['Task details','Upload','Map & review'].map((label,i)=><li key={label} className={`flex-1 rounded-lg px-3 py-2 text-center ${step===i+1?'bg-brand-600 text-white':'bg-slate-100 text-slate-500'}`}>{i+1}. {label}</li>)}</ol></div>
 <div className="p-5 sm:p-7">{step===1&&<div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium sm:col-span-2">Task title<Input required className="mt-2" value={task.name} onChange={e=>setTask({...task,name:e.target.value})} placeholder="Follow up with September Expo leads"/></label><label className="text-sm font-medium">Project<select className="mt-2 h-11 w-full rounded-xl border bg-white px-3" value={task.project} onChange={e=>setTask({...task,project:e.target.value})}><option value="">Select project</option>{projects.map(p=><option key={p._id} value={p._id}>{p.name}</option>)}</select></label><label className="text-sm font-medium">Assigned employee<select className="mt-2 h-11 w-full rounded-xl border bg-white px-3" value={task.assignedEmployee} onChange={e=>setTask({...task,assignedEmployee:e.target.value})}><option value="">Select employee</option>{employees.map(e=><option key={e._id} value={e._id}>{e.firstName} {e.lastName}</option>)}</select></label><label className="text-sm font-medium">Priority<select className="mt-2 h-11 w-full rounded-xl border bg-white px-3" value={task.priority} onChange={e=>setTask({...task,priority:e.target.value})}>{['LOW','MEDIUM','HIGH','CRITICAL'].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-sm font-medium">Due date<Input type="date" className="mt-2" value={task.deadline} onChange={e=>setTask({...task,deadline:e.target.value})}/></label><label className="text-sm font-medium sm:col-span-2">Instructions<textarea className="mt-2 min-h-24 w-full rounded-xl border p-3 text-sm" maxLength={5000} value={task.description} onChange={e=>setTask({...task,description:e.target.value})}/></label></div>}
 {step===2&&<div><label className="flex min-h-64 cursor-pointer flex-col items-center justify-center rounded-2xl border-2 border-dashed border-slate-300 bg-slate-50 p-8 text-center hover:border-brand-400"><Upload className="text-brand-600"/><span className="mt-4 font-semibold">Upload lead sheet</span><span className="mt-1 text-sm text-slate-500">CSV or XLSX · maximum 10 MB · 5,000 rows</span><input className="sr-only" type="file" accept=".csv,.xlsx" onChange={e=>setFile(e.target.files?.[0])}/>{file&&<span className="mt-4 rounded-lg bg-white px-3 py-2 text-sm shadow-sm">{file.name}</span>}</label>{parse.error&&<p className="mt-3 rounded-xl bg-red-50 p-3 text-sm text-red-700">{parse.error.message}</p>}</div>}
 {step===3&&preview&&<div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[['Rows',preview.totalRows],['Ready',valid],['Empty',preview.emptyRows],['Excluded',excluded.size]].map(([a,b])=><div className="rounded-xl border p-3" key={a}><p className="text-xs text-slate-500">{a}</p><p className="mt-1 text-xl font-semibold">{b}</p></div>)}</div><h3 className="mt-6 font-semibold">Column mapping</h3><div className="mt-3 grid gap-3 sm:grid-cols-2">{preview.columns.map(h=><label className="flex items-center justify-between gap-3 rounded-xl border p-3 text-sm" key={h}><span className="truncate font-medium" title={h}>{h}</span><select className="h-10 max-w-52 rounded-lg border bg-white px-2" value={mapping[h]} onChange={e=>setMapping({...mapping,[h]:e.target.value})}>{canonical.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label>)}</div><h3 className="mt-6 font-semibold">Preview</h3><div className="mt-3 max-h-72 overflow-auto rounded-xl border"><table className="min-w-full text-left text-xs"><thead className="sticky top-0 bg-slate-100"><tr><th className="p-3">Include</th>{preview.columns.slice(0,6).map(h=><th className="whitespace-nowrap p-3" key={h}>{h}</th>)}</tr></thead><tbody>{preview.rows.slice(0,50).map(r=><tr className="border-t" key={r.rowNumber}><td className="p-3"><input aria-label={`Include row ${r.rowNumber}`} type="checkbox" checked={!excluded.has(r.rowNumber)} onChange={()=>setExcluded(old=>{const next=new Set(old);next.has(r.rowNumber)?next.delete(r.rowNumber):next.add(r.rowNumber);return next;})}/></td>{preview.columns.slice(0,6).map(h=><td className="max-w-48 truncate p-3" title={r.values[h]} key={h}>{r.values[h]||'—'}</td>)}</tr>)}</tbody></table></div>{commit.error&&<p className="mt-3 rounded-xl bg-red-50 p-3 text-sm text-red-700">{commit.error.message}</p>}</div>}</div>
 <footer className="flex justify-between border-t p-5"><Button variant="ghost" onClick={()=>step===1?onClose():setStep(step-1)}>Back</Button>{step===1?<Button disabled={!task.name||!task.project||!task.assignedEmployee} onClick={()=>setStep(2)}>Continue</Button>:step===2?<Button disabled={!file||parse.isPending} onClick={()=>parse.mutate(undefined)}>{parse.isPending?'Parsing securely…':'Review columns'}</Button>:<Button disabled={!valid||commit.isPending} onClick={()=>commit.mutate()}>{commit.isPending?'Creating task…':`Import ${valid} leads`}</Button>}</footer></div></div>;
};
