import { useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { CheckCircle2, Clock3, History, RotateCcw, X } from "lucide-react";
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";
import { useAuth } from "@/features/auth/AuthProvider";
import { workApi, type Task } from "./workApi";

export const TaskDrawer = ({ task, onClose, onRefresh }: { task:Task; onClose:()=>void; onRefresh:()=>Promise<unknown> }) => {
  const { user }=useAuth(); const canReview=user?.permissions.includes("task.review");
  const [rating,setRating]=useState(4); const [comment,setComment]=useState(""); const [actualHours,setActualHours]=useState(task.actualHours??task.estimatedHours);
  const [completionNote,setCompletionNote]=useState(task.completionNote??""); const [deliverableUrl,setDeliverableUrl]=useState(task.deliverableUrl??""); const [businessImpact,setBusinessImpact]=useState(task.businessImpact??"");
  const activity=useQuery({queryKey:["task",task._id,"activity"],queryFn:()=>workApi.activity(task._id)});
  const action=useMutation({mutationFn:(body:{status:string;actualHours?:number;completionNote?:string;deliverableUrl?:string;businessImpact?:string})=>workApi.transition(task._id,body),onSuccess:async()=>{await onRefresh();onClose();}});
  const review=useMutation({mutationFn:(approve:boolean)=>workApi.review(task._id,{qualityRating:Number(rating),reviewComment:comment||undefined,approve}),onSuccess:async()=>{await onRefresh();onClose();}});
  return <div className="fixed inset-0 z-50 bg-ink/30 backdrop-blur-sm" onMouseDown={(e)=>{if(e.target===e.currentTarget)onClose();}}><aside className="ml-auto h-full w-full max-w-xl overflow-y-auto bg-white shadow-2xl">
    <header className="sticky top-0 z-10 flex items-start border-b bg-white/95 p-6 backdrop-blur"><div><p className="text-xs font-semibold text-brand-700">{task.taskId}</p><h2 className="mt-1 text-xl font-semibold">{task.name}</h2><p className="mt-1 text-sm text-slate-400">{task.project.name}</p></div><button className="ml-auto grid size-9 place-items-center rounded-xl hover:bg-slate-100" aria-label="Close task" onClick={onClose}><X size={18}/></button></header>
    <div className="p-6"><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[{label:"Status",value:task.status.replaceAll("_"," ")},{label:"Priority",value:task.priority},{label:"Estimate",value:`${task.estimatedHours}h`},{label:"Reopens",value:task.reopenCount}].map((x)=><div className="rounded-xl bg-slate-50 p-3" key={x.label}><p className="text-[10px] uppercase text-slate-400">{x.label}</p><p className="mt-1 text-xs font-semibold">{x.value}</p></div>)}</div>
    {task.description&&<p className="mt-6 text-sm leading-6 text-slate-600">{task.description}</p>}
    <section className="mt-7 rounded-2xl border p-5"><h3 className="font-semibold">Task actions</h3><div className="mt-4 flex flex-wrap gap-2">{task.status==="NOT_STARTED"&&<Button onClick={()=>action.mutate({status:"IN_PROGRESS"})}>Start task</Button>}{task.status==="BLOCKED"&&<Button onClick={()=>action.mutate({status:"IN_PROGRESS"})}>Resume task</Button>}{task.status==="COMPLETED"&&<Button variant="secondary" onClick={()=>action.mutate({status:"REOPENED"})}><RotateCcw size={15}/>Reopen</Button>}</div>
    {["IN_PROGRESS","REOPENED"].includes(task.status)&&<div className="mt-4 space-y-3"><label className="block text-sm font-medium">Actual hours<Input type="number" min="0" step=".25" className="mt-2" value={actualHours} onChange={(e)=>setActualHours(Number(e.target.value))}/><span className="mt-1 block text-xs font-normal text-slate-400">Hours are estimation evidence only; they never raise a score by themselves.</span></label><label className="block text-sm font-medium">Completion note<textarea className="mt-2 min-h-24 w-full rounded-xl border p-3 text-sm" placeholder="What was delivered and how was it verified?" value={completionNote} onChange={(e)=>setCompletionNote(e.target.value)}/></label><label className="block text-sm font-medium">Deliverable link (optional)<Input type="url" className="mt-2" value={deliverableUrl} onChange={(e)=>setDeliverableUrl(e.target.value)}/></label><label className="block text-sm font-medium">Business/customer impact (optional)<textarea className="mt-2 min-h-20 w-full rounded-xl border p-3 text-sm" value={businessImpact} onChange={(e)=>setBusinessImpact(e.target.value)}/></label><Button disabled={completionNote.trim().length<10||action.isPending} onClick={()=>action.mutate({status:"IN_REVIEW",actualHours:Number(actualHours),completionNote,deliverableUrl,businessImpact})}>Submit evidence for review</Button></div>}
    {task.completionNote&&<div className="mt-5 rounded-xl bg-slate-50 p-4 text-sm"><p className="font-medium">Completion evidence</p><p className="mt-2 text-slate-600">{task.completionNote}</p>{task.deliverableUrl&&<a className="mt-2 block text-brand-700 underline" href={task.deliverableUrl} target="_blank" rel="noreferrer">Open deliverable</a>}{task.businessImpact&&<p className="mt-2 text-slate-600">Impact: {task.businessImpact}</p>}</div>}
    {task.status==="IN_REVIEW"&&canReview&&<div className="mt-5 border-t pt-5"><div className="grid grid-cols-[100px_1fr] gap-3"><label className="text-sm font-medium">Quality<Input type="number" min="1" max="5" className="mt-2" value={rating} onChange={(e)=>setRating(Number(e.target.value))}/></label><label className="text-sm font-medium">Review comment<Input className="mt-2" value={comment} onChange={(e)=>setComment(e.target.value)}/></label></div><div className="mt-3 flex gap-2"><Button variant="secondary" onClick={()=>review.mutate(false)}><RotateCcw size={15}/>Request rework</Button><Button onClick={()=>review.mutate(true)}><CheckCircle2 size={15}/>Approve</Button></div></div>}{task.status==="IN_REVIEW"&&!canReview&&<p className="mt-5 rounded-xl bg-blue-50 p-3 text-sm text-blue-700">Submitted successfully. Waiting for a manager or reviewer.</p>}</section>
    <section className="mt-7"><div className="flex items-center"><History size={17} className="text-brand-600"/><h3 className="ml-2 font-semibold">Activity timeline</h3></div><div className="mt-4">{activity.data?.items.map((item,index)=><div className="relative flex gap-3 pb-5" key={item._id}>{index<(activity.data?.items.length??0)-1&&<div className="absolute left-3 top-6 h-full w-px bg-slate-200"/>}<div className="relative grid size-6 shrink-0 place-items-center rounded-full border bg-white"><Clock3 size={11}/></div><div><p className="text-sm font-medium">{item.action.replaceAll("_"," ")}</p><p className="mt-1 text-xs text-slate-400">{item.performedBy?.name??"System"} · {new Date(item.createdAt).toLocaleString()}</p></div></div>)}</div></section></div>
  </aside></div>;
};
