import { useEffect, useRef, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Check, FileAudio, History, Mic, MicOff, Sparkles, X } from "lucide-react";
import type { RoleName } from "@mobiusbloom/shared";
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";
import { workApi, type VoiceDraft, type VoicePreview } from "./workApi";

const statuses = ["NOT_STARTED", "IN_PROGRESS", "BLOCKED", "IN_REVIEW", "COMPLETED", "REOPENED", "CANCELLED"];
const priorities = ["LOW", "MEDIUM", "HIGH", "CRITICAL"];
const complexities = ["EASY", "MEDIUM", "HARD", "VERY_HARD"];
const blockerReasons = ["WAITING_FOR_MANAGER", "WAITING_FOR_CLIENT", "TECHNICAL_ISSUE", "DEPENDENCY", "ACCESS_REQUIRED", "REQUIREMENT_UNCLEAR", "EXTERNAL_DEPENDENCY", "OTHER"];
const transitionTargets: Record<string, string[]> = { NOT_STARTED: ["IN_PROGRESS", "BLOCKED", "CANCELLED"], IN_PROGRESS: ["BLOCKED", "IN_REVIEW", "CANCELLED"], BLOCKED: ["IN_PROGRESS", "CANCELLED"], IN_REVIEW: ["COMPLETED", "REOPENED", "IN_PROGRESS"], COMPLETED: ["REOPENED"], REOPENED: ["IN_PROGRESS", "BLOCKED", "IN_REVIEW", "CANCELLED"], CANCELLED: [] };

export const VoiceTaskDialog = ({ role, onClose, onSuccess }: { role: RoleName; onClose: () => void; onSuccess: () => Promise<void> }) => {
  const queryClient = useQueryClient(); const isEmployee = role === "EMPLOYEE";
  const recorder = useRef<MediaRecorder | null>(null); const stream = useRef<MediaStream | null>(null); const chunks = useRef<Blob[]>([]);
  const [recording, setRecording] = useState(false); const [seconds, setSeconds] = useState(0); const [typed, setTyped] = useState("");
  const [preview, setPreview] = useState<VoicePreview | null>(null); const [draft, setDraft] = useState<VoiceDraft | null>(null); const [localError, setLocalError] = useState("");
  const history = useQuery({ queryKey: ["voice-history"], queryFn: workApi.voiceHistory });
  const previewMutation = useMutation({ mutationFn: (audio: Blob) => workApi.voicePreview(audio), onSuccess: (data) => { setPreview(data); setDraft(data.draft); setLocalError(""); void queryClient.invalidateQueries({ queryKey: ["voice-history"] }); } });
  const fileMutation = useMutation({ mutationFn: (file: File) => workApi.voicePreviewFile(file), onSuccess: (data) => { setPreview(data); setDraft(data.draft); setLocalError(""); void queryClient.invalidateQueries({ queryKey: ["voice-history"] }); } });
  const textMutation = useMutation({ mutationFn: () => workApi.voicePreviewText(typed), onSuccess: (data) => { setPreview(data); setDraft(data.draft); setLocalError(""); void queryClient.invalidateQueries({ queryKey: ["voice-history"] }); } });
  const confirm = useMutation({ mutationFn: () => workApi.voiceConfirm(preview!.command.id, draft!), onSuccess: async () => { await onSuccess(); await queryClient.invalidateQueries({ queryKey: ["voice-history"] }); onClose(); } });
  const pending = previewMutation.isPending || fileMutation.isPending || textMutation.isPending;
  const error = localError || previewMutation.error?.message || fileMutation.error?.message || textMutation.error?.message || confirm.error?.message;

  useEffect(() => { if (!recording) return; const timer = window.setInterval(() => setSeconds((value) => value + 1), 1000); return () => window.clearInterval(timer); }, [recording]);
  useEffect(() => () => stream.current?.getTracks().forEach((track) => track.stop()), []);

  const startRecording = async () => {
    try {
      if (!navigator.mediaDevices?.getUserMedia || typeof MediaRecorder === "undefined") throw new Error("Voice recording is not supported in this browser. Upload an audio file instead.");
      stream.current = await navigator.mediaDevices.getUserMedia({ audio: { echoCancellation: true, noiseSuppression: true } }); chunks.current = []; setSeconds(0);
      const preferred = ["audio/webm;codecs=opus", "audio/webm", "audio/ogg;codecs=opus"].find((type) => MediaRecorder.isTypeSupported(type));
      recorder.current = new MediaRecorder(stream.current, preferred ? { mimeType: preferred } : undefined);
      recorder.current.ondataavailable = (event) => { if (event.data.size) chunks.current.push(event.data); };
      recorder.current.onstop = () => { const audio = new Blob(chunks.current, { type: recorder.current?.mimeType || "audio/webm" }); stream.current?.getTracks().forEach((track) => track.stop()); setRecording(false); if (audio.size > 0) previewMutation.mutate(audio); };
      recorder.current.start(250); setRecording(true); setLocalError("");
    } catch (cause) { setLocalError(cause instanceof Error ? cause.message : "Microphone access failed"); }
  };
  const stopRecording = () => { if (recorder.current?.state === "recording") recorder.current.stop(); };
  const close = () => { stream.current?.getTracks().forEach((track) => track.stop()); if (preview?.command.status === "TRANSCRIBED") void workApi.voiceCancel(preview.command.id); onClose(); };
  const update = <K extends keyof VoiceDraft>(key: K, value: VoiceDraft[K]) => setDraft((current) => current ? { ...current, [key]: value } : current);
  const selectedTask = preview?.options.tasks.find((item) => item.id === draft?.task);
  const validStatuses = selectedTask?.status ? transitionTargets[selectedTask.status] ?? statuses : statuses;

  return <div className="fixed inset-0 z-50 overflow-y-auto bg-ink/40 p-4 backdrop-blur-sm"><div className="mx-auto my-4 w-full max-w-3xl rounded-3xl bg-white shadow-2xl">
    <header className="flex items-start border-b p-6"><div className="grid size-11 place-items-center rounded-2xl bg-gradient-to-br from-brand-500 to-violet-700 text-white"><Mic size={20}/></div><div className="ml-3"><h2 className="text-xl font-semibold">Voice task assistant</h2><p className="mt-1 text-sm text-slate-500">{isEmployee ? "Create or update your tasks by speaking." : "Assign work or update any task by speaking."} Audio is processed by your local Whisper model.</p></div><button type="button" className="ml-auto grid size-9 place-items-center rounded-lg text-slate-400 hover:bg-slate-100" onClick={close} aria-label="Close"><X size={18}/></button></header>

    {!preview && <section className="p-6"><div className={`grid place-items-center rounded-3xl border-2 border-dashed px-6 py-10 text-center ${recording ? "border-red-300 bg-red-50" : "border-violet-200 bg-violet-50/50"}`}><button type="button" disabled={pending} onClick={recording ? stopRecording : startRecording} className={`grid size-20 place-items-center rounded-full text-white shadow-lg transition hover:scale-105 ${recording ? "animate-pulse bg-red-500" : "bg-brand-600"}`}>{recording ? <MicOff size={30}/> : <Mic size={30}/>}</button><h3 className="mt-4 font-semibold">{recording ? `Listening… ${seconds}s` : pending ? "Turning voice into a task…" : "Tap to speak"}</h3><p className="mt-2 max-w-lg text-sm text-slate-500">Try: “{isEmployee ? "My task is to finish the payroll report by Friday, high priority" : "Assign Priya the monthly report task by Friday, high priority"}.”</p>{recording && <Button className="mt-4 bg-red-600 hover:bg-red-700" onClick={stopRecording}><MicOff size={16}/> Stop and transcribe</Button>}</div>
      <div className="mt-5 grid gap-4 md:grid-cols-2"><label className="flex cursor-pointer items-center justify-center gap-2 rounded-xl border px-4 py-3 text-sm font-semibold text-brand-700 hover:bg-brand-50"><FileAudio size={17}/> Upload recording<input className="sr-only" type="file" accept="audio/webm,audio/ogg,audio/wav,audio/mpeg,audio/mp4,.m4a" onChange={(event) => { const file = event.target.files?.[0]; if (file) fileMutation.mutate(file); }}/></label><div className="flex gap-2"><Input placeholder="Or type the command to test" value={typed} onChange={(event) => setTyped(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && typed.trim().length >= 2) textMutation.mutate(); }}/><Button variant="secondary" disabled={typed.trim().length < 2 || pending} onClick={() => textMutation.mutate()}><Sparkles size={16}/> Interpret</Button></div></div>
      {error && <p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}
    </section>}

    {preview && draft && <form className="p-6" onSubmit={(event) => { event.preventDefault(); confirm.mutate(); }}><div className="rounded-2xl bg-slate-50 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><span className="text-xs font-semibold uppercase tracking-wide text-brand-700">Transcript</span><span className="rounded-full bg-white px-2.5 py-1 text-xs text-slate-500">{Math.round(preview.command.confidence * 100)}% interpretation confidence{preview.command.language ? ` · ${preview.command.language}` : ""}</span></div><p className="mt-2 text-sm leading-6 text-slate-700">“{preview.command.transcript}”</p></div>
      <div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium sm:col-span-2">Action<select className="mt-2 h-11 w-full rounded-xl border bg-white px-3" value={draft.action} onChange={(event) => { const action = event.target.value as VoiceDraft["action"]; setDraft(action === "UPDATE_STATUS" ? { action, task: preview.options.tasks[0]?.id, status: preview.options.tasks[0]?.status ? transitionTargets[preview.options.tasks[0].status]?.[0] : "IN_PROGRESS", completionNote: preview.command.transcript } : { action, name: preview.command.transcript.slice(0, 200), description: preview.command.transcript, project: preview.options.projects[0]?.id, assignedEmployee: isEmployee ? preview.options.employees[0]?.id : undefined, verbalAssigner: isEmployee ? "Voice self-report" : undefined, priority: "MEDIUM", complexity: "MEDIUM", estimatedHours: 1, deadline: new Date(Date.now() + 86_400_000).toISOString() }); }}><option value="CREATE_TASK">Create a task</option><option value="UPDATE_STATUS">Update task status</option></select></label>
      {draft.action === "CREATE_TASK" ? <>
        <label className="text-sm font-medium sm:col-span-2">Task name<Input required minLength={2} className="mt-2" value={draft.name ?? ""} onChange={(event) => update("name", event.target.value)}/></label>
        <label className="text-sm font-medium">Project<select required className="mt-2 h-11 w-full rounded-xl border bg-white px-3" value={draft.project ?? ""} onChange={(event) => update("project", event.target.value)}><option value="">Select project</option>{preview.options.projects.map((item) => <option value={item.id} key={item.id}>{item.label}{item.detail ? ` (${item.detail})` : ""}</option>)}</select></label>
        {isEmployee ? <label className="text-sm font-medium">Assigned verbally by<Input required className="mt-2" value={draft.verbalAssigner ?? ""} onChange={(event) => update("verbalAssigner", event.target.value)}/></label> : <label className="text-sm font-medium">Assign to<select required className="mt-2 h-11 w-full rounded-xl border bg-white px-3" value={draft.assignedEmployee ?? ""} onChange={(event) => update("assignedEmployee", event.target.value)}><option value="">Select employee</option>{preview.options.employees.map((item) => <option value={item.id} key={item.id}>{item.label}{item.detail ? ` (${item.detail})` : ""}</option>)}</select></label>}
        <label className="text-sm font-medium">Deadline<Input required type="date" className="mt-2" value={draft.deadline?.slice(0, 10) ?? ""} onChange={(event) => update("deadline", event.target.value)}/></label>
        <label className="text-sm font-medium">Estimated hours<Input required type="number" min=".25" step=".25" className="mt-2" value={draft.estimatedHours ?? 1} onChange={(event) => update("estimatedHours", Number(event.target.value))}/></label>
        <label className="text-sm font-medium">Priority<select className="mt-2 h-11 w-full rounded-xl border bg-white px-3" value={draft.priority ?? "MEDIUM"} onChange={(event) => update("priority", event.target.value)}>{priorities.map((item) => <option key={item}>{item}</option>)}</select></label>
        <label className="text-sm font-medium">Complexity<select className="mt-2 h-11 w-full rounded-xl border bg-white px-3" value={draft.complexity ?? "MEDIUM"} onChange={(event) => update("complexity", event.target.value)}>{complexities.map((item) => <option key={item}>{item.replaceAll("_", " ")}</option>)}</select></label>
        <label className="text-sm font-medium sm:col-span-2">Description<textarea rows={3} className="mt-2 w-full resize-none rounded-xl border px-3 py-2 text-sm" value={draft.description ?? ""} onChange={(event) => update("description", event.target.value)}/></label>
      </> : <>
        <label className="text-sm font-medium">Task<select required className="mt-2 h-11 w-full rounded-xl border bg-white px-3" value={draft.task ?? ""} onChange={(event) => { const task = preview.options.tasks.find((item) => item.id === event.target.value); setDraft((current) => current ? { ...current, task: event.target.value, status: task?.status ? transitionTargets[task.status]?.[0] : "IN_PROGRESS" } : current); }}><option value="">Select task</option>{preview.options.tasks.map((item) => <option value={item.id} key={item.id}>{item.detail} · {item.label} ({item.status?.replaceAll("_", " ")})</option>)}</select></label>
        <label className="text-sm font-medium">New status<select required className="mt-2 h-11 w-full rounded-xl border bg-white px-3" value={draft.status ?? ""} onChange={(event) => update("status", event.target.value)}><option value="">Select status</option>{validStatuses.map((item) => <option value={item} key={item}>{item.replaceAll("_", " ")}</option>)}</select></label>
        {draft.status === "BLOCKED" && <><label className="text-sm font-medium">Blocker reason<select className="mt-2 h-11 w-full rounded-xl border bg-white px-3" value={draft.blockerReason ?? "OTHER"} onChange={(event) => update("blockerReason", event.target.value)}>{blockerReasons.map((item) => <option key={item}>{item.replaceAll("_", " ")}</option>)}</select></label><label className="text-sm font-medium">Blocker note<Input className="mt-2" value={draft.blockerComment ?? ""} onChange={(event) => update("blockerComment", event.target.value)}/></label></>}
        <label className="text-sm font-medium sm:col-span-2">Update note<textarea required={draft.status === "IN_REVIEW"} minLength={draft.status === "IN_REVIEW" ? 10 : undefined} rows={3} className="mt-2 w-full resize-none rounded-xl border px-3 py-2 text-sm" value={draft.completionNote ?? ""} onChange={(event) => update("completionNote", event.target.value)}/></label>
      </>}</div>
      {error && <p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="mt-6 flex flex-wrap justify-end gap-2"><Button type="button" variant="ghost" onClick={() => { void workApi.voiceCancel(preview.command.id); setPreview(null); setDraft(null); }}>Discard</Button><Button disabled={confirm.isPending}><Check size={16}/>{confirm.isPending ? "Applying…" : draft.action === "CREATE_TASK" ? "Confirm and create" : "Confirm update"}</Button></div>
    </form>}

    <section className="border-t px-6 py-5"><div className="flex items-center gap-2"><History size={16} className="text-slate-400"/><h3 className="text-sm font-semibold">{role === "SUPER_ADMIN" ? "Organization voice history" : "Your recent voice commands"}</h3></div><div className="mt-3 max-h-44 space-y-2 overflow-y-auto">{history.data?.items.slice(0, 8).map((item) => <div className="flex items-start gap-3 rounded-xl border p-3" key={item._id}><span className={`mt-1 size-2 shrink-0 rounded-full ${item.status === "CONFIRMED" ? "bg-emerald-500" : item.status === "CANCELLED" ? "bg-slate-300" : "bg-amber-400"}`}/><div className="min-w-0 flex-1"><p className="truncate text-xs text-slate-600">{item.transcript}</p><p className="mt-1 text-[10px] text-slate-400">{role === "SUPER_ADMIN" ? `${item.actor.name} · ` : ""}{item.intent.replaceAll("_", " ")} · {item.status} · {new Date(item.createdAt).toLocaleString()}</p></div>{item.task && <span className="shrink-0 text-[10px] font-semibold text-brand-700">{item.task.taskId}</span>}</div>)}{history.data?.items.length === 0 && <p className="py-3 text-sm text-slate-400">No voice commands yet.</p>}</div></section>
  </div></div>;
};
