// @ts-nocheck
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, CheckCircle2, Target } from "lucide-react";
import { salesApi } from "../salesApi";
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";
import { useState, type ChangeEvent } from "react";

const money = (n: number) => `₹${Math.round(n).toLocaleString("en-IN")}`;
export const TargetPerformancePage = () => { const qc = useQueryClient(); const [commit, setCommit] = useState(""); const query = useQuery({ queryKey: ["target-performance"], queryFn: salesApi.targetPerformance }); const item = query.data?.items?.[0]; const mutation = useMutation({ mutationFn: () => salesApi.commitment(item!.target._id, { committedRevenue: Number(commit) }), onSuccess: () => { setCommit(""); qc.invalidateQueries({ queryKey: ["target-performance"] }); } });
  if (query.isLoading) return <main className="p-8">Loading target performance…</main>; if (!item) return <main className="p-8"><h1 className="text-2xl font-semibold">My sales target</h1><p className="mt-4 text-slate-500">No active target is assigned yet.</p></main>; const p = item.performance; return <main className="space-y-6 p-4 sm:p-8"><div><p className="text-xs font-semibold uppercase tracking-widest text-brand-700">My sales</p><h1 className="mt-1 text-3xl font-semibold">Target & performance</h1></div><section className="rounded-2xl bg-slate-900 p-6 text-white"><div className="flex items-center gap-2 text-sm text-slate-300"><Target size={18}/> Official target</div><div className="mt-3 text-4xl font-semibold">{money(p.actualAchievement)} <span className="text-xl text-slate-400">/ {money(p.officialTarget)}</span></div><div className="mt-4 h-3 overflow-hidden rounded-full bg-slate-700"><div className="h-full rounded-full bg-emerald-400" style={{ width: `${Math.min(100, p.achievementPercentage)}%` }}/></div><div className="mt-2 flex justify-between text-sm"><span>{p.achievementPercentage}% achieved</span><span>{p.daysRemaining} days left</span></div></section><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Remaining target",money(p.remainingOfficialTarget)],["Required daily pace",money(p.requiredDailyRunRate)],["Required weekly pace",money(p.requiredWeeklyRunRate)],["Projected achievement",`${p.projectedAchievementPercentage}%`]].map(([label,value])=><div className="rounded-2xl border bg-white p-5" key={label}><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></div>)}</div><section className={`rounded-2xl border p-5 ${p.status === "AT_RISK" || p.status === "CRITICAL" ? "border-amber-200 bg-amber-50" : "border-emerald-200 bg-emerald-50"}`}><div className="flex items-center gap-2 font-semibold">{p.status === "AT_RISK" || p.status === "CRITICAL" ? <AlertTriangle size={18}/> : <CheckCircle2 size={18}/>} Status: {p.status.replaceAll("_", " ")}</div><p className="mt-2 text-sm">Your official target remains unchanged. Commitment is tracked separately and does not affect compensation unless policy says so.</p></section><section className="rounded-2xl border bg-white p-5"><h2 className="font-semibold">My commitment</h2><p className="mt-1 text-sm text-slate-500">Current: {p.employeeCommitment == null ? "Not set" : money(p.employeeCommitment)}</p><div className="mt-4 flex max-w-sm gap-2"><Input type="number" min="0" placeholder="Enter commitment" value={commit} onChange={e=>setCommit(e.target.value)}/><Button disabled={!commit || mutation.isPending} onClick={()=>mutation.mutate()}>Save</Button></div></section></main> };
